(()=>{"use strict";
const TOKEN="blueCurrentV3230Token",$=id=>document.getElementById(id),esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dates={Thanksgiving:"2026-11-26","Christmas Eve":"2026-12-24","Christmas Day":"2026-12-25","New Year's Eve":"2026-12-31","New Year's Day":"2027-01-01"};
let state=null,role="",job="book",room="Inlet Room",chosen=null,busy=false,timer=null;
function message(value,error=false){$("message").textContent=value;$("message").dataset.error=String(error);}
async function api(path,method="GET",body){const res=await fetch(path,{method,headers:{...(localStorage.getItem(TOKEN)?{Authorization:`Bearer ${localStorage.getItem(TOKEN)}`}:{}) ,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error||`Request failed (${res.status})`);return data;}
function showJob(next){if(next==="manager"&&!$("jobs").querySelector('[data-job="manager"]')?.hidden){job=next;}else if(["book","arrivals","floor"].includes(next))job=next;$("jobs").querySelectorAll("[data-job]").forEach(b=>b.setAttribute("aria-current",b.dataset.job===job?"page":"false"));document.querySelectorAll("[data-panel]").forEach(p=>p.hidden=p.dataset.panel!==job);if(job==="manager")loadManager();}
function render(){if(!state)return;const q=$("guestSearch").value.trim().toLowerCase();const phoneQuery=q.replace(/\D/g,"");const rows=state.reservations.filter(r=>!q||r.guestName.toLowerCase().includes(q)||(phoneQuery&&r.phone.includes(phoneQuery))).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
$("bookingList").innerHTML=rows.length?rows.map(r=>`<article class="card"><div><strong>${esc(r.guestName)}</strong><small>${esc(r.holidayEvent)} · ${esc(r.date)} · ${esc(r.time)} · Party ${esc(r.partySize)}</small><small>${esc(r.phone)}${r.tableId?` · ${esc(r.tableId)}`:""}</small></div><span class="status">${esc(r.status)}</span><div class="actions">${r.status==="confirmed"?`<button type="button" data-action="arrive" data-id="${esc(r.id)}">Mark arrived</button><button type="button" class="secondary" data-action="cancel" data-id="${esc(r.id)}">Cancel</button>`:r.status==="arrived"?`<button type="button" data-action="choose" data-id="${esc(r.id)}">Choose table</button><button type="button" class="secondary" data-action="cancel" data-id="${esc(r.id)}">Cancel</button>`:r.status==="seated"?`<button type="button" data-action="complete" data-id="${esc(r.id)}">Complete service</button>`:""}</div></article>`).join(""):'<p>No matching bookings.</p>';
$("rooms").innerHTML=["Inlet Room","Sunset Ballroom"].map(name=>`<button type="button" data-room="${esc(name)}" aria-pressed="${name===room}">${esc(name)}</button>`).join("");
$("floorMap").innerHTML=state.tables.filter(t=>t.room===room).map(t=>`<button type="button" class="table" data-table="${esc(t.id)}" data-status="${esc(t.status)}" aria-label="Table ${esc(t.id)}, ${esc(t.status)}"><strong>${esc(t.id)}</strong><small>${esc(t.status)}</small></button>`).join("");
$("seatPrompt").textContent=chosen?`Seat ${chosen.guestName}, party of ${chosen.partySize}. Tap an available ${room} table.`:`${room}: select an arrived party from Arrivals, or tap a cleaning table to mark it available.`;
}
async function refresh(silent=false){try{const next=await api("/api/harbor-point-demo");if(!state||next.version!==state.version){state=next;if(chosen)chosen=state.reservations.find(r=>r.id===chosen.id&&r.status==="arrived")||null;render();}if(!silent)message("Rehearsal ready. Fictional data only.");}catch(e){if(!silent)message(e.message,true);}}
async function mutate(path,payload,success){if(busy)return false;busy=true;document.querySelectorAll('.job button[type="submit"]').forEach(b=>b.disabled=true);try{await api(path,"POST",{...payload,version:state?.version});chosen=null;await refresh(true);message(success);return true;}catch(e){message(e.message,true);if(e.message.includes("changed on another device"))await refresh(true);return false;}finally{busy=false;document.querySelectorAll('.job button[type="submit"]').forEach(b=>b.disabled=false);}}
async function loadManager(){try{const data=await api("/api/harbor-point-demo/manager");$("managerSummary").innerHTML=[["Status",data.readiness],["Bookings",data.reservations],["Arrived",data.arrived],["Seated",data.seated],["Available sample tables",data.availableTables]].map(([label,value])=>`<div><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`).join("");$("readinessList").innerHTML=data.awaiting.map(item=>`<li>${esc(item)}</li>`).join("");}catch(e){message(e.message,true);}}
async function session(){try{const me=await api("/api/auth/me");if(!me.permissions?.includes("write_reservations"))throw Error("This account does not have host access.");role=me.role;$("operatorName").textContent=me.user.name;$("loginPanel").hidden=true;$("workspace").hidden=false;$("signOut").hidden=false;$("jobs").querySelector('[data-job="manager"]').hidden=!me.permissions.includes("write");await refresh();clearInterval(timer);timer=setInterval(()=>{if(!busy&&document.visibilityState==="visible")refresh(true);},3500);}catch(e){$("loginPanel").hidden=false;$("workspace").hidden=true;$("signOut").hidden=true;clearInterval(timer);timer=null;$("loginPanel").querySelector("h2").textContent=e.message.includes("Authentication")?"Sign in to Blue Current":e.message;}}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();const data=new FormData(e.currentTarget);try{const login=await api("/api/auth/login","POST",{email:data.get("email"),password:data.get("password")});localStorage.setItem(TOKEN,login.token);await session();}catch(error){$("loginPanel").querySelector("h2").textContent=error.message;}});
$("signOut").addEventListener("click",async()=>{try{await api("/api/auth/logout","POST",{});}catch{}localStorage.removeItem(TOKEN);state=null;await session();});
$("jobs").addEventListener("click",e=>{const b=e.target.closest("[data-job]");if(b)showJob(b.dataset.job);});
$("bookingForm").elements.holidayEvent.addEventListener("change",e=>{$("bookingForm").elements.date.value=dates[e.target.value];});
$("bookingForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget;if(await mutate("/api/harbor-point-demo/reservations",Object.fromEntries(new FormData(form)),"Booking saved. Find the guest in Arrivals when they arrive.")){form.elements.guestName.value="";form.elements.phone.value="";form.elements.notes.value="";}});
$("guestSearch").addEventListener("input",render);
$("bookingList").addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const row=state?.reservations.find(r=>r.id===b.dataset.id);if(!row)return;if(b.dataset.action==="choose"){chosen=row;showJob("floor");render();message(`Choose a table for ${row.guestName}.`);return;}mutate("/api/harbor-point-demo/actions",{reservationId:row.id,action:b.dataset.action},b.dataset.action==="arrive"?"Guest marked arrived. Choose a table when ready.":b.dataset.action==="complete"?"Service completed. Table now needs cleaning.":"Booking cancelled.");});
$("rooms").addEventListener("click",e=>{const b=e.target.closest("[data-room]");if(b){room=b.dataset.room;render();}});
$("floorMap").addEventListener("click",e=>{const b=e.target.closest("[data-table]");if(!b)return;const table=state?.tables.find(t=>t.id===b.dataset.table);if(!table)return;if(chosen){if(table.status!=="available"){message("Choose an available table.",true);return;}mutate("/api/harbor-point-demo/actions",{reservationId:chosen.id,action:"seat",tableId:table.id},`${chosen.guestName} seated at ${table.id}.`);return;}if(table.status==="cleaning")mutate("/api/harbor-point-demo/ready",{tableId:table.id},`${table.id} available again.`);else message(`${table.id} is ${table.status}. Select an arrived party to seat.`);});
if(localStorage.getItem(TOKEN))session();
})();
