(()=>{"use strict";
const TOKEN="blueCurrentV3230Token",$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let state=null,job="book",room="",chosen=null,busy=false,timer=null;
function message(text,error=false){$("message").textContent=text;$("message").dataset.error=String(error);}
async function api(path,method="GET",body){const response=await fetch(path,{method,headers:{...(localStorage.getItem(TOKEN)?{Authorization:`Bearer ${localStorage.getItem(TOKEN)}`}:{}) ,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||`Request failed (${response.status})`);return data;}
function showJob(next){if(!["book","arrivals","floor"].includes(next))return;job=next;$("jobs").querySelectorAll("[data-job]").forEach(b=>b.setAttribute("aria-current",b.dataset.job===job?"page":"false"));document.querySelectorAll("[data-panel]").forEach(p=>p.hidden=p.dataset.panel!==job);}
function finishEdit(){const form=$("bookingForm");form.elements.reservationId.value="";form.querySelector('button[type="submit"]').textContent="Save booking";$("cancelEdit").hidden=true;}
function showHold(reasons){state=null;chosen=null;$("holdPanel").hidden=false;$("workspace").hidden=true;$("holdReasons").innerHTML=reasons.map(x=>`<li>${esc(x)}</li>`).join("");}
function times(){const form=$("bookingForm"),selectedTime=form.elements.time.value,event=state?.events.find(e=>e.name===form.elements.holidayEvent.value);if(!event)return;form.elements.date.value=event.date;form.elements.partySize.max=state.maxPartySize;const [firstH,firstM]=event.firstSeating.split(":").map(Number),[lastH,lastM]=event.lastSeating.split(":").map(Number);let options="";for(let n=firstH*60+firstM;n<=lastH*60+lastM;n+=event.incrementMinutes){const time=`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`,remaining=event.maxCoversPerSlot-Number(state.slotUsage?.[`${event.date}T${time}`]||0);options+=`<option value="${time}" ${remaining<=0?"disabled":""}>${time} · ${Math.max(0,remaining)} covers left</option>`;}form.elements.time.innerHTML=options;if([...form.elements.time.options].some(o=>o.value===selectedTime&&!o.disabled))form.elements.time.value=selectedTime;}
function render(){if(!state)return;const form=$("bookingForm"),previous=form.elements.holidayEvent.value;form.elements.holidayEvent.innerHTML=state.events.map(e=>`<option value="${esc(e.name)}">${esc(e.name)}</option>`).join("");if(state.events.some(e=>e.name===previous))form.elements.holidayEvent.value=previous;times();
 const q=$("guestSearch").value.trim().toLowerCase(),digits=q.replace(/\D/g,"");const rows=state.reservations.filter(r=>!q||r.guestName.toLowerCase().includes(q)||(digits&&String(r.phone).replace(/\D/g,"").includes(digits))).sort((a,b)=>String(a.reservationTime).localeCompare(String(b.reservationTime)));
 $("bookingList").innerHTML=rows.length?rows.map(r=>`<article class="card"><div><strong>${esc(r.guestName)}</strong><small>${esc(r.holidayEvent)} · ${esc(r.reservationTime.slice(0,10))} · ${esc(r.reservationTime.slice(11,16))} · Party ${esc(r.partySize)}</small><small>${esc(r.phone)}${r.tableId?` · ${esc(r.tableId)}`:""}</small></div><span class="status">${esc(r.status)}</span><div class="actions">${r.status==="confirmed"?`<button type="button" data-action="arrive" data-id="${esc(r.id)}">Mark arrived</button><button type="button" class="secondary" data-action="edit" data-id="${esc(r.id)}">Edit</button><button type="button" class="secondary" data-action="cancel" data-id="${esc(r.id)}">Cancel</button>`:r.status==="arrived"?`<button type="button" data-action="choose" data-id="${esc(r.id)}">Choose table</button><button type="button" class="secondary" data-action="waitlist" data-id="${esc(r.id)}">Add to waitlist if needed</button><button type="button" class="secondary" data-action="edit" data-id="${esc(r.id)}">Edit</button><button type="button" class="secondary" data-action="cancel" data-id="${esc(r.id)}">Cancel</button>`:r.status==="seated"?`<button type="button" data-action="complete" data-id="${esc(r.id)}">Complete service</button>`:""}</div></article>`).join(""):'<p>No matching bookings.</p>';
 const rooms=[...new Set(state.tables.map(t=>t.section||"Dining room"))];if(!rooms.includes(room))room=rooms[0]||"";$("rooms").innerHTML=rooms.map(name=>`<button type="button" data-room="${esc(name)}" aria-pressed="${name===room}">${esc(name)}</button>`).join("");$("floorMap").innerHTML=state.tables.filter(t=>(t.section||"Dining room")===room).map(t=>`<button type="button" class="table" data-table="${esc(t.id)}" data-status="${esc(t.status)}" aria-label="Table ${esc(t.name)}, ${esc(t.status)}, ${esc(t.seats)} seats"><strong>${esc(t.name)}</strong><small>${esc(t.status)} · ${esc(t.seats)}</small></button>`).join("");$("seatPrompt").textContent=chosen?`Seat ${chosen.guestName}, party of ${chosen.partySize}. Tap an available table that fits.`:"Select an arrived party from Arrivals, or tap a cleaning table to mark it available.";
}
async function refresh(silent=false){try{const next=await api("/api/harbor-point-live");if(next.readiness!=="ACTIVE"){showHold(next.blocking||["Manager approval required"]);return;}$("holdPanel").hidden=true;$("workspace").hidden=false;state=next;if(chosen)chosen=state.reservations.find(r=>r.id===chosen.id&&r.status==="arrived")||null;render();if(!silent)message("Live workspace ready.");}catch(e){if(!silent)message(e.message,true);}}
async function mutate(path,body,success,method="POST"){if(busy)return false;busy=true;document.querySelectorAll('#workspace button[type="submit"]').forEach(b=>b.disabled=true);try{await api(path,method,body);chosen=null;await refresh(true);message(success);return true;}catch(e){message(e.message,true);await refresh(true);return false;}finally{busy=false;document.querySelectorAll('#workspace button[type="submit"]').forEach(b=>b.disabled=false);}}
async function session(){try{const me=await api("/api/auth/me");if(!me.permissions?.includes("write_reservations"))throw Error("Host access required.");$("operatorName").textContent=me.user.name;$("loginPanel").hidden=true;$("signOut").hidden=false;await refresh();clearInterval(timer);timer=setInterval(()=>{if(!busy&&document.visibilityState==="visible")refresh(true);},3500);}catch(e){$("loginPanel").hidden=false;$("workspace").hidden=true;$("holdPanel").hidden=true;$("signOut").hidden=true;clearInterval(timer);timer=null;$("loginPanel").querySelector("h2").textContent=e.message.includes("Authentication")?"Sign in to Blue Current":e.message;}}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{const login=await api("/api/auth/login","POST",{email:form.get("email"),password:form.get("password")});localStorage.setItem(TOKEN,login.token);await session();}catch(error){$("loginPanel").querySelector("h2").textContent=error.message;}});
$("signOut").addEventListener("click",async()=>{try{await api("/api/auth/logout","POST",{});}catch{}localStorage.removeItem(TOKEN);state=null;await session();});
$("jobs").addEventListener("click",e=>{const b=e.target.closest("[data-job]");if(b)showJob(b.dataset.job);});
$("bookingForm").elements.holidayEvent.addEventListener("change",times);
$("bookingForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,id=form.elements.reservationId.value;if(await mutate(id?`/api/harbor-point-live/reservations/${encodeURIComponent(id)}`:"/api/harbor-point-live/reservations",Object.fromEntries(new FormData(form)),id?"Booking updated.":"Booking saved.",id?"PUT":"POST")){finishEdit();form.elements.guestName.value="";form.elements.phone.value="";form.elements.notes.value="";form.elements.accessibility.value="";form.elements.specialOccasion.value="";}});
$("cancelEdit").addEventListener("click",()=>{$("bookingForm").reset();finishEdit();times();});
$("printBookings").addEventListener("click",()=>window.print());
$("guestSearch").addEventListener("input",render);
$("bookingList").addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const row=state?.reservations.find(r=>r.id===b.dataset.id);if(!row)return;if(b.dataset.action==="edit"){const f=$("bookingForm");f.elements.reservationId.value=row.id;f.elements.holidayEvent.value=row.holidayEvent;times();f.elements.time.value=row.reservationTime.slice(11,16);for(const key of ["guestName","phone","partySize","seatingPreference","specialOccasion","accessibility","notes"])f.elements[key].value=row[key]||"";f.querySelector('button[type="submit"]').textContent="Save changes";$("cancelEdit").hidden=false;showJob("book");message(`Editing ${row.guestName}.`);return;}if(b.dataset.action==="choose"){chosen=row;showJob("floor");render();message(`Choose a table for ${row.guestName}.`);return;}mutate("/api/harbor-point-live/actions",{reservationId:row.id,action:b.dataset.action},`${row.guestName}: ${b.dataset.action} saved.`);});
$("rooms").addEventListener("click",e=>{const b=e.target.closest("[data-room]");if(b){room=b.dataset.room;render();}});
$("floorMap").addEventListener("click",e=>{const b=e.target.closest("[data-table]");if(!b)return;const table=state?.tables.find(t=>t.id===b.dataset.table);if(!table)return;if(chosen){if(table.status!=="available"||Number(table.seats)<Number(chosen.partySize)){message("Choose an available table that fits this party.",true);return;}mutate("/api/harbor-point-live/actions",{reservationId:chosen.id,action:"seat",tableId:table.id},`${chosen.guestName} seated at ${table.name}.`);return;}if(table.status==="cleaning")mutate("/api/harbor-point-live/ready",{tableId:table.id},`${table.name} available again.`);else message("Select an arrived party first.");});
if(localStorage.getItem(TOKEN))session();
})();
