(()=>{"use strict";const b=document.querySelector(".menu-button"),n=document.getElementById("mobileNav");b?.addEventListener("click",()=>{const o=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",String(!o));if(n)n.hidden=o});n?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{n.hidden=true;b?.setAttribute("aria-expanded","false")}));document.querySelectorAll("#year").forEach(x=>x.textContent=new Date().getFullYear());const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>io.observe(x))})();
(() => {"use strict";function animate(n){const t=Number(n.dataset.counter||0),s=n.dataset.suffix||"",d=1100,a=performance.now();function f(x){const p=Math.min(1,(x-a)/d),e=1-Math.pow(1-p,3);n.textContent=Math.round(t*e)+s;if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!e.target.dataset.counted){e.target.dataset.counted="1";animate(e.target);o.unobserve(e.target)}}),{threshold:.35});document.querySelectorAll("[data-counter]").forEach(n=>o.observe(n));const day=document.getElementById("heroExperienceDay"),clock=document.getElementById("heroExperienceTime");function tick(){const n=new Date();if(day)day.textContent=new Intl.DateTimeFormat("en-US",{weekday:"long"}).format(n);if(clock)clock.textContent=new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(n)}tick();setInterval(tick,30000);const cards=[...document.querySelectorAll(".hero-attention-card")],msg=document.getElementById("heroBrainMessage"),btn=document.getElementById("heroNextRecommendation"),messages=["Recommending a host redeployment based on arrival pace and table readiness.","Recommending a twelve-minute reservation release hold to protect kitchen throughput.","Recommending a manager follow-up on seven high-value guest requests."];let i=0;function show(x){i=(x+cards.length)%cards.length;cards.forEach((c,j)=>c.classList.toggle("is-active",j===i));if(msg)msg.textContent=messages[i]}btn?.addEventListener("click",()=>show(i+1));cards.forEach((c,j)=>c.addEventListener("mouseenter",()=>show(j)));setInterval(()=>show(i+1),6500);const stream=document.getElementById("heroEventStream"),events=[["AI Concierge","Birthday preference attached to guest profile."],["Reservation Operations","Two-top inventory opened after an early turn."],["Kitchen Command","Station load balanced after menu-mix change."],["Executive Command","Service pressure returned to normal range."]];let k=0;setInterval(()=>{if(!stream)return;const [t,d]=events[k++%events.length],a=document.createElement("article");a.innerHTML="<i></i><div><strong></strong><span></span></div><time>Now</time>";a.querySelector("strong").textContent=t;a.querySelector("span").textContent=d;stream.prepend(a);while(stream.children.length>4)stream.lastElementChild.remove()},7200)})();

(() => {
"use strict";
const platformData=[
["Guest Experience","Every guest request enters one intelligent operating flow.","AI Concierge answers calls, captures intent, confirms reservations, and preserves guest preferences while keeping the host stand synchronized.",[["Answer","Every guest receives immediate acknowledgment."],["Understand","Intent and preferences are captured."],["Coordinate","The reservation view updates instantly."]],["Guest line","AI Concierge is handling an incoming reservation call.","Live"],[["Party","6 guests"],["Time","7:15 PM"],["Preference","Waterfront"],["Occasion","Birthday"]]],
["Restaurant Operations","The floor, kitchen, staff, and reservations share one service state.","Blue Current coordinates the moving parts of service so managers can act before local pressure becomes a guest-facing problem.",[["Observe","Track table readiness, arrivals, kitchen load, and staffing."],["Coordinate","Send the right action to the right owner."],["Recover","Verify whether the intervention improved service."]],["Live floor","Section pressure is increasing near the waterfront arrival window.","Watch"],[["Occupancy","78%"],["Tables turning","7"],["Kitchen load","74%"],["Coverage","94%"]]],
["Executive Intelligence","Leadership sees the moments that require attention—not another wall of data.","Blue Current converts operating signals into a ranked executive queue with urgency, owner, confidence, expected value, and evidence.",[["Prioritize","Separate immediate actions from items to watch."],["Assign","Attach a clear owner and checkpoint."],["Measure","Compare expected value with observed outcome."]],["Decision queue","Two operating moments require leadership attention.","2 active"],[["Urgency","Today"],["Owner","Regional Manager"],["Confidence","91%"],["Expected value","$1,100"]]],
["Governed Autonomy","Autonomous action expands only when evidence proves it is safe.","Guardrails, rollout controls, outcome verification, incident response, recovery, certification, and audit evidence keep automated operations accountable.",[["Constrain","Set confidence, value, urgency, and certification limits."],["Verify","Measure observed results against expectations."],["Govern","Pause, recover, certify, and audit every domain."]],["Autonomy guardrail","Kitchen pacing recommendation requires supervised approval.","Approval"],[["Mode","Supervised"],["Confidence floor","88%"],["Max value","$500"],["Certification","Conditional"]]]
];
const operationsData=[
["Reservation Pace","Protect the service before demand becomes pressure.","Blue Current compares arrivals, table readiness, kitchen throughput, staffing coverage, and current reservations before recommending whether to release, hold, or reshape demand.",[["Forecast","Compare reservations to the expected service curve."],["Detect","Identify arrival compression early."],["Act","Hold, release, or redirect demand."]],["Arrival curve","7:00–7:30 PM is approaching the safe service threshold.","Watch"],[["Reservations","86% of forecast"],["Floor readiness","78%"],["Kitchen capacity","74%"],["Staff coverage","94%"]],"Hold large-party reservation releases for twelve minutes.","The arrival curve and kitchen load are temporarily outpacing table readiness.","91% confidence",[32,48,63,82,94,88,67,42]],
["Live Floor","Keep seating decisions aligned with the real dining-room state.","Table status, section pressure, arrival timing, server load, and guest needs stay visible in one shared operating picture.",[["See","Track every active table and section."],["Balance","Distribute arrivals according to service capacity."],["Recover","Protect the guest experience when a section falls behind."]],["Section pressure","Waterfront demand is exceeding current host coverage.","Act now"],[["Occupancy","78%"],["Ready tables","4"],["Turns due","7"],["Host coverage","2 of 3"]],"Move one host to waterfront arrivals for twenty minutes.","Demand is concentrated in one seating zone.","94% confidence",[44,58,72,86,78,69,55,47]],
["Kitchen Command","Coordinate pacing before ticket pressure affects the dining room.","Blue Current connects menu mix, station load, ticket age, reservation pace, and table flow so kitchen leaders can rebalance early.",[["Monitor","See ticket pressure and station load."],["Rebalance","Shift work before expo becomes unstable."],["Communicate","Keep floor and reservations aligned."]],["Ticket pressure","Expo pressure is rising as large-party entrées enter the line.","High"],[["Avg ticket","14.2 min"],["Oldest ticket","21 min"],["Station load","88%"],["Expo pressure","High"]],"Rebalance one cook to sauté and hold releases for eight minutes.","Current station load may add six minutes to the next reservation wave.","89% confidence",[35,46,58,71,84,96,90,74]],
["Workforce","Deploy the team according to the live service state.","Coverage, clock-in status, role demand, section pressure, and kitchen load become one workforce coordination layer.",[["Confirm","See who is present and available."],["Deploy","Move coverage where it is needed."],["Verify","Measure whether the staffing move reduced pressure."]],["Coverage plan","Current staffing is sufficient, but the host stand needs temporary support.","Stable"],[["Clocked in","42"],["Coverage","94%"],["Open roles","1"],["Redeployments","2"]],"Move one service assistant to host support until 7:40 PM.","A short redeployment protects arrivals without increasing scheduled labor.","93% confidence",[60,68,76,89,94,91,80,66]]
];
function points(items){const root=document.getElementById("tourPoints");root.replaceChildren();items.forEach((item,i)=>{const a=document.createElement("article");a.innerHTML="<b></b><span><strong></strong><small></small></span>";a.querySelector("b").textContent=String(i+1).padStart(2,"0");a.querySelector("strong").textContent=item[0];a.querySelector("small").textContent=item[1];root.append(a);});}
function details(items){const root=document.getElementById("tourDetails");root.replaceChildren();items.forEach(item=>{const a=document.createElement("article");a.innerHTML="<span></span><b></b>";a.querySelector("span").textContent=item[0];a.querySelector("b").textContent=item[1];root.append(a);});}
const section=document.querySelector("[data-product-tour]");if(!section)return;const data=section.dataset.productTour==="platform"?platformData:operationsData;const tabs=[...document.querySelectorAll("[data-tour-tab]")];const orbit=[...document.querySelectorAll("[data-orbit-panel]")];let active=0;
function render(i){active=i;const d=data[i];tabs.forEach((t,x)=>t.classList.toggle("is-active",x===i));orbit.forEach((t,x)=>t.classList.toggle("is-active",x===i));document.getElementById("tourKicker").textContent=d[0];document.getElementById("tourTitle").textContent=d[1];document.getElementById("tourDescription").textContent=d[2];points(d[3]);document.getElementById("tourPanelEyebrow").textContent=d[4][0];document.getElementById("tourPanelTitle").textContent=d[4][1];document.getElementById("tourPanelStatus").textContent=d[4][2];document.getElementById("tourScreenLabel").textContent=d[0];details(d[5]);if(section.dataset.productTour==="operations"){document.getElementById("tourRecommendation").textContent=d[6];document.getElementById("tourReason").textContent=d[7];document.getElementById("tourConfidence").textContent=d[8];document.querySelectorAll("#arrivalChart span").forEach((b,x)=>b.style.setProperty("--height",`${d[9][x]}%`));}}
tabs.forEach((t,i)=>t.addEventListener("click",()=>render(i)));orbit.forEach((t,i)=>t.addEventListener("click",()=>{render(i);section.scrollIntoView({behavior:"smooth"});}));setInterval(()=>render((active+1)%data.length),11000);
})();
