"use strict";
const fs=require("fs"),path=require("path");
const root=process.cwd(),kit=__dirname;
const jsDst=path.join(root,"client","js","floor-reservations-v62.0.js");
const cssDst=path.join(root,"client","styles.css");
if(!fs.existsSync(jsDst)||!fs.existsSync(cssDst)) throw new Error("V100.2.53 requires the current Blue Current repo with Host Stand files present.");
const currentJs=fs.readFileSync(jsDst,"utf8");
if(!currentJs.includes("V100.2.52 — Service Milestones")) throw new Error("V100.2.53 requires V100.2.52 first so Service milestones are preserved.");
const srcJs=path.join(kit,"patches","client","js","floor-reservations-v62.0.js");
const srcCss=path.join(kit,"patches","client","styles.css");
if(!fs.existsSync(srcJs)||!fs.existsSync(srcCss)) throw new Error("V100.2.53 patch payload is incomplete.");
fs.copyFileSync(jsDst,jsDst+".v100.2.53.bak");
fs.copyFileSync(cssDst,cssDst+".v100.2.53.bak");
fs.copyFileSync(srcJs,jsDst);
fs.copyFileSync(srcCss,cssDst);
const testSrc=path.join(kit,"scripts","maintenance","test-v100.2.53-floor-regression-repair.js");
const testDst=path.join(root,"scripts","maintenance","test-v100.2.53-floor-regression-repair.js");
fs.mkdirSync(path.dirname(testDst),{recursive:true});fs.copyFileSync(testSrc,testDst);
console.log(JSON.stringify({ok:true,version:"100.2.53",repair:"Floor Regression Repair",preserved:["V100.2.49 seated handoff","V100.2.50 service intake","V100.2.51 active tables","V100.2.52 service milestones","V100.2.48 floor readability"],restored:["room isolation","organic table geometry","fixture visibility by active zone","floor recommendation counts"]},null,2));
