"use strict";
const fs=require("fs"),path=require("path");
const root=process.cwd();
const file=path.join(root,"client","js","floor-reservations-v62.0.js");
if(!fs.existsSync(file)) throw new Error("V100.2.54 requires client/js/floor-reservations-v62.0.js");
let s=fs.readFileSync(file,"utf8");
if(!s.includes("V100.2.52 — Service Milestones")) throw new Error("V100.2.54 requires the V100.2.52+ Service milestone baseline.");
if(!s.includes("bc-floor-zone-isolation-v100-2-47")) throw new Error("V100.2.54 requires the V100.2.53 repaired floor baseline. Refusing to modify an unverified floor controller.");
if(s.includes("V100.2.54 — Service Priority & Pacing")){console.log(JSON.stringify({ok:true,version:"100.2.54",status:"already-applied"},null,2));process.exit(0);}
const oldFn=' function serviceNeedsAttention(p){return (p?.status||"seated")==="seated"&&Math.max(0,Date.now()-Number(p?.seatedAt||Date.now()))>=3*60000;}';
const newFn=` // V100.2.54 — Service Priority & Pacing. Surgical service-only change; floor renderer untouched.\n const SERVICE_PACE_MINUTES={seated:3,greeted:7,ordering:15,dining:45,check:10};\n function serviceStageAgeMs(p){const status=p?.status||"seated";const anchor=status==="seated"?Number(p?.seatedAt||Date.now()):Number(p?.updatedAt||p?.seatedAt||Date.now());return Math.max(0,Date.now()-anchor);}\n function serviceNeedsAttention(p){const status=p?.status||"seated",limit=SERVICE_PACE_MINUTES[status];return Number.isFinite(limit)&&serviceStageAgeMs(p)>=limit*60000;}\n function serviceAttentionLabel(p){if(!serviceNeedsAttention(p))return "";const status=p?.status||"seated";return status==="seated"?"Needs greeting":"Needs attention";}\n function servicePriorityScore(p){if(!serviceNeedsAttention(p))return 0;const status=p?.status||"seated",limit=(SERVICE_PACE_MINUTES[status]||999)*60000;return 1000+Math.floor(serviceStageAgeMs(p)/Math.max(1,limit));}`;
if(!s.includes(oldFn)) throw new Error("V100.2.54 guard failed: expected Service attention function not found. No files changed.");
s=s.replace(oldFn,newFn);
const oldRows='   const rows=readServiceParties().filter(p=>p&&p.status!=="cleared");';
const newRows='   const rows=readServiceParties().filter(p=>p&&p.status!=="cleared").sort((a,b)=>servicePriorityScore(b)-servicePriorityScore(a)||Number(a.seatedAt||0)-Number(b.seatedAt||0));';
if(!s.includes(oldRows)) throw new Error("V100.2.54 guard failed: Service row source changed. No files changed.");
s=s.replace(oldRows,newRows);
const oldSummary='   summary.innerHTML=`<div><span>Active tables</span><strong>${rows.length}</strong></div><div><span>Active covers</span><strong>${covers}</strong></div><div><span>Needs greeting</span><strong>${needs}</strong></div>`;';
const newSummary='   summary.innerHTML=`<div><span>Active tables</span><strong>${rows.length}</strong></div><div><span>Active covers</span><strong>${covers}</strong></div><div><span>Needs attention</span><strong>${needs}</strong></div>`;';
if(!s.includes(oldSummary)) throw new Error("V100.2.54 guard failed: Service summary changed. No files changed.");
s=s.replace(oldSummary,newSummary);
const oldMap='list.innerHTML=rows.length?rows.map((p,i)=>{const stage=serviceStage(p),attention=serviceNeedsAttention(p);return `<article class="bc-service-party-v251" data-service-row="${i}" data-needs-attention="${attention}"><div><strong>${escapeHtml(p.guest||"Guest")}</strong><small>${escapeHtml(p.guestDetail||`Party of ${p.partySize||"—"}`)}</small></div><div class="meta"><span>Table</span><b>${escapeHtml(serviceTableLabel(p))}</b></div><div class="meta"><span>Service</span><b class="bc-service-stage-v252">${escapeHtml(stage.label)}</b><small>Seated ${escapeHtml(serviceElapsed(p.seatedAt))}</small></div><button type="button" data-service-action="advance" data-final="${stage.next==="complete"}">${escapeHtml(stage.action)}</button></article>`;}).join("")';
const newMap='list.innerHTML=rows.length?rows.map((p,i)=>{const stage=serviceStage(p),attention=serviceNeedsAttention(p),attentionLabel=serviceAttentionLabel(p);return `<article class="bc-service-party-v251" data-service-row="${i}" data-needs-attention="${attention}"><div><strong>${escapeHtml(p.guest||"Guest")}</strong><small>${escapeHtml(p.guestDetail||`Party of ${p.partySize||"—"}`)}</small>${attentionLabel?`<small><b>${escapeHtml(attentionLabel)}</b></small>`:""}</div><div class="meta"><span>Table</span><b>${escapeHtml(serviceTableLabel(p))}</b></div><div class="meta"><span>Service</span><b class="bc-service-stage-v252">${escapeHtml(stage.label)}</b><small>Seated ${escapeHtml(serviceElapsed(p.seatedAt))}</small></div><button type="button" data-service-action="advance" data-final="${stage.next==="complete"}">${escapeHtml(stage.action)}</button></article>`;}).join("")';
if(!s.includes(oldMap)) throw new Error("V100.2.54 guard failed: Service row renderer changed. No files changed.");
s=s.replace(oldMap,newMap);
fs.copyFileSync(file,file+".v100.2.54.bak");
fs.writeFileSync(file,s);
const testSrc=path.join(__dirname,"scripts","maintenance","test-v100.2.54-service-priority-pacing.js"),testDst=path.join(root,"scripts","maintenance","test-v100.2.54-service-priority-pacing.js");
fs.mkdirSync(path.dirname(testDst),{recursive:true});fs.copyFileSync(testSrc,testDst);
console.log(JSON.stringify({ok:true,version:"100.2.54",wave:"Service Priority & Pacing",architecture:"guarded in-place service-only patch",floorRenderer:"untouched"},null,2));
