(function () {
  "use strict";
  const money = value => new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:0 }).format(Number(value)||0);
  const safe = value => String(value ?? "").toLowerCase();
  window.createBlueCurrentLiveModule = function (eventBus, appState) {
    const root=document.getElementById("blue-current-live"); if(!root) return null;
    const el=id=>document.getElementById(id);
    const nodes={health:el("liveHealthScore"),guests:el("liveGuestsDining"),tables:el("liveTablesActive"),calls:el("liveCallsToday"),revenue:el("liveRevenue"),forecast:el("liveRevenueForecast"),pressure:el("liveTablePressure"),answer:el("copilotAnswer"),form:el("copilotForm"),input:el("copilotInput"),stream:el("liveEventStream"),search:el("liveTimelineSearch"),pulse:el("connectorPulse"),run:el("liveRunSequence"),action:el("liveNextAction"),detail:el("liveNextActionDetail")};
    let events=[]; let pulseTimer=null;
    function snapshot(){const s=appState?.getState?.()||{}; const activeTables=Array.isArray(s.tables)?s.tables.filter(t=>t.status&&t.status!=="available").length:Math.max(0,Math.round((Number(s.occupancyPercent)||78)*.35)); return {...s,activeTables,guestsDining:Math.max(0,Math.round((Number(s.occupancyPercent)||78)*1.08)),health:Math.max(62,Math.min(99,Math.round(100-Math.max(0,(Number(s.occupancyPercent)||78)-88)*1.4-Math.max(0,(Number(s.projectedKitchenMinutes)||11)-14)*2)))};}
    function render(){const s=snapshot();nodes.health.textContent=s.health;nodes.guests.textContent=s.guestsDining;nodes.tables.textContent=s.activeTables;nodes.calls.textContent=Number(s.callsAnswered||53).toLocaleString();nodes.revenue.textContent=money(s.estimatedRevenue||12884);nodes.forecast.textContent=`Forecast ${money(s.revenueForecast||18720)}`;nodes.pressure.textContent=s.occupancyPercent>=94?"Capacity pressure":s.occupancyPercent>=86?"Demand building":"Balanced floor"; if(s.occupancyPercent>=94){nodes.action.textContent="Protect the next seating wave";nodes.detail.textContent="Pause walk-ins briefly and rebalance tables before kitchen load peaks.";} else if(s.activeGuest?.vip||s.activeGuest?.celebration){nodes.action.textContent="Prepare the VIP arrival";nodes.detail.textContent="Notify the host and verify guest preferences before seating.";} else {nodes.action.textContent="Prepare Table 14 for VIP arrival";nodes.detail.textContent="Birthday preferences are loaded. Notify the host and verify the dessert note.";}}
    function addEvent(name,payload={}){const time=new Date();events.unshift({name,time:time.toLocaleTimeString([], {hour:"numeric",minute:"2-digit",second:"2-digit"}),detail:payload?.reservation?.guestName||payload?.location?.name||payload?.table?.label||payload?.scenario?.label||payload?.title||"System synchronized"});events=events.slice(0,60);renderEvents();}
    function renderEvents(){const q=safe(nodes.search?.value);const list=events.filter(x=>!q||safe(x.name+" "+x.detail).includes(q));nodes.stream.innerHTML=list.length?list.map(x=>`<div class="live-event"><time>${x.time}</time><div><strong>${x.name.replaceAll(":"," · ")}</strong><small>${x.detail}</small></div></div>`).join(""):'<p class="live-event-empty">No matching live events.</p>'; }
    function answer(query){const s=snapshot(),q=safe(query);let title="Operational answer",text=s.executiveBrief||"Service is operating normally.";if(q.includes("vip")){title="VIP arrivals";text=s.activeGuest?`${s.activeGuest.name||"Anthony Russo"} is the active premier guest. Table ${s.activeTable?.number||14} is being prepared.`:"One premier guest is expected during the next arrival window.";}else if(q.includes("birthday")){title="Celebrations";text="Two birthday celebrations are on tonight's service plan. Table 14 has a dessert note attached.";}else if(q.includes("slow")||q.includes("kitchen")){title="Service pressure";text=`Kitchen is projected at ${s.projectedKitchenMinutes||15} minutes. ${s.occupancyPercent>=92?"Seating compression is the primary risk.":"No material bottleneck is currently developing."}`;}else if(q.includes("revenue")||q.includes("close")){title="Closing revenue forecast";text=`Current pace is ${money(s.estimatedRevenue||12884)} with a projected close of ${money(s.revenueForecast||18720)}.`;}else if(q.includes("table")){title="Floor status";text=`${s.activeTables} tables are active. Occupancy is ${s.occupancyPercent||78}% and the floor is ${s.occupancyPercent>=92?"under pressure":"balanced"}.`;}nodes.answer.innerHTML=`<small>${title}</small><p>${text}</p>`;eventBus?.emit?.("copilot:answered",{query,title});}
    document.querySelectorAll("[data-copilot-query]").forEach(b=>b.addEventListener("click",()=>answer(b.dataset.copilotQuery)));nodes.form?.addEventListener("submit",e=>{e.preventDefault();if(nodes.input.value.trim()){answer(nodes.input.value.trim());nodes.input.value="";}});nodes.search?.addEventListener("input",renderEvents);document.querySelectorAll("[data-live-focus]").forEach(b=>b.addEventListener("click",()=>answer(b.dataset.liveFocus)));
    nodes.pulse?.addEventListener("click",()=>{document.querySelectorAll("[data-connector]").forEach((item,i)=>setTimeout(()=>{item.classList.add("pulsing");setTimeout(()=>item.classList.remove("pulsing"),760);eventBus?.emit?.("connector:heartbeat",{connector:item.dataset.connector,status:"healthy"});},i*240));});
    nodes.run?.addEventListener("click",()=>{clearInterval(pulseTimer);const sequence=[()=>eventBus.emit("concierge:call-started",{title:"Incoming reservation call"}),()=>eventBus.emit("guest:recognized",{title:"Anthony Russo recognized"}),()=>eventBus.emit("reservation:confirmed",{reservation:{id:"live-14",guestName:"Anthony Russo",partySize:4,tableNumber:14,celebration:"Birthday"},occupancyPercent:91,revenueImpact:420}),()=>eventBus.emit("guest:arrived",{title:"VIP guest arrived"}),()=>eventBus.emit("table:status-changed",{table:{number:14,label:"Table 14",status:"seated"}}),()=>eventBus.emit("predictive:forecast-updated",{scenario:{label:"Demand building"}})];let i=0;nodes.run.disabled=true;nodes.run.textContent="Running live pulse…";sequence[i++]();pulseTimer=setInterval(()=>{if(i>=sequence.length){clearInterval(pulseTimer);nodes.run.disabled=false;nodes.run.textContent="Run live service pulse";eventBus.emit("live:pulse-complete",{steps:sequence.length});return;}sequence[i++]();},850);});
    const originalEmit=eventBus.emit.bind(eventBus); if(!eventBus.__liveWrapped){eventBus.emit=function(name,payload){const result=originalEmit(name,payload);try{addEvent(name,payload);}catch{}return result;};eventBus.__liveWrapped=true;}
    eventBus.on?.("state:updated",render); render(); addEvent("live:ready",{title:"Command center connected"}); return {render,answer,getEvents:()=>events.slice()};
  };
})();
