"use strict";
class AutonomousOperationsService {
  constructor(database,auditService,realtimeHub,executiveCommandCenterService){Object.assign(this,{database,auditService,realtimeHub,executiveCommandCenterService});}
  clamp(v,min,max){return Math.max(min,Math.min(max,Math.round(v)));}
  now(){return new Date().toISOString();}
  async policy(org){const db=await this.database.read();return (db.autonomousPolicies||[]).find(x=>x.organizationId===org)||{enabled:false,mode:"manual",autoExecuteRiskLevels:[],approvalRequiredRiskLevels:["low","medium","high"],maxActionsPerCycle:0,forecastHorizonMinutes:120};}
  forecastLocation(x){
    const demandFactor=1+(x.occupancy-65)/250+(x.waitlist||0)/120;
    const revenueNextHour=Math.max(0,Math.round(x.revenue*.085*demandFactor));
    const closeRevenue=Math.round(x.revenue+revenueNextHour*4.2);
    const waitlistPeak=Math.max(x.waitlist||0,Math.round((x.waitlist||0)+(x.occupancy>80?5:1)+(x.averageTicketMinutes>18?3:0)));
    const ticketPeak=this.clamp(x.averageTicketMinutes+(x.occupancy>80?4:1)+(x.readyTickets>2?2:0),8,40);
    const staffingNeed=Math.max(0,Math.ceil((x.occupancy-76)/12)+(ticketPeak>21?1:0));
    return {locationId:x.locationId,name:x.name,revenueNextHour,projectedCloseRevenue:closeRevenue,projectedWaitlistPeak:waitlistPeak,projectedTicketPeak:ticketPeak,additionalStaffNeeded:staffingNeed,confidence:this.clamp(90-Math.abs(x.revenueTrend)*.5,68,96)};
  }
  buildActions(snapshot,forecasts){const actions=[];for(const x of snapshot.locations){const f=forecasts.find(y=>y.locationId===x.locationId);if(f.projectedTicketPeak>=23)actions.push({key:`${x.locationId}_pace`,locationId:x.locationId,locationName:x.name,type:'reservation_pacing',title:'Reduce seating velocity',description:`Apply a 4-minute seating buffer before ticket time reaches ${f.projectedTicketPeak} minutes.`,risk:'low',expectedImpact:'Reduce peak ticket time 8–14%',command:{bufferMinutes:4}});if(f.additionalStaffNeeded>0)actions.push({key:`${x.locationId}_staff`,locationId:x.locationId,locationName:x.name,type:'staffing',title:'Activate staffing contingency',description:`Request ${f.additionalStaffNeeded} additional team member${f.additionalStaffNeeded===1?'':'s'} for the projected demand window.`,risk:'medium',expectedImpact:'Protect service capacity',command:{additionalStaff:f.additionalStaffNeeded}});if(x.readyTickets>=3)actions.push({key:`${x.locationId}_runner`,locationId:x.locationId,locationName:x.name,type:'expo',title:'Assign temporary food runner',description:`Expo has ${x.readyTickets} ready tickets. Assign the least-loaded eligible server for 10 minutes.`,risk:'low',expectedImpact:'Reduce food pickup delay 20–35%',command:{durationMinutes:10}});if(x.revenueTrend<=-5&&x.occupancy<65)actions.push({key:`${x.locationId}_demand`,locationId:x.locationId,locationName:x.name,type:'demand',title:'Launch manager-approved demand offer',description:'Prepare a targeted same-day offer for opted-in guests; approval is required before sending.',risk:'high',expectedImpact:'Increase near-term covers',command:{discountPercent:10}});}return actions.slice(0,12);}
  profit(location){const revenue=location.revenue,labor=Math.round(revenue*(.26+(location.activeStaff>18?.025:0))),food=Math.round(revenue*(.29+(location.averageTicketMinutes>20?.018:0))),waste=Math.round(revenue*(.018+(location.readyTickets>2?.009:0))),operating=Math.max(0,revenue-labor-food-waste-Math.round(revenue*.17));return{locationId:location.locationId,name:location.name,revenue,labor,laborPercent:Math.round(labor/revenue*1000)/10,food,foodPercent:Math.round(food/revenue*1000)/10,waste,operatingProfit:operating,margin:Math.round(operating/revenue*1000)/10,revenuePerLaborHour:Math.round(revenue/Math.max(1,location.activeStaff*7.5)),revenuePerSeat:Math.round(revenue/Math.max(1,location.totalTables*4))};}
  timeline(existing,actions){const generated=actions.slice(0,6).map((a,i)=>({id:`evt_${a.key}`,time:new Date(Date.now()-i*7*60000).toISOString(),locationId:a.locationId,locationName:a.locationName,category:a.type,title:a.title,detail:a.description,status:'recommended'}));return [...generated,...existing].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,30);}
  async snapshot(org){const executive=await this.executiveCommandCenterService.snapshot(org),policy=await this.policy(org),db=await this.database.read(),forecasts=executive.locations.map(x=>this.forecastLocation(x)),suggested=this.buildActions(executive,forecasts),stored=(db.autonomousActions||[]).filter(x=>x.organizationId===org).slice(-30).reverse(),byKey=new Map(stored.map(x=>[x.key,x]));const actions=suggested.map(x=>({...x,id:byKey.get(x.key)?.id||`auto_${x.key}`,status:byKey.get(x.key)?.status||'recommended',createdAt:byKey.get(x.key)?.createdAt||this.now(),executedAt:byKey.get(x.key)?.executedAt||null}));const profits=executive.locations.map(x=>this.profit(x)),portfolioProfit={revenue:profits.reduce((s,x)=>s+x.revenue,0),operatingProfit:profits.reduce((s,x)=>s+x.operatingProfit,0),laborPercent:Math.round(profits.reduce((s,x)=>s+x.labor,0)/Math.max(1,profits.reduce((s,x)=>s+x.revenue,0))*1000)/10,foodPercent:Math.round(profits.reduce((s,x)=>s+x.food,0)/Math.max(1,profits.reduce((s,x)=>s+x.revenue,0))*1000)/10,margin:Math.round(profits.reduce((s,x)=>s+x.operatingProfit,0)/Math.max(1,profits.reduce((s,x)=>s+x.revenue,0))*1000)/10};return{generatedAt:this.now(),policy,portfolio:executive.portfolio,locations:executive.locations,forecasts,actions,profits,portfolioProfit,timeline:this.timeline((db.operationsTimeline||[]).filter(x=>x.organizationId===org),actions)};}
  async runCycle(org,actor){const snap=await this.snapshot(org),policy=snap.policy;let executed=0;const records=[];for(const action of snap.actions){let status='recommended';if(policy.enabled&&policy.autoExecuteRiskLevels.includes(action.risk)&&executed<policy.maxActionsPerCycle){status='executed';executed++;}const record={...action,id:`auto_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,organizationId:org,status,createdAt:this.now(),executedAt:status==='executed'?this.now():null,actor:status==='executed'?'Autonomous Operations Director':actor};records.push(record);}await this.database.mutate(db=>{db.autonomousActions||=[];db.operationsTimeline||=[];db.autonomousActions.push(...records);for(const r of records)db.operationsTimeline.push({id:`evt_${r.id}`,organizationId:org,time:this.now(),locationId:r.locationId,locationName:r.locationName,category:r.type,title:r.title,detail:r.status==='executed'?`Executed automatically: ${r.description}`:`Approval queued: ${r.description}`,status:r.status});return records;});await this.auditService.record({organizationId:org,actor,action:`Autonomous operations cycle completed: ${executed} actions executed`,category:'autonomous_operations'});this.realtimeHub.publish('autonomous:cycle-completed',{organizationId:org,executed,total:records.length});return this.snapshot(org);}
  async decide(id,input,actor,org){const status=['approved','rejected','executed'].includes(input.status)?input.status:'rejected';const updated=await this.database.mutate(db=>{const item=(db.autonomousActions||[]).find(x=>x.id===id);if(!item)return null;item.status=status;item.decidedAt=this.now();item.executedAt=status==='executed'?this.now():item.executedAt;item.decisionNote=String(input.note||'');db.operationsTimeline||=[];db.operationsTimeline.push({id:`evt_${Date.now()}`,organizationId:org,time:this.now(),locationId:item.locationId,locationName:item.locationName,category:item.type,title:`Action ${status}: ${item.title}`,detail:item.decisionNote||item.description,status});return item;});if(!updated)return null;await this.auditService.record({organizationId:org,actor,action:`Autonomous action ${status}: ${updated.title}`,category:'autonomous_operations'});this.realtimeHub.publish('autonomous:action-decided',updated);return updated;}
  async updatePolicy(input,actor,org){const updated=await this.database.mutate(db=>{db.autonomousPolicies||=[];let p=db.autonomousPolicies.find(x=>x.organizationId===org);if(!p){p={id:`auto_policy_${org}`,organizationId:org};db.autonomousPolicies.push(p);}Object.assign(p,{enabled:Boolean(input.enabled),mode:['manual','guarded','autonomous'].includes(input.mode)?input.mode:'guarded',autoExecuteRiskLevels:Array.isArray(input.autoExecuteRiskLevels)?input.autoExecuteRiskLevels:['low'],maxActionsPerCycle:this.clamp(Number(input.maxActionsPerCycle||3),0,10),forecastHorizonMinutes:this.clamp(Number(input.forecastHorizonMinutes||120),30,360),updatedAt:this.now()});return p;});await this.auditService.record({organizationId:org,actor,action:`Autonomous policy updated: ${updated.mode}`,category:'autonomous_operations'});this.realtimeHub.publish('autonomous:policy-updated',updated);return updated;}
  async ask(question,org){const snap=await this.snapshot(org),q=String(question||'').toLowerCase(),risk=[...snap.locations].sort((a,b)=>(a.health-b.health)||(b.averageTicketMinutes-a.averageTicketMinutes))[0],top=[...snap.locations].sort((a,b)=>b.revenue-a.revenue)[0];let answer;if(q.includes('revenue')||q.includes('forecast'))answer=`Projected portfolio close is $${snap.forecasts.reduce((s,x)=>s+x.projectedCloseRevenue,0).toLocaleString()}. ${top.name} currently leads at $${top.revenue.toLocaleString()}.`;else if(q.includes('help')||q.includes('risk')||q.includes('behind'))answer=`${risk.name} needs the most attention. Health is ${risk.health}, average tickets are ${risk.averageTicketMinutes} minutes, and operating risk is ${risk.risk}.`;else if(q.includes('cook')||q.includes('staff')){const need=snap.forecasts.filter(x=>x.additionalStaffNeeded>0);answer=need.length?`${need.map(x=>`${x.name}: ${x.additionalStaffNeeded} additional`).join('; ')} team member coverage is forecast.`:'No location currently crosses the additional-staff threshold.';}else if(q.includes('profit')||q.includes('margin'))answer=`Modeled operating profit is $${snap.portfolioProfit.operatingProfit.toLocaleString()} at a ${snap.portfolioProfit.margin}% margin. Labor is ${snap.portfolioProfit.laborPercent}% and food cost is ${snap.portfolioProfit.foodPercent}%.`;else answer=`Portfolio health is ${snap.portfolio.health}. There are ${snap.actions.length} active operating actions; ${snap.actions.filter(x=>x.risk==='low').length} are low risk and eligible for guarded automation.`;return{question,answer,generatedAt:this.now(),evidence:{portfolioHealth:snap.portfolio.health,actions:snap.actions.length,atRiskLocations:snap.portfolio.atRiskLocations}};}
}
module.exports=AutonomousOperationsService;
