(function(){
  "use strict";
  const params=new URLSearchParams(location.search),setup=params.get("demoSetup")==="1",active=params.get("demonstration")==="1";
  if(!setup&&!active)return;
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const restaurant={
    name:"Harbor & Hearth Tavern",
    status:"FICTIONAL DEMONSTRATION RESTAURANT",
    concept:"High-volume coastal-casual tavern",
    service:"Lunch, dinner, late night",
    areas:["Main Dining · 12 tables","Harbor Bar · 6 tables","Covered Patio · 8 tables","Private Loft · 5 tables"],
    controls:["No live restaurant data","No POS write-back","No pilot certification","Seeded development environment only"]
  };
  const steps=[
    {name:"Tonight at a glance",job:"Show one operating picture before service.",hash:"#host-stand",cta:"Open host stand"},
    {name:"Capture demand",job:"Show a reservation and the next obvious host action.",hash:"#reservations",cta:"Open reservations"},
    {name:"Manage the door",job:"Show arrivals, walk-ins, and clear wait expectations.",hash:"#host-stand",cta:"Open host stand"},
    {name:"Run the floor",job:"Show table truth and zone-level service awareness.",hash:"#floor",cta:"Open floor"},
    {name:"Coordinate service",job:"Show the manager where intervention is actually needed.",hash:"#service",cta:"Open service"},
    {name:"Protect throughput",job:"Show kitchen pressure without inventing decisions.",hash:"#kitchen",cta:"Open kitchen"},
    {name:"Close with value",job:"Show labor, profit, and accountable manager action.",hash:"#command",cta:"Open command"}
  ];
  const style=document.createElement("style");style.textContent=`
    .bc-demo-setup{position:fixed;inset:0;z-index:2147483647;overflow:auto;background:#061f29;color:#f5fbfc;padding:calc(20px + env(safe-area-inset-top)) 18px calc(28px + env(safe-area-inset-bottom));font:600 17px/1.45 system-ui,-apple-system,sans-serif}.bc-demo-setup *{box-sizing:border-box}.bc-demo-shell{max-width:900px;margin:auto}.bc-demo-head{display:flex;justify-content:space-between;gap:16px;align-items:start}.bc-demo-head h1{font-size:clamp(30px,6vw,52px);line-height:1.05;margin:8px 0}.bc-demo-kicker,.bc-demo-safety{color:#6ee7d1;letter-spacing:.08em}.bc-demo-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:22px 0}.bc-demo-card{background:#0b2b35;border:1px solid #31515a;border-radius:18px;padding:18px}.bc-demo-card h2{margin-top:0}.bc-demo-card ul{padding-left:22px}.bc-demo-actions{display:flex;gap:10px;flex-wrap:wrap}.bc-demo-actions button,.bc-demo-guide button{min-height:50px;border:1px solid #52727c;border-radius:12px;padding:11px 18px;background:#087e65;color:white;font:800 17px system-ui}.bc-demo-actions .secondary{background:#173c47}.bc-demo-banner{position:fixed;left:0;right:0;top:0;z-index:2147483644;background:#7a4810;color:#fff8e8;padding:8px 68px 8px 12px;text-align:center;font:800 13px/1.25 system-ui;letter-spacing:.04em}.bc-demo-guide{position:fixed;z-index:2147483645;left:12px;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));max-width:920px;margin:auto;background:#071f29f2;color:#f5fbfc;border:1px solid #4e7780;border-radius:17px;padding:14px;box-shadow:0 12px 40px #0009;font:600 15px/1.35 system-ui}.bc-demo-guide header{display:flex;justify-content:space-between;gap:12px}.bc-demo-guide h2{font-size:20px;margin:3px 0}.bc-demo-guide p{margin:5px 0 12px;color:#c9dade}.bc-demo-guide nav{display:flex;gap:8px}.bc-demo-guide nav button{flex:1;min-height:44px;font-size:14px}.bc-demo-guide nav button:first-child{background:#173c47}.bc-demo-close{position:absolute;right:10px;top:9px;min-height:34px!important;padding:3px 10px!important;background:#173c47!important}.bc-demo-return{position:fixed;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));z-index:2147483645;border:0;border-radius:999px;padding:12px 16px;background:#087e65;color:#fff;font:800 15px system-ui}@media(max-width:680px){.bc-demo-grid{grid-template-columns:1fr}.bc-demo-setup{padding-left:12px;padding-right:12px}.bc-demo-guide{left:8px;right:8px}.bc-demo-head{display:block}}
  `;document.head.appendChild(style);
  function exit(){const url=new URL(location.href);url.searchParams.delete("demoSetup");url.searchParams.delete("demonstration");location.href=url.toString();}
  if(setup){
    const root=document.createElement("main");root.className="bc-demo-setup";root.setAttribute("aria-label","Fictional demonstration setup");root.innerHTML=`<div class="bc-demo-shell"><div class="bc-demo-head"><div><small class="bc-demo-kicker">V100.3.51 · CONTROLLED DEMONSTRATION</small><h1>${esc(restaurant.name)}</h1><p>${esc(restaurant.status)} · ${esc(restaurant.concept)}</p></div><div class="bc-demo-actions"><button class="secondary" id="bcDemoExit">Exit</button></div></div><p>This presentation uses a clearly fictional restaurant and the existing seeded development environment. It does not confirm Anchor Tavern data or create pilot evidence.</p><div class="bc-demo-grid"><section class="bc-demo-card"><h2>Operating shape</h2><p>${esc(restaurant.service)}</p><ul>${restaurant.areas.map(item=>`<li>${esc(item)}</li>`).join("")}</ul></section><section class="bc-demo-card"><h2>Safety boundary</h2><ul>${restaurant.controls.map(item=>`<li>${esc(item)}</li>`).join("")}</ul></section></div><section class="bc-demo-card"><h2>Seven-part story</h2><ol>${steps.map(step=>`<li><strong>${esc(step.name)}</strong> — ${esc(step.job)}</li>`).join("")}</ol></section><div class="bc-demo-actions"><button id="bcDemoStart">Start guided demonstration</button></div></div>`;document.body.appendChild(root);
    root.addEventListener("click",event=>{if(event.target.id==="bcDemoExit")exit();if(event.target.id==="bcDemoStart"){const url=new URL(location.href);url.searchParams.delete("demoSetup");url.searchParams.set("demonstration","1");url.hash="host-stand";location.href=url.toString();}});return;
  }
  const banner=document.createElement("div");banner.className="bc-demo-banner";banner.textContent=`DEMO ONLY · ${restaurant.name} · FICTIONAL DATA · NO LIVE SYSTEM WRITE-BACK`;document.body.appendChild(banner);
  let index=0,hidden=false;const guide=document.createElement("aside");guide.className="bc-demo-guide";guide.setAttribute("aria-label","Demonstration guide");document.body.appendChild(guide);const returnButton=document.createElement("button");returnButton.className="bc-demo-return";returnButton.textContent="Show demo guide";returnButton.hidden=true;document.body.appendChild(returnButton);
  function draw(){const step=steps[index];guide.innerHTML=`<button class="bc-demo-close" data-action="hide" aria-label="Hide guide">×</button><header><small>DEMO STEP ${index+1} OF ${steps.length}</small><small>FICTIONAL RESTAURANT</small></header><h2>${esc(step.name)}</h2><p>${esc(step.job)}</p><nav><button data-action="previous" ${index===0?"disabled":""}>Previous</button><button data-action="open">${esc(step.cta)}</button><button data-action="next">${index===steps.length-1?"Finish":"Next"}</button></nav>`;}
  guide.addEventListener("click",event=>{const action=event.target.dataset.action;if(action==="hide"){guide.hidden=true;returnButton.hidden=false;hidden=true;}if(action==="previous"&&index>0){index-=1;draw();}if(action==="open")location.hash=steps[index].hash;if(action==="next"){if(index<steps.length-1){index+=1;draw();location.hash=steps[index].hash;}else{const url=new URL(location.href);url.searchParams.delete("demonstration");url.searchParams.set("demoSetup","1");url.hash="";location.href=url.toString();}}});
  returnButton.addEventListener("click",()=>{hidden=false;guide.hidden=false;returnButton.hidden=true;});draw();
})();
