(()=>{
"use strict";
const $=id=>document.getElementById(id),esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dates={Thanksgiving:"2026-11-26","Christmas Eve":"2026-12-24","Christmas Day":"2026-12-25","New Year's Eve":"2026-12-31","New Year's Day":"2027-01-01"};
const rooms=["Inlet Room","Sunset Ballroom"];
let state=null,room=rooms[0],chosen=null,busy=false,poller=null;
async function request(route,method="GET",body){const token=localStorage.getItem("blueCurrentV3230Token")||"";const response=await fetch(`/api/harbor-point-demo${route}`,{method,headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify({...body,version:state?.version}):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function notice(message,error=false){const node=$("bcHarborNotice");if(node){node.textContent=message;node.dataset.error=String(error);}}
function render(){if(!state)return;const list=$("bcHarborReservations"),map=$("bcHarborTables"),tab=$("bcHarborRooms");
 tab.innerHTML=rooms.map(name=>`<button type="button" data-room="${esc(name)}" aria-pressed="${name===room}">${esc(name)}</button>`).join("");
 const rows=state.reservations.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 list.innerHTML=rows.length?rows.map(r=>`<article class="bc-harbor-booking"><div><strong>${esc(r.guestName)}</strong><small>${esc(r.holidayEvent)} · ${esc(r.date)} · ${esc(r.time)} · Party ${esc(r.partySize)}</small><small>${esc(r.phone)}${r.tableId?` · Table ${esc(r.tableId)}`:""}</small></div><span class="bc-harbor-state">${esc(r.status)}</span><div class="bc-harbor-booking-actions">${r.status==="confirmed"?`<button type="button" data-action="arrive" data-id="${esc(r.id)}">Mark arrived</button><button type="button" data-action="cancel" data-id="${esc(r.id)}">Cancel</button>`:r.status==="arrived"?`<button type="button" data-action="choose" data-id="${esc(r.id)}">Choose table</button><button type="button" data-action="cancel" data-id="${esc(r.id)}">Cancel</button>`:r.status==="seated"?`<button type="button" data-action="complete" data-id="${esc(r.id)}">Complete service</button>`:""}</div></article>`).join(""):'<p>No fictional reservations yet. Enter one above to rehearse the flow.</p>';
 const available=state.tables.filter(t=>t.room===room&&t.status==="available").length;
 $("bcHarborRoomLabel").textContent=`${room} · ${available} of ${state.tables.filter(t=>t.room===room).length} sample tables available`;
 map.innerHTML=state.tables.filter(t=>t.room===room).map(t=>`<button type="button" class="bc-harbor-table" data-table="${esc(t.id)}" data-status="${esc(t.status)}" aria-label="Sample table ${esc(t.id)}, ${esc(t.status)}"><b>${esc(t.id)}</b><small>${esc(t.status)}</small></button>`).join("");
 $("bcHarborSelection").textContent=chosen?`Seat ${chosen.guestName}: choose an available sample table that fits party of ${chosen.partySize}.`:"Select a table to inspect its current demo state.";
}
async function refresh(silent=false){try{const next=await request("");if(!state||next.version!==state.version){state=next;if(chosen)chosen=state.reservations.find(r=>r.id===chosen.id&&r.status==="arrived")||null;render();}if(!silent)notice("Demo state loaded. Fictional bookings only.");}catch(e){if(!silent)notice(e.message,true);}}
async function mutate(route,body,success){if(busy)return;busy=true;try{await request(route,"POST",body);chosen=null;await refresh(true);notice(success);}catch(e){notice(e.message,true);if(/changed on another device/.test(e.message))await refresh(true);}finally{busy=false;}}
function mount(){const trigger=$("bcHarborPointDemoOpen");if(!trigger||$("bcHarborPointDemo"))return;trigger.textContent="Harbor Point rehearsal";
 const dialog=document.createElement("dialog");dialog.id="bcHarborPointDemo";dialog.className="bc-harbor-demo bc-harbor-operating";dialog.setAttribute("aria-labelledby","bcHarborDemoTitle");
 dialog.innerHTML=`<div class="bc-harbor-shell"><header><div><small>BLUE CURRENT · FUNCTIONAL REHEARSAL</small><h2 id="bcHarborDemoTitle">Harbor Point</h2><p>Fictional holiday bookings · shared demo floor</p></div><button type="button" data-close>Close</button></header><div class="bc-harbor-notice">DEMO ONLY · Use names beginning “Demo” and 732-555-01xx numbers. Sample tables and four-seat limits are not venue-approved. Never enter real guest information.</div><p id="bcHarborNotice" role="status" aria-live="polite"></p><form id="bcHarborForm" class="bc-harbor-form"><label>Holiday<select name="holidayEvent">${Object.keys(dates).map(name=>`<option>${esc(name)}</option>`).join("")}</select></label><label>Date<input name="date" type="date" value="2026-11-26" readonly></label><label>Time<input name="time" type="time" value="17:30" required></label><label>Fictional guest<input name="guestName" value="Demo Guest" maxlength="50" required></label><label>Sample phone<input name="phone" type="tel" value="732-555-0101" required></label><label>Party size<input name="partySize" type="number" min="1" max="4" value="2" required></label><button type="submit">Save demo booking</button></form><div class="bc-harbor-operating-grid"><section><h3>Reservation &amp; arrival</h3><div id="bcHarborReservations" class="bc-harbor-reservations"></div></section><section><h3>Floor</h3><nav id="bcHarborRooms" aria-label="Demo rooms"></nav><p id="bcHarborRoomLabel"></p><div id="bcHarborTables" class="bc-harbor-map"></div><p id="bcHarborSelection" role="status"></p></section></div><footer><span>One shared demo store · refreshes every few seconds</span><button type="button" data-close>Return to Host Stand</button></footer></div>`;
 document.body.appendChild(dialog);const form=$("bcHarborForm");form.elements.holidayEvent.addEventListener("change",()=>{form.elements.date.value=dates[form.elements.holidayEvent.value];});
 trigger.addEventListener("click",()=>{dialog.showModal();refresh();poller=setInterval(()=>{if(!busy)refresh(true);},3500);});
 function close(){dialog.close();clearInterval(poller);poller=null;chosen=null;trigger.focus();}
 dialog.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",close));dialog.addEventListener("close",()=>{clearInterval(poller);poller=null;});
 form.addEventListener("submit",event=>{event.preventDefault();const data=new FormData(form);mutate("/reservations",Object.fromEntries(data),"Demo booking saved. Mark the party arrived when ready.");});
 dialog.addEventListener("click",event=>{const tab=event.target.closest("[data-room]");if(tab){room=tab.dataset.room;render();return;}const action=event.target.closest("[data-action]");if(action){const row=state?.reservations.find(r=>r.id===action.dataset.id);if(!row)return;if(action.dataset.action==="choose"){chosen=row;render();notice(`Choose a sample table for ${row.guestName}.`);}else mutate("/actions",{reservationId:row.id,action:action.dataset.action},action.dataset.action==="arrive"?"Guest arrived and is waiting for a table.":action.dataset.action==="complete"?"Service complete; table is cleaning.":"Demo booking cancelled.");return;}const table=event.target.closest("[data-table]");if(!table)return;const current=state?.tables.find(t=>t.id===table.dataset.table);if(!current)return;if(chosen){if(current.status!=="available"){notice("Choose an available table.",true);return;}mutate("/actions",{reservationId:chosen.id,action:"seat",tableId:current.id},`${chosen.guestName} seated at ${current.id}.`);return;}if(current.status==="cleaning")mutate("/ready",{tableId:current.id},`Table ${current.id} is available again.`);else notice(`${current.id} · ${current.status}. ${current.status==="seated"?"Complete service from the reservation card.":"Select an arrived party to seat."}`);});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount,{once:true});else mount();
})();
