(function(){
"use strict";
const TOKEN_KEY="blueCurrentV3230Token",$=id=>document.getElementById(id);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
const locationId=()=>window.BlueCurrentFrontlineLocation?.get?.()||"loc_marina";
const api=async(path,options={})=>{const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem(TOKEN_KEY)||""}`,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;};
const localDate=()=>{const now=new Date(),offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60000).toISOString().slice(0,10);};
let records=[],selected=null;
function setStatus(message,error=false){const node=$("bcHolidayBookStatus");if(node){node.textContent=message;node.dataset.tone=error?"error":"ok";}}
function selectedDate(){return $("bcReservationBookDate")?.value||localDate();}function eventFilter(){return $("bcReservationBookEvent")?.value||"";}function recordDate(item){return String(item.reservationTime||"").slice(0,10);}
function displayTime(value){const date=new Date(value);return Number.isNaN(date.getTime())?"—":date.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});}
function visibleRecords(){return records.filter(item=>recordDate(item)===selectedDate()&&(!eventFilter()||item.holidayEvent===eventFilter())&&!['cancelled','canceled'].includes(String(item.status||'').toLowerCase()));}
function render(){const list=$("bcReservationList");if(!list)return;const items=visibleRecords(),covers=items.reduce((sum,item)=>sum+Number(item.partySize||0),0);$("bcHolidayReservationCount").textContent=String(items.length);$("bcHolidayCoverCount").textContent=String(covers);list.innerHTML=items.length?items.map(item=>`<article data-holiday-reservation-id="${escapeHtml(item.id)}"><time>${escapeHtml(displayTime(item.reservationTime))}</time><div><strong>${escapeHtml(item.guestName||"Guest")}</strong><span>Party of ${escapeHtml(item.partySize||1)} · ${escapeHtml(item.seatingPreference||"Flexible")}</span>${item.phone?`<small class="bc-reservation-phone">${escapeHtml(item.phone)}</small>`:""}${item.holidayEvent?`<em class="bc-holiday-event">${escapeHtml(item.holidayEvent)}</em>`:""}</div><b data-tone="${String(item.status||'confirmed').toLowerCase()==='arrived'?'arrived':'expected'}">${escapeHtml(item.status||"confirmed")}</b><button type="button" data-holiday-details>Details</button></article>`).join(""):`<p class="reservation-empty">No reservations are saved for this date.</p>`;setStatus(`${items.length} reservation${items.length===1?'':'s'} · ${covers} covers`);}
async function refresh(){try{setStatus("Loading reservation book…");records=await api(`/api/reservation-operations?locationId=${encodeURIComponent(locationId())}`);render();}catch(error){setStatus(error.message,true);}}
function addHolidayFields(){const form=$("bcHostDialogForm"),grid=form?.querySelector(".bc-dialog-grid");if(!grid||grid.querySelector('[name="reservationDate"]')||!grid.querySelector('[name="guestName"]'))return;grid.insertAdjacentHTML("beforeend",`<label><span>Date</span><input name="reservationDate" type="date" required value="${escapeHtml(selectedDate())}"></label><label><span>Phone number</span><input name="phone" type="tel" inputmode="tel" autocomplete="tel" required placeholder="(732) 555-1234"></label><label><span>Holiday / event</span><select name="holidayEvent"><option value="">Regular service</option>${["Thanksgiving","Christmas Eve","Christmas Day","New Year's Eve","New Year's Day"].map(value=>`<option${value===eventFilter()?" selected":""}>${value}</option>`).join("")}</select></label>`);}
async function saveFromDialog(form){const data=new FormData(form);if(!data.get("reservationDate")||!data.get("guestName"))return;try{await api("/api/reservation-operations",{method:"POST",body:JSON.stringify({locationId:locationId(),guestName:data.get("guestName"),phone:data.get("phone"),partySize:Number(data.get("partySize")||1),reservationTime:`${data.get("reservationDate")}T${data.get("time")||"19:30"}:00`,holidayEvent:data.get("holidayEvent"),seatingPreference:data.get("preference")||"Flexible",notes:data.get("notes")||"",source:"Phone reservation"})});await refresh();setStatus(`Reservation saved for ${data.get("guestName")}.`);}catch(error){setStatus(error.message,true);}}
function openDetails(item){selected=item;$("bcHolidayReservationTitle").textContent=item.guestName||"Reservation details";$("bcHolidayReservationBody").innerHTML=`<div class="bc-reservation-detail"><dl class="bc-reservation-detail__grid"><div><dt>Date</dt><dd>${escapeHtml(recordDate(item))}</dd></div><div><dt>Time</dt><dd>${escapeHtml(displayTime(item.reservationTime))}</dd></div><div><dt>Party</dt><dd>${escapeHtml(item.partySize||1)}</dd></div><div><dt>Phone</dt><dd>${escapeHtml(item.phone||"Not recorded")}</dd></div><div><dt>Event</dt><dd>${escapeHtml(item.holidayEvent||"Regular service")}</dd></div><div><dt>Seating</dt><dd>${escapeHtml(item.seatingPreference||"Flexible")}</dd></div><div class="wide"><dt>Notes</dt><dd>${escapeHtml(item.notes||"None recorded")}</dd></div></dl></div>`;$("bcHolidayMarkArrived").hidden=String(item.status||"").toLowerCase()==="arrived";$("bcHolidayReservationDialog").showModal();}
document.addEventListener("DOMContentLoaded",()=>{$("bcReservationBookDate").value=localDate();[$("hostAddReservation"),$("bcReservationQuickAdd")].forEach(button=>button?.addEventListener("click",()=>queueMicrotask(addHolidayFields)));$("bcHostDialogForm")?.addEventListener("submit",event=>{if(event.submitter?.id==="bcHostDialogSubmit")saveFromDialog(event.currentTarget);});$("bcReservationBookDate")?.addEventListener("change",render);$("bcReservationBookEvent")?.addEventListener("change",render);$("bcPrintReservationBook")?.addEventListener("click",()=>window.print());$("bcReservationList")?.addEventListener("click",event=>{const button=event.target.closest("[data-holiday-details]");if(!button)return;const item=records.find(row=>row.id===button.closest("article")?.dataset.holidayReservationId);if(item)openDetails(item);});$("bcHolidayMarkArrived")?.addEventListener("click",async()=>{if(!selected)return;try{await api(`/api/reservation-operations/${encodeURIComponent(selected.id)}`,{method:"PATCH",body:JSON.stringify({status:"arrived"})});$("bcHolidayReservationDialog").close();await refresh();}catch(error){setStatus(error.message,true);}});window.addEventListener("bc:auth-ready",refresh);window.addEventListener("bc:frontline-location-changed",refresh);setTimeout(refresh,700);});
})();
