(() => {
"use strict";
// V100.2.80 — Inventory Truth Foundation.
// Primary Inventory surface shows recorded on-hand state against configured par.
// Predictive reorder, modeled food cost, recipe margin, and vendor recommendations stay outside this truth view.
const LOCATION_ID=window.BlueCurrentFrontlineLocation?.reference||"loc_marina";
const byId=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):null;
let api=null,state=null,loading=false,activated=false;
function ensureStyles(){
 if(byId("bcInventoryTruthStylesV100280"))return;
 const s=document.createElement("style");s.id="bcInventoryTruthStylesV100280";s.textContent=`
 #inventory-intelligence.bc-inventory-truth-active-v280>.container{display:none!important}.bc-inventory-truth-v280{max-width:1180px;margin:0 auto;padding:32px 24px;color:#17343c}
 .bc-inventory-truth-v280 .bc-inv-head,.bc-inventory-truth-v280 .bc-inv-panel-head{display:flex;justify-content:space-between;gap:16px;align-items:center}.bc-inventory-truth-v280 small{color:#6b8086}.bc-inventory-truth-v280 h2{margin:5px 0 7px;font-size:32px}.bc-inventory-truth-v280 h3{margin:3px 0}.bc-inventory-truth-v280 p{color:#5f757c;margin:0}.bc-inventory-truth-v280 button{border:0;border-radius:12px;padding:10px 13px;background:#0c6978;color:#fff;font-weight:900;cursor:pointer}
 .bc-inventory-truth-v280 .bc-inv-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.bc-inventory-truth-v280 .bc-inv-kpis article{padding:14px;background:#fff;border:1px solid #dbe7e9;border-radius:16px}.bc-inventory-truth-v280 .bc-inv-kpis span{display:block;color:#6b8086;font-size:12px}.bc-inventory-truth-v280 .bc-inv-kpis strong{display:block;font-size:25px;margin-top:3px}
 .bc-inventory-truth-v280 .bc-inv-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px;margin-top:14px}.bc-inventory-truth-v280 .bc-inv-panel{background:#fff;border:1px solid #dbe7e9;border-radius:16px;padding:16px;min-width:0}.bc-inventory-truth-v280 .bc-inv-list{display:grid;gap:8px;margin-top:12px}.bc-inventory-truth-v280 .bc-inv-row{border:1px solid #e0eaec;border-radius:12px;padding:11px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.bc-inventory-truth-v280 .bc-inv-row strong,.bc-inventory-truth-v280 .bc-inv-row span,.bc-inventory-truth-v280 .bc-inv-row small{display:block}.bc-inventory-truth-v280 .bc-inv-row span{color:#60767c;margin-top:2px}.bc-inventory-truth-v280 .bc-inv-qty{text-align:right;white-space:nowrap}.bc-inventory-truth-v280 .bc-inv-qty b{display:block;font-size:18px}.bc-inventory-truth-v280 .bc-inv-below{border-color:#eac9c3;background:#fffaf8}.bc-inventory-truth-v280 .bc-inv-empty{padding:15px;color:#647a81;background:#f7fafb;border-radius:12px;margin-top:12px}.bc-inventory-truth-v280 .bc-inv-source{margin-top:14px;font-size:12px;color:#70858b}
 @media(max-width:850px){.bc-inventory-truth-v280 .bc-inv-kpis{grid-template-columns:1fr 1fr}.bc-inventory-truth-v280 .bc-inv-grid{grid-template-columns:1fr}}@media(max-width:560px){.bc-inventory-truth-v280{padding:20px 12px}.bc-inventory-truth-v280 .bc-inv-head{display:block}.bc-inventory-truth-v280 .bc-inv-head button{margin-top:12px}}
 `;document.head.appendChild(s);
}
function shell(){const root=byId("inventory-intelligence");if(!root)return null;root.classList.add("bc-inventory-truth-active-v280");let v=root.querySelector(":scope > .bc-inventory-truth-v280");if(!v){v=document.createElement("div");v.className="bc-inventory-truth-v280";root.appendChild(v)}return v}
function normalizeItems(payload){return (Array.isArray(payload?.items)?payload.items:[]).map(item=>{const onHand=num(item.onHand),par=num(item.par);return {...item,onHand,par,belowPar:onHand!==null&&par!==null&&onHand<par,parGap:onHand!==null&&par!==null?Math.max(0,par-onHand):null}})}
function qty(item){return item.onHand===null?"Unknown":`${item.onHand} ${esc(item.unit||"")}`.trim()}
function parText(item){return item.par===null?"Par unavailable":`Par ${item.par} ${esc(item.unit||"")}`.trim()}
function render(payload){
 state=payload||{};const items=normalizeItems(state),below=items.filter(x=>x.belowPar).sort((a,b)=>(b.parGap||0)-(a.parGap||0)),unknown=items.filter(x=>x.onHand===null||x.par===null);const v=shell();if(!v)return;
 v.innerHTML=`<div class="bc-inv-head"><div><small>Inventory · recorded truth</small><h2>What do we actually have on hand?</h2><p>Blue Current shows the inventory quantities currently recorded for this location and compares them with configured par. Predictions, modeled food cost, and automated reorder advice are intentionally excluded from this primary view.</p></div><button data-bc-inv-refresh>Refresh</button></div>
 <div class="bc-inv-kpis"><article><span>Tracked items</span><strong>${items.length}</strong></article><article><span>Below configured par</span><strong>${below.length}</strong></article><article><span>At / above par</span><strong>${items.filter(x=>x.onHand!==null&&x.par!==null&&!x.belowPar).length}</strong></article><article><span>Quantity/par unknown</span><strong>${unknown.length}</strong></article></div>
 <div class="bc-inv-grid"><section class="bc-inv-panel"><div class="bc-inv-panel-head"><div><small>Current recorded state</small><h3>All tracked inventory</h3></div></div><div class="bc-inv-list">${items.length?items.map(item=>`<article class="bc-inv-row ${item.belowPar?"bc-inv-below":""}"><div><strong>${esc(item.name||item.id||"Unnamed item")}</strong><span>${esc(item.category||"Uncategorized")} · ${parText(item)}</span><small>${item.onHand===null||item.par===null?"Recorded quantity or par is unavailable":item.belowPar?`Recorded ${item.parGap} ${esc(item.unit||"")} below configured par`:`Recorded at or above configured par`}</small></div><div class="bc-inv-qty"><b>${qty(item)}</b><small>on hand</small></div></article>`).join(""):`<div class="bc-inv-empty">No inventory items are recorded for this location.</div>`}</div></section>
 <aside class="bc-inv-panel"><div class="bc-inv-panel-head"><div><small>Needs attention</small><h3>Below configured par</h3></div></div><div class="bc-inv-list">${below.length?below.map(item=>`<article class="bc-inv-row bc-inv-below"><div><strong>${esc(item.name||item.id||"Unnamed item")}</strong><span>${esc(item.category||"Uncategorized")}</span><small>Recorded quantity is below configured par.</small></div><div class="bc-inv-qty"><b>${qty(item)}</b><small>${parText(item)}</small></div></article>`).join(""):`<div class="bc-inv-empty">No recorded items are below configured par.</div>`}</div></aside></div>
 <div class="bc-inv-source">Source: Blue Current Inventory API · location ${esc(state.locationId||LOCATION_ID)} · ${state.generatedAt?`updated ${esc(new Date(state.generatedAt).toLocaleTimeString())}`:"update time unavailable"} · below-par status is a direct comparison of recorded on-hand quantity with configured par</div>`;
 v.querySelector("[data-bc-inv-refresh]")?.addEventListener("click",load);
 window.dispatchEvent(new CustomEvent("bluecurrent:inventory-truth-rendered",{detail:{version:"100.2.80",items:items.length,belowPar:below.length,unknown:unknown.length}}));
}
function message(error){return error?.message||"Inventory source unavailable."}
async function load(){if(loading||!activated)return;loading=true;ensureStyles();shell();try{api ||= new window.BlueCurrentCloudApi("");if(!api?.token)throw new Error("Sign in to load recorded inventory state.");render(await api.inventoryIntelligence(LOCATION_ID))}catch(error){const v=shell();if(v)v.innerHTML=`<div class="bc-inv-head"><div><small>Inventory · recorded truth</small><h2>Inventory unavailable</h2><p>Blue Current will not substitute predictive reorder advice, modeled food cost, or demo quantities when the inventory source is unavailable.</p></div><button data-bc-inv-retry>Try again</button></div><div class="bc-inv-empty"><strong>Inventory source unavailable.</strong><div>${esc(message(error))}</div></div>`;v?.querySelector("[data-bc-inv-retry]")?.addEventListener("click",load)}finally{loading=false}}
function activate(reason="workspace"){if(activated)return;activated=true;ensureStyles();shell();load();window.BlueCurrentInventoryTruthV100_2_80={refresh:load,getState:()=>state?JSON.parse(JSON.stringify(state)):null,reason}}
function routeRequestsInventory(){return /inventory/i.test(`${location.hash} ${location.search}`)}
function init(){const root=byId("inventory-intelligence");if(!root)return;if(routeRequestsInventory())activate("route");window.addEventListener("hashchange",()=>{if(routeRequestsInventory())activate("hashchange")});document.addEventListener("click",event=>{const target=event.target.closest?.("a,button,[role='button']");if(!target)return;const signal=[target.getAttribute("href"),target.dataset?.workspace,target.dataset?.target,target.id,target.textContent].filter(Boolean).join(" ");if(/inventory/i.test(signal))activate("operator-navigation")},true);if("IntersectionObserver" in window){const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting||entry.intersectionRatio>0)){observer.disconnect();activate("workspace-visible")}}, {rootMargin:"400px 0px",threshold:0});observer.observe(root)}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})();
