(function(){
  "use strict";
  if(new URLSearchParams(location.search).get("pilotSetup")!=="1")return;
  const token=()=>localStorage.getItem("blueCurrentV3230Token")||"";
  const api=async(path,options={})=>{const response=await fetch(path,{...options,headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json",...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||`Request failed (${response.status})`);error.details=data.details;throw error;}return data;};
  const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  let state={configuration:null,certification:null,binding:null,simulation:null};
  const style=document.createElement("style");style.textContent=`
  .bc-ps{position:fixed;inset:0;z-index:2147483646;overflow:auto;background:#061f29;color:#f4fbfc;padding:calc(18px + env(safe-area-inset-top)) 16px calc(24px + env(safe-area-inset-bottom));font:600 17px/1.4 system-ui,-apple-system,sans-serif}.bc-ps *{box-sizing:border-box}.bc-ps__shell{max-width:920px;margin:auto}.bc-ps header{display:flex;justify-content:space-between;gap:14px;align-items:center}.bc-ps h1{margin:0;font-size:clamp(26px,5vw,38px)}.bc-ps__card{margin-top:16px;padding:18px;border:1px solid #31515a;border-radius:18px;background:#0b2b35}.bc-ps__steps{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.bc-ps__step{padding:12px;border-radius:12px;background:#173c47}.bc-ps__step[data-ready="true"]{background:#087e65}.bc-ps__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.bc-ps label{display:grid;gap:5px;color:#c7dadd;font-size:14px}.bc-ps input,.bc-ps textarea,.bc-ps button{font:inherit;min-height:48px;border-radius:12px}.bc-ps input,.bc-ps textarea{width:100%;padding:10px;border:1px solid #52727c;background:#fff;color:#10252b}.bc-ps textarea{min-height:130px;font-family:ui-monospace,monospace;font-size:14px}.bc-ps button{padding:11px 16px;border:1px solid #52727c;background:#176d76;color:#fff;font-weight:800}.bc-ps button:disabled{opacity:.45}.bc-ps__action{width:100%;margin-top:14px;background:#087e65!important}.bc-ps__status{min-height:28px;color:#9de4d4}.bc-ps__error{color:#ffb1a9}.bc-ps__blockers{color:#ffd28c}@media(max-width:700px){.bc-ps__steps,.bc-ps__grid{grid-template-columns:1fr}.bc-ps header{align-items:flex-start}}
  `;document.head.appendChild(style);
  const root=document.createElement("main");root.className="bc-ps";root.setAttribute("aria-label","Pilot setup console");root.innerHTML=`<div class="bc-ps__shell"><header><div><small>V100.3.47 · ADMIN SETUP</small><h1>Pilot setup</h1></div><button id="bcPsExit">Exit</button></header><p id="bcPsStatus" class="bc-ps__status">Loading pilot state…</p><section id="bcPsSteps" class="bc-ps__steps"></section><section id="bcPsWork" class="bc-ps__card"></section></div>`;document.body.appendChild(root);
  const $=id=>document.getElementById(id),status=(message,error=false)=>{$("bcPsStatus").textContent=message;$("bcPsStatus").classList.toggle("bc-ps__error",error);};
  const pretty=value=>JSON.stringify(value||[],null,2);
  function phase(){if(!state.configuration?.readiness?.ready)return "configure";if(!state.certification?.current)return "certify";if(!state.binding?.ready)return "bind";if(!state.simulation?.current)return "simulate";return "ready";}
  function draw(){
    const flags=[state.configuration?.readiness?.ready,state.certification?.current,state.binding?.ready,state.simulation?.current];
    $("bcPsSteps").innerHTML=["1 Restaurant","2 Certify","3 Bind","4 Simulate"].map((label,index)=>`<div class="bc-ps__step" data-ready="${Boolean(flags[index])}">${label}<br><small>${flags[index]?"READY":"OPEN"}</small></div>`).join("");
    const current=phase(),cfg=state.configuration?.configuration||{};
    if(current==="configure"){$("bcPsWork").innerHTML=`<h2>Confirm actual restaurant truth</h2><p class="bc-ps__blockers">Open: ${esc((state.configuration?.readiness?.blocking||[]).join(", ")||"Configuration confirmation")}</p><div class="bc-ps__grid"><label>Location ID<input id="bcPsLocationId" value="${esc(cfg.location?.id||"")}"></label><label>Restaurant name<input id="bcPsLocationName" value="${esc(cfg.location?.name||"")}"></label><label>Timezone<input id="bcPsTimezone" value="${esc(cfg.location?.timezone||"America/New_York")}"></label><label>Confirmed by<input id="bcPsConfirmedBy" placeholder="Full name"></label><label>Confirmation source<input id="bcPsSource" placeholder="On-site floor plan and operator review"></label><label>Read-only POS source<input id="bcPsPos" value="${esc(cfg.integrationAssignments?.find(row=>String(row.domain).toUpperCase()==="POS")?.connectorId||"")}" placeholder="Provider name or MANUAL_READ_ONLY"></label></div><label>Dining areas JSON<textarea id="bcPsAreas">${esc(pretty(cfg.diningAreas))}</textarea></label><label>Tables JSON<textarea id="bcPsTables">${esc(pretty(cfg.tables))}</textarea></label><button class="bc-ps__action" id="bcPsSave">Save confirmed configuration</button>`;return;}
    if(current==="certify"){$("bcPsWork").innerHTML=`<h2>Certify configuration</h2><p class="bc-ps__blockers">${esc((state.certification?.assessment?.blocking||[]).join(", ")||"Review the saved restaurant truth, then certify it.")}</p><button class="bc-ps__action" id="bcPsCertify">Certify current configuration</button>`;return;}
    if(current==="bind"){$("bcPsWork").innerHTML=`<h2>Bind pilot workflows</h2><p>Build the protected internal/read-only workflow map from the certified restaurant configuration.</p><button class="bc-ps__action" id="bcPsBind">Build workflow binding</button>`;return;}
    if(current==="simulate"){$("bcPsWork").innerHTML=`<h2>Run required simulation</h2><p>Run all seven isolated pilot scenarios. This does not count as physical iPad evidence.</p><button class="bc-ps__action" id="bcPsSimulate">Run pilot simulation</button>`;return;}
    $("bcPsWork").innerHTML=`<h2>Pilot prerequisites ready</h2><p>Restaurant configuration, certification, workflow binding, and simulation are current.</p><button class="bc-ps__action" id="bcPsWalkthrough">Open physical iPad walkthrough</button>`;
  }
  async function load(){const results=await Promise.all([api("/api/configuration/restaurant"),api("/api/configuration/pilot-certification"),api("/api/pilot/workflow-binding"),api("/api/pilot/service-simulation")]);[state.configuration,state.certification,state.binding,state.simulation]=results;draw();status(phase()==="ready"?"All pilot prerequisites are ready.":"Complete the highlighted setup step.");}
  root.addEventListener("click",async event=>{try{
    if(event.target.id==="bcPsExit"){const url=new URL(location.href);url.searchParams.delete("pilotSetup");location.href=url.toString();return;}
    if(event.target.id==="bcPsSave"){const cfg=state.configuration.configuration,areas=JSON.parse($("bcPsAreas").value),tables=JSON.parse($("bcPsTables").value),pos=$("bcPsPos").value.trim();if(!$("bcPsConfirmedBy").value.trim()||!$("bcPsSource").value.trim())throw new Error("Named confirmation and its source are required.");await api("/api/configuration/restaurant",{method:"PUT",body:JSON.stringify({...cfg,location:{...cfg.location,id:$("bcPsLocationId").value.trim(),name:$("bcPsLocationName").value.trim(),timezone:$("bcPsTimezone").value.trim()},diningAreas:areas,tables,integrationAssignments:[...(cfg.integrationAssignments||[]).filter(row=>String(row.domain).toUpperCase()!=="POS"),{domain:"POS",connectorId:pos||"MANUAL_READ_ONLY"}],pilot:{...cfg.pilot,enabled:true,mode:"PILOT",actualRestaurantDataConfirmed:true,confirmedBy:$("bcPsConfirmedBy").value.trim(),confirmedAt:new Date().toISOString(),confirmationSource:$("bcPsSource").value.trim(),writeBackEnabled:false,autonomousProductionChanges:false}})});}
    if(event.target.id==="bcPsCertify")await api("/api/configuration/pilot-certification/certify",{method:"POST",body:"{}"});
    if(event.target.id==="bcPsBind")await api("/api/pilot/workflow-binding",{method:"POST",body:"{}"});
    if(event.target.id==="bcPsSimulate")await api("/api/pilot/service-simulation/run",{method:"POST",body:"{}"});
    if(event.target.id==="bcPsWalkthrough"){const url=new URL(location.href);url.searchParams.delete("pilotSetup");url.searchParams.set("pilotAcceptance","1");location.href=url.toString();return;}
    status("Saved. Refreshing authoritative pilot state…");await load();
  }catch(error){status(error.message,true);}});
  load().catch(error=>status(error.message,true));
})();
