"use strict";
const fs=require("fs");
const path=require("path");
const root=process.cwd();
const appPath=path.join(root,"client","js","app-v15.1.3.js");
const floorPath=path.join(root,"client","js","floor-reservations-v62.0.js");
const cssPath=path.join(root,"client","styles.css");
for(const p of [appPath,floorPath,cssPath]){if(!fs.existsSync(p)){console.error(`V100.2.40 apply failed: missing ${path.relative(root,p)}`);process.exit(1);}}
let app=fs.readFileSync(appPath,"utf8");
let floor=fs.readFileSync(floorPath,"utf8");
let css=fs.readFileSync(cssPath,"utf8");
if(!css.includes("V100.2.39 — Collision-Safe Premium Floor Layout")){console.error("V100.2.40 requires V100.2.39 first.");process.exit(1);}
if(css.includes("V100.2.40 — Reserved Modal Portal + Reservation-to-Floor Handoff")){console.log("V100.2.40 already applied.");process.exit(0);}
const replaceOnce=(text,from,to,label)=>{if(!text.includes(from)){console.error(`V100.2.40 apply failed: ${label} anchor not found.`);process.exit(1);}return text.replace(from,to);};
fs.writeFileSync(appPath+".v100.2.40.bak",app);
fs.writeFileSync(floorPath+".v100.2.40.bak",floor);
fs.writeFileSync(cssPath+".v100.2.40.bak",css);
app=replaceOnce(app,"    floorMap.appendChild(reservedCard);\n","    document.body.appendChild(reservedCard);\n","reserved modal portal");
floor=replaceOnce(floor,"   }else if(mode===\"reservation-details\"){\n     activeReservationArticle=payload.article||null;\n     dialogTitle.textContent=payload.name||\"Reservation details\";\n","   }else if(mode===\"reservation-details\"){\n     activeReservationArticle=payload.article||null;\n     dialogSubmit.hidden=false;\n     dialogSubmit.textContent=\"Add to waitlist\";\n     dialogTitle.textContent=payload.name||\"Reservation details\";\n","reservation detail footer action");
floor=replaceOnce(floor,"   if(mode===\"walkin\")addWalkin(String(data.get(\"guestName\")||\"Walk-in\"),String(data.get(\"partySize\")||\"2\"),String(data.get(\"preference\")||\"Flexible\"),String(data.get(\"quotedWait\")||\"15\"));\n\n   // V100.2.3: own the post-dialog transition explicitly. Native <dialog> focus\n","   if(mode===\"walkin\")addWalkin(String(data.get(\"guestName\")||\"Walk-in\"),String(data.get(\"partySize\")||\"2\"),String(data.get(\"preference\")||\"Flexible\"),String(data.get(\"quotedWait\")||\"15\"));\n   if(mode===\"reservation-details\"&&activeReservationArticle)handoffReservationToFloor(activeReservationArticle);\n\n   // V100.2.3: own the post-dialog transition explicitly. Native <dialog> focus\n","reservation detail submit handoff");
floor=replaceOnce(floor,"   }else if(mode===\"walkin\"){\n     setView(\"floor\");\n   }\n });\n","   }else if(mode===\"walkin\"||mode===\"reservation-details\"){\n     setView(\"floor\");\n   }\n });\n","post-dialog floor transition");
floor=replaceOnce(floor," function wireReservationDetailActions(payload){\n"," function handoffReservationToFloor(article){\n   if(!article)return false;\n   const record=reservationRecord(article);\n   article.dataset.reservationStatus=\"Arrived\";\n   const badge=article.querySelector(\"b\");\n   if(badge){badge.textContent=\"Arrived\";badge.dataset.tone=\"arrived\";}\n\n   const priorityApi=window.__bcArrivalPriorityQueueV100_2_17;\n   if(priorityApi?.moveArrivalToReady){\n     priorityApi.moveArrivalToReady(article);\n   }else{\n     const list=document.getElementById(\"waitlistQueue\");\n     if(list){\n       const name=record.name;\n       const exists=Array.from(list.querySelectorAll(\".queue-item\")).some(item=>normalizeGuestName(item.querySelector(\"strong\")?.textContent)===normalizeGuestName(name));\n       if(!exists){\n         const item=document.createElement(\"article\");\n         item.className=\"queue-item bc-arrived-reservation-ready-v100-2-40\";\n         item.dataset.bcGuestStatus=\"waiting\";\n         item.dataset.bcSourceType=\"reservation\";\n         item.innerHTML=`<span class=\"queue-time\">0m</span><div><strong>${escapeHtml(name)}</strong><small>Party of ${escapeHtml(record.party)} \u00b7 ${escapeHtml(record.preference)}${record.notes?` \u00b7 ${escapeHtml(record.notes)}`:\"\"}</small></div><button type=\"button\">Seat</button>`;\n         list.appendChild(item);\n         wireSeatButton(item.querySelector(\"button\"));\n       }\n       const count=Array.from(list.querySelectorAll(\".queue-item\")).filter(item=>!item.classList.contains(\"bc-seated\")).length;\n       const badgeNode=document.getElementById(\"waitlistBadge\"),waiting=document.getElementById(\"hostWaiting\"),bc=document.getElementById(\"bcWaitCount\");\n       if(badgeNode)badgeNode.textContent=String(count);if(waiting)waiting.textContent=String(count);if(bc)bc.textContent=String(count);\n     }\n   }\n\n   setView(\"floor\");\n   const waitTab=host.querySelector('.queue-tabs [data-queue=\"waitlist\"]');\n   waitTab?.click();\n   return true;\n }\n\n function wireReservationDetailActions(payload){\n","reservation-to-floor helper");
floor=replaceOnce(floor,"   dialogBody.querySelector('[data-reservation-detail-action=\"arrived\"]')?.addEventListener(\"click\",()=>{\n     article.dataset.reservationStatus=\"Arrived\";const badge=article.querySelector(\"b\");if(badge){badge.textContent=\"Arrived\";badge.dataset.tone=\"arrived\";}\n     if(document.activeElement instanceof HTMLElement)document.activeElement.blur();closeDialog();setView(\"reservations\");article.querySelector('[data-reservation-action=\"details\"]')?.focus({preventScroll:true});\n   });\n","   dialogBody.querySelector('[data-reservation-detail-action=\"arrived\"]')?.addEventListener(\"click\",()=>{\n     handoffReservationToFloor(article);\n     if(document.activeElement instanceof HTMLElement)document.activeElement.blur();\n     closeDialog();\n   });\n","mark-arrived queue handoff");
css += "\n\n/* V100.2.40 \u2014 Reserved Modal Portal + Reservation-to-Floor Handoff */\n/* Reserved-table tools are application-level overlays. Keep them above every table/floor stacking context. */\nbody > .bc-reserved-table-tool-v100-2-26 {\n  position: fixed !important;\n  left: 50vw !important;\n  top: 50vh !important;\n  right: auto !important;\n  bottom: auto !important;\n  transform: translate(-50%, -50%) !important;\n  width: min(520px, calc(100vw - 40px)) !important;\n  max-height: calc(100vh - 48px) !important;\n  overflow: auto !important;\n  z-index: 2147483000 !important;\n  isolation: isolate !important;\n}\nbody > .bc-reserved-table-tool-v100-2-26::before {\n  content: \"\";\n  position: fixed;\n  inset: 0;\n  background: rgba(4, 24, 31, .42);\n  backdrop-filter: blur(2px);\n  z-index: -1;\n  pointer-events: none;\n}\n@media (max-width: 700px) {\n  body > .bc-reserved-table-tool-v100-2-26 {\n    width: calc(100vw - 24px) !important;\n    max-height: calc(100vh - 24px) !important;\n  }\n}\n";
fs.writeFileSync(appPath,app);
fs.writeFileSync(floorPath,floor);
fs.writeFileSync(cssPath,css);
console.log(JSON.stringify({ok:true,version:"100.2.40",repair:"Reserved Modal Portal + Reservation-to-Floor Handoff",fixes:["reserved-table modal is portaled to document.body and centered above every table","Mark arrived in full Reservations moves the party into the live seating queue","Add to waitlist in reservation details performs the same authoritative handoff","handoff is deduplicated and lands the operator back on Floor > Waitlist","existing seating, table-fit, lifecycle, zoned floor maps, and persistence logic remain intact"]},null,2));
