(function(){"use strict";
function createBlueCurrentSchedulingModule(eventBus,appState,cloudFoundationModule){
 const api=cloudFoundationModule?.api||new window.BlueCurrentCloudApi(""),byId=id=>document.getElementById(id);let state={employees:[],shifts:[],validations:[],summary:{},intelligence:{summary:{},recommendations:[]}},weekStart="";
 const iso=d=>d.toISOString().slice(0,10),monday=d=>{const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return iso(x)},money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v||0),days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
 function optionEmployees(selected){return `<option value="">Open shift</option>`+state.employees.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${x.name} · ${x.role}</option>`).join("")}
 function renderAI(){const intel=state.intelligence||{summary:{},recommendations:[]},summary=intel.summary||{};byId("scheduleAiCount").textContent=summary.total||0;byId("scheduleAiActionable").textContent=summary.actionable||0;byId("scheduleAiCritical").textContent=summary.critical||0;byId("scheduleAiRecommendations").innerHTML=(intel.recommendations||[]).map(item=>`<article class="sch-ai-card ${item.priority}"><div><small>${item.type.replaceAll('_',' ')}</small><strong>${item.title}</strong><p>${item.message}</p>${item.candidates?.length?`<ul>${item.candidates.map(c=>`<li>${c.name} · ${c.projectedHours}h · ${c.reasons.join(', ')}</li>`).join('')}</ul>`:''}</div>${item.actionable?`<button class="button button-primary" data-ai-fill="${item.shiftId}" data-ai-employee="${item.candidates[0].employeeId}">Apply best match</button>`:''}</article>`).join("")||"<p class='sch-ai-clear'>No staffing changes are recommended for this week.</p>";}
 function render(){const s=state.summary||{};[["scheduleShiftCount",s.totalShifts],["scheduleOpenCount",s.openShifts],["scheduleHours",s.totalHours],["scheduleLabor",money(s.projectedLabor)],["scheduleConflictCount",s.conflicts],["scheduleWarningCount",s.warnings]].forEach(([id,v])=>{if(byId(id))byId(id).textContent=v??"—"});byId("scheduleWeekLabel").textContent=`${state.weekStart||""} — ${state.weekEnd||""}`;byId("schedulePublication").textContent=state.publication?`Published ${new Date(state.publication.publishedAt).toLocaleString()}`:"Draft schedule";byId("scheduleEmployee").innerHTML=optionEmployees("");
  const start=new Date(`${state.weekStart}T12:00:00`);byId("scheduleBoard").innerHTML=days.map((name,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const date=iso(d),items=state.shifts.filter(x=>x.date===date);return `<section class="sch-day" data-date="${date}"><header><strong>${name}</strong><span>${date.slice(5)}</span></header><div>${items.map(x=>{const emp=state.employees.find(e=>e.id===x.employeeId);const issue=state.validations.find(v=>v.shiftId===x.id);return `<article class="sch-shift ${issue?issue.severity:''}" data-shift="${x.id}"><small>${x.department}</small><strong>${x.role}</strong><span>${x.startTime}–${x.endTime}</span><b>${emp?.name||"Open shift"}</b><div><button data-edit="${x.id}">Edit</button><button data-delete="${x.id}">Delete</button></div></article>`}).join("")||'<p>No shifts</p>'}</div></section>`}).join("");
  byId("scheduleIssues").innerHTML=state.validations.map(x=>`<article class="${x.severity}"><strong>${x.code.replaceAll('_',' ')}</strong><span>${x.message}</span></article>`).join("")||"<p>No schedule conflicts detected.</p>";renderAI();appState.update({scheduledHours:s.totalHours||0,scheduleConflicts:s.conflicts||0,aiSchedulingRecommendations:state.intelligence?.summary?.total||0});}
 async function load(){if(!api.token)return;state=await api.scheduling("loc_marina",weekStart);weekStart=state.weekStart;render();}
 async function run(fn){try{await fn();await load()}catch(error){alert(error.message)}}
 byId("schedulePrev")?.addEventListener("click",()=>{const d=new Date(`${weekStart}T12:00:00`);d.setDate(d.getDate()-7);weekStart=iso(d);load()});byId("scheduleNext")?.addEventListener("click",()=>{const d=new Date(`${weekStart}T12:00:00`);d.setDate(d.getDate()+7);weekStart=iso(d);load()});byId("scheduleToday")?.addEventListener("click",()=>{weekStart=monday(new Date());load()});
 byId("scheduleAdd")?.addEventListener("click",()=>run(()=>api.createScheduleShift({locationId:"loc_marina",date:byId("scheduleDate").value,startTime:byId("scheduleStart").value,endTime:byId("scheduleEnd").value,role:byId("scheduleRole").value,department:byId("scheduleDepartment").value,employeeId:byId("scheduleEmployee").value})));
 byId("schedulePublish")?.addEventListener("click",()=>run(()=>api.publishSchedule({locationId:"loc_marina",weekStart})));byId("scheduleCopy")?.addEventListener("click",()=>run(()=>api.copyPreviousSchedule({locationId:"loc_marina",weekStart})));
 byId("scheduleBoard")?.addEventListener("click",e=>{const del=e.target.closest("[data-delete]"),edit=e.target.closest("[data-edit]");if(del&&confirm("Delete this shift?"))run(()=>api.deleteScheduleShift(del.dataset.delete));if(edit){const shift=state.shifts.find(x=>x.id===edit.dataset.edit);const employeeId=prompt(`Assign employee ID (blank = open)\n${state.employees.map(x=>`${x.id}: ${x.name}`).join("\n")}`,shift.employeeId||"");if(employeeId!==null)run(()=>api.updateScheduleShift(shift.id,{employeeId}))}});
 byId("scheduleAiRecommendations")?.addEventListener("click",e=>{const button=e.target.closest("[data-ai-fill]");if(button&&confirm("Apply Blue Current's best staffing match?"))run(()=>api.smartFillScheduleShift({shiftId:button.dataset.aiFill,employeeId:button.dataset.aiEmployee}))});
 ["scheduling:shift-created","scheduling:shift-updated","scheduling:shift-deleted","scheduling:published","scheduling:week-copied","scheduling:ai-applied"].forEach(x=>eventBus.on?.(x,load));eventBus.on?.("auth:signed-in",load);eventBus.on?.("auth:restored",load);weekStart=monday(new Date());byId("scheduleDate").value=iso(new Date());load();return{reload:load,getState:()=>JSON.parse(JSON.stringify(state))};}
window.createBlueCurrentSchedulingModule=createBlueCurrentSchedulingModule;})();
