(function(){"use strict";
class BlueCurrentSourcePromotionEngine{
 constructor({eventBus,appState}){this.eventBus=eventBus;this.appState=appState;this.off=eventBus.on("ingestion-queue:processed",item=>this.stage(item));}
 state(){return this.appState.get("sourcePromotion")||{status:"idle",staged:{},promoted:{},audit:[]};}
 evaluate(state=this.state(),reason="manual"){const staged=Object.keys(state.staged||{}).length,promoted=Object.keys(state.promoted||{}).length;return{...state,capturedAt:new Date().toISOString(),reason,stagedCount:staged,promotedCount:promoted,status:staged?"approval-required":promoted?"active":"idle",nextAction:staged?"Review staged batches and explicitly approve promotion into the trusted pilot dataset.":promoted?"Trusted pilot records are active; live source-of-truth systems remain unchanged.":"Process an ingestion batch to begin promotion review."};}
 save(state,reason){const value=this.evaluate(state,reason);this.appState.update({sourcePromotion:value,sourcePromotionHistory:[...(this.appState.get("sourcePromotionHistory")||[]),{capturedAt:value.capturedAt,reason,status:value.status,stagedCount:value.stagedCount,promotedCount:value.promotedCount}].slice(-50)});this.eventBus.emit("source-promotion:updated",structuredClone(value));return value;}
 stage(item){const s=this.state(),staged={...(s.staged||{}),[item.id]:{id:item.id,source:item.source,records:item.records||[],recordCount:item.recordCount,stagedAt:new Date().toISOString()}};return this.save({...s,staged},"stage");}
 promote(id,owner){const s=this.state(),item=s.staged?.[id];if(!item)return this.evaluate(s);const promoted={...(s.promoted||{})};promoted[item.source]={...item,promotedAt:new Date().toISOString(),owner:owner||"Manager approval"};const staged={...(s.staged||{})};delete staged[id];const audit=[...(s.audit||[]),{id:`audit_${Date.now()}`,action:"promote",batchId:id,source:item.source,owner:owner||"Manager approval",at:new Date().toISOString(),records:item.recordCount}].slice(-100);const value=this.save({...s,staged,promoted,audit},"promote");this.eventBus.emit("trusted-pilot-source:promoted",{source:item.source,records:item.records,owner});return value;}
 decline(id,owner){const s=this.state(),item=s.staged?.[id];if(!item)return this.evaluate(s);const staged={...(s.staged||{})};delete staged[id];const audit=[...(s.audit||[]),{id:`audit_${Date.now()}`,action:"decline",batchId:id,source:item.source,owner:owner||"Manager review",at:new Date().toISOString(),records:item.recordCount}].slice(-100);return this.save({...s,staged,audit},"decline");}
 snapshot(){return this.evaluate(this.state());}
 export(){const blob=new Blob([JSON.stringify(this.snapshot(),null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`blue-current-source-promotion-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
 destroy(){this.off?.();}
}
window.BlueCurrentSourcePromotionEngine=BlueCurrentSourcePromotionEngine;})();