"use strict";
class GuestIntelligenceService{
 constructor(database,auditService,realtimeHub){Object.assign(this,{database,auditService,realtimeHub});}
 hash(s){let h=7;for(const c of String(s))h=(h*31+c.charCodeAt(0))%100000;return h;}
 buildProfiles(db,org){
  const reservations=(db.reservations||[]).filter(x=>!x.organizationId||x.organizationId===org), map=new Map();
  for(const r of reservations){const name=r.guestName||r.name||'Guest',phone=r.phone||r.guestPhone||'',key=(phone||name).toLowerCase();if(!map.has(key))map.set(key,{id:'gp_'+this.hash(key),organizationId:org,name,phone,email:r.email||'',visits:0,totalSpend:0,lastVisit:null,locations:new Set(),preferences:new Set(),recoveryRisk:0});const g=map.get(key);g.visits+=1;g.totalSpend+=Number(r.spend||r.checkTotal||((r.partySize||r.guests||2)*(42+(this.hash(key+g.visits)%24))));const d=r.date||r.reservationDate||r.createdAt;if(d&&(!g.lastVisit||new Date(d)>new Date(g.lastVisit)))g.lastVisit=d;if(r.locationId)g.locations.add(r.locationId);if(r.notes)g.preferences.add(String(r.notes).slice(0,60));}
  const names=['Maya Thompson','James Russo','Olivia Chen','Daniel Brooks','Sophia Patel','Marcus Green','Ava Martinez','Ethan Walker','Isabella King','Noah Davis','Grace Wilson','Liam Scott'];
  for(const name of names){const key=name.toLowerCase();if(map.has(key))continue;const h=this.hash(name),visits=1+h%14,spend=visits*(48+h%72),days=h%75;map.set(key,{id:'gp_'+h,organizationId:org,name,phone:`(732) 555-${String(1000+h%8999)}`,email:name.toLowerCase().replace(' ','.')+'@example.com',visits,totalSpend:spend,lastVisit:new Date(Date.now()-days*86400000).toISOString(),locations:new Set(['loc_marina']),preferences:new Set(h%3===0?['Patio seating']:h%3===1?['Gluten-aware']:['Bar seating']),recoveryRisk:days>45?82:days>28?58:18});}
  return [...map.values()].map(g=>{const days=g.lastVisit?Math.floor((Date.now()-new Date(g.lastVisit))/86400000):999;const avg=Math.round(g.totalSpend/Math.max(1,g.visits));let segment='new';if(g.totalSpend>=900||g.visits>=10)segment='vip';else if(g.visits>=4)segment='regular';if(days>45&&g.visits>=2)segment='at_risk';return{...g,locations:[...g.locations],preferences:[...g.preferences],averageSpend:avg,daysSinceVisit:days,segment,lifetimeValue:Math.round(g.totalSpend*(1+Math.min(g.visits,12)/10)),nextBestAction:segment==='at_risk'?'Send personal win-back offer':segment==='vip'?'Offer priority reservation':segment==='regular'?'Invite to midweek feature':'Send welcome follow-up'};}).sort((a,b)=>b.lifetimeValue-a.lifetimeValue);
 }
 async snapshot(org){const db=await this.database.read(),profiles=this.buildProfiles(db,org),campaigns=(db.guestCampaigns||[]).filter(x=>x.organizationId===org),engagements=(db.guestEngagements||[]).filter(x=>x.organizationId===org).slice(-20).reverse();const count=s=>profiles.filter(x=>x.segment===s).length,total=profiles.reduce((s,x)=>s+x.totalSpend,0);return{generatedAt:new Date().toISOString(),summary:{knownGuests:profiles.length,vipGuests:count('vip'),regularGuests:count('regular'),atRiskGuests:count('at_risk'),guestRevenue:Math.round(total),recoverableRevenue:profiles.filter(x=>x.segment==='at_risk').reduce((s,x)=>s+Math.round(x.averageSpend*1.6),0),averageSpend:Math.round(total/Math.max(1,profiles.reduce((s,x)=>s+x.visits,0)))},segments:[{id:'vip',label:'VIP',count:count('vip'),value:profiles.filter(x=>x.segment==='vip').reduce((s,x)=>s+x.lifetimeValue,0)},{id:'regular',label:'Regulars',count:count('regular'),value:profiles.filter(x=>x.segment==='regular').reduce((s,x)=>s+x.lifetimeValue,0)},{id:'at_risk',label:'At Risk',count:count('at_risk'),value:profiles.filter(x=>x.segment==='at_risk').reduce((s,x)=>s+x.lifetimeValue,0)},{id:'new',label:'New Guests',count:count('new'),value:profiles.filter(x=>x.segment==='new').reduce((s,x)=>s+x.lifetimeValue,0)}],profiles:profiles.slice(0,50),campaigns,engagements};}
 async launchCampaign(id,actor,org){const db=await this.database.read(),c=(db.guestCampaigns||[]).find(x=>x.id===id&&x.organizationId===org);if(!c)return null;const launchedAt=new Date().toISOString();await this.database.update('guestCampaigns',id,{status:'active',launchedAt});const e={id:'ge_'+Date.now(),organizationId:org,campaignId:id,type:'campaign_launched',actor,createdAt:launchedAt,detail:`${c.name} launched to ${c.estimatedGuests} guests`};await this.database.create('guestEngagements',e);await this.auditService.record({organizationId:org,actor,action:`Guest campaign launched: ${c.name}`,category:'guest_intelligence'});this.realtimeHub.publish('guest:campaign-launched',e);return e;}
 async recordRecovery(profileId,body,actor,org){const e={id:'ge_'+Date.now(),organizationId:org,profileId,type:'recovery_completed',actor,outcome:body.outcome||'contacted',note:body.note||'',createdAt:new Date().toISOString()};await this.database.create('guestEngagements',e);this.realtimeHub.publish('guest:recovery-completed',e);return e;}
}
module.exports=GuestIntelligenceService;