(function(){"use strict";
function createBlueCurrentAipPersistentAgentRuntimeCenterModule(){const root=document.getElementById('aipPersistentAgentRuntimeCenter');if(!root||!window.BlueCurrentAipPersistentAgentRuntimeEngine)return null;const e=new window.BlueCurrentAipPersistentAgentRuntimeEngine(),$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let current=null;
 function renderRun(r){current=r||null;$('aparStatus').textContent=r?.status||'—';$('aparAgent').textContent=r?.agentType||'—';$('aparApproval').textContent=r?.approvalRequired?'YES':'NO';$('aparCheckpoints').textContent=r?.checkpointCount||0;$('aparCurrent').textContent=r?`${r.id} · ${r.executionMode}`:'Create a run from the latest compiled automation.';}
 async function load(){try{const x=await e.load(),rows=x.items||[];renderRun(rows[0]);$('aparCount').textContent=x.count||0;$('aparList').innerHTML=rows.slice(0,20).map(r=>`<article><div><strong>${esc(r.agentType)} · ${esc(r.status)}</strong><span>${esc(r.id)} · ${esc(r.intent)} · ${r.stepCount||0} steps · ${r.approvalRequired?'approval-gated':'dry-run ready'}</span></div><button type="button" data-run-id="${esc(r.id)}">Inspect</button></article>`).join('')||'<p>No persistent AIP agent runs yet.</p>';}catch(err){$('aparCurrent').textContent=err.message;}}
 async function create(){try{const x=await e.create($('aparAgentType')?.value||'operations-optimizer');renderRun(x.run);await load();}catch(err){$('aparCurrent').textContent=err.message;}}
 root.addEventListener('click',async ev=>{const id=ev.target.closest('[data-run-id]')?.dataset.runId;if(!id)return;try{const x=await e.context(id);renderRun(x.run);$('aparContext').textContent=JSON.stringify(x.context,null,2);}catch(err){$('aparContext').textContent=err.message;}});
 $('aparRefresh')?.addEventListener('click',load);$('aparCreate')?.addEventListener('click',create);load();return{engine:e,load,create,getCurrent:()=>current};}
window.createBlueCurrentAipPersistentAgentRuntimeCenterModule=createBlueCurrentAipPersistentAgentRuntimeCenterModule;
})();
