(function(){"use strict";
class BlueCurrentAIPToolRegistry{
  constructor(appState,eventBus){this.appState=appState;this.eventBus=eventBus;this.tools=new Map();this.auditKey="bluecurrent:v400:aip-tool-audit";this.registerDefaults();}
  register(def){if(!def?.name||typeof def.run!=="function")throw new Error("AIP tools require a name and run function.");this.tools.set(def.name,{risk:"read",approval:false,...def});return this;}
  list(){return [...this.tools.values()].map(({run,...meta})=>meta);}
  audit(entry){let rows=[];try{rows=JSON.parse(localStorage.getItem(this.auditKey)||"[]");}catch{}rows.unshift(entry);localStorage.setItem(this.auditKey,JSON.stringify(rows.slice(0,100)));}
  async execute(name,input={},context={}){const tool=this.tools.get(name);if(!tool)throw new Error(`Unknown AIP tool: ${name}`);if(tool.approval&&!context.approved){const request={id:`APR-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,status:"approval_required",type:"tool",title:tool.label||name,tool:name,owner:context.owner||"Manager",risk:tool.risk,request:{input},evidence:{agent:context.agent||"operator"}};this.eventBus?.emit?.("aip:approval-requested",request);return request;}const started=performance.now();const result=await tool.run(input,context);const record={id:`AIP-${Date.now()}`,tool:name,status:"complete",durationMs:Math.round(performance.now()-started),at:new Date().toISOString(),agent:context.agent||"operator"};this.audit(record);this.eventBus?.emit?.("aip:tool-executed",{...record,result});return{...record,result};}
  registerDefaults(){
    this.register({name:"operations.snapshot",label:"Read operating snapshot",description:"Returns current shift, guest, labor, kitchen, and revenue signals.",run:()=>{const s=this.appState?.getState?.()||{};return{serviceStatus:s.serviceStatus,occupancyPercent:s.occupancyPercent,guestWaitMinutes:s.guestWaitMinutes||s.waitMinutes||0,kitchenPressure:s.kitchenPressure||s.kitchenLoad||0,laborPercent:s.laborPercent||s.laborCostPercent||0,estimatedRevenue:s.estimatedRevenue||0,shiftScore:s.shiftIntelligence?.score||s.restaurantHealth||0};}})
    .register({name:"operations.priorities",label:"Read current priorities",description:"Returns ranked operational priorities already calculated by Blue Current.",run:()=>{const s=this.appState?.getState?.()||{};return s.shiftIntelligence?.recommendations||s.executiveDecisionFeed?.items||[];}})
    .register({name:"operations.exceptions",label:"Read service exceptions",description:"Returns locally governed unresolved exceptions.",run:()=>{try{const x=JSON.parse(localStorage.getItem("bluecurrent:v3918:exceptions")||"{}");return Object.entries(x).map(([id,v])=>({id,...v})).filter(x=>x.status!=="resolved");}catch{return[];}}})
    .register({name:"workflow.draft",label:"Draft governed workflow",description:"Creates a draft only; execution requires human approval.",risk:"write",approval:true,run:(input)=>({draftId:`WF-${Date.now()}`,status:"draft",...input})});
  }
}
window.BlueCurrentAIPToolRegistry=BlueCurrentAIPToolRegistry;})();