(function(){"use strict";
class BlueCurrentDataContractEngine{
 constructor({eventBus,appState}){this.eventBus=eventBus;this.appState=appState;this.value=null;["integration-control:updated","signal-quality:updated","state:changed"].forEach(n=>eventBus.on(n,()=>this.refresh(n)))}
 refresh(reason="manual"){const s=this.appState.getState(),sources=s.integrationControl?.sources||[];const contracts=[
 {id:"reservations",label:"Reservations",required:["reservationId","guestName","partySize","scheduledAt","status"],source:sources.find(x=>x.id==="reservations")},
 {id:"pos",label:"POS / Revenue",required:["checkId","locationId","openedAt","subtotal","discount","closedAt"],source:sources.find(x=>x.id==="pos")},
 {id:"labor",label:"Labor / Time clock",required:["employeeId","role","clockIn","clockOut","locationId"],source:sources.find(x=>x.id==="labor")},
 {id:"inventory",label:"Inventory / Purchasing",required:["itemId","quantity","unitCost","vendorId","updatedAt"],source:sources.find(x=>x.id==="inventory")}
 ].map(c=>{const connected=!!c.source?.connected,quality=connected?(c.source?.freshness==="fresh"?100:c.source?.freshness==="aging"?78:58):0;return{...c,connected,quality,status:quality>=85?"valid":quality>=60?"watch":"blocked",missing:connected?[]:c.required.slice(0,2)}});const blockers=contracts.filter(x=>x.status==="blocked"&&["reservations","pos","labor"].includes(x.id));const score=Math.round(contracts.reduce((n,x)=>n+x.quality,0)/contracts.length);const value={capturedAt:new Date().toISOString(),reason,version:"V37.1.0",score,status:blockers.length?"blocked":score>=85?"ready":score>=65?"watch":"forming",contracts,blockers:blockers.map(x=>x.label),nextAction:blockers.length?`Map required fields for ${blockers[0].label}.`:score<85?"Resolve contract watch items before production traffic.":"Data contracts are ready for controlled connector testing."};this.value=value;this.appState.update({dataContractRegistry:value,dataContractHistory:[...(s.dataContractHistory||[]),value].slice(-50)});this.eventBus.emit("data-contract:updated",structuredClone(value));return structuredClone(value)}
 snapshot(){return structuredClone(this.value||this.refresh("initial"))}}
window.BlueCurrentDataContractEngine=BlueCurrentDataContractEngine;})();