(function(){"use strict";function createBlueCurrentExecutivePilotReviewCenterModule(eventBus,appState){const root=document.getElementById("executivePilotReview");if(!root||!window.BlueCurrentExecutivePilotReviewEngine)return null;const e=new window.BlueCurrentExecutivePilotReviewEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c])),money=n=>`$${Number(n||0).toLocaleString()}`;
function render(s){const p=s.packet||{},b=p.baselineVsCurrent||{},r=p.recommendation||{};$("eprDecision").textContent=p.decision||"—";$("eprConfidence").textContent=p.confidence||"—";$("eprVerified").textContent=money(p.evidence?.verifiedRealizedImpactDollars||0);$("eprExceptions").textContent=(p.exceptions||[]).length;$("eprHeadline").textContent=s.headline||"Executive review unavailable.";$("eprSummary").textContent=p.executiveSummary||"";
$("eprMovement").innerHTML=p.baselineVsCurrent?`<article><small>Readiness</small><strong>${b.readiness.baseline} → ${b.readiness.current}</strong></article><article><small>Operating rhythm</small><strong>${b.operatingRhythm.baseline}% → ${b.operatingRhythm.current}%</strong></article><article><small>Modeled leakage</small><strong>${money(b.modeledLeakage.baseline)} → ${money(b.modeledLeakage.current)}</strong></article><article><small>Verified realized value</small><strong>${money(b.verifiedRealizedValue.current)}</strong></article>`:"";
$("eprGates").innerHTML=(p.successGates||[]).map(x=>`<article><strong>${x.passed?"PASS":"OPEN"} · ${esc(x.name)}</strong></article>`).join("");
$("eprLocations").innerHTML=(p.locationReview||[]).map(x=>`<article><strong>${esc(x.locationName)} · ${esc(x.owner||"Unassigned")}</strong><span>Targets ${x.targetsMet}/${x.targetsMeasured} · Readiness ${x.readinessLift>=0?"+":""}${x.readinessLift} · Rhythm ${x.rhythmLift>=0?"+":""}${x.rhythmLift} · Leakage reduction ${x.leakageReductionPercent}%</span></article>`).join("");
$("eprNext").textContent=r.nextAction||"";}
async function load(){try{render(await e.snapshot());}catch(err){$("eprHeadline").textContent=err.message;}}
$("eprRefresh")?.addEventListener("click",load);$("eprArchive")?.addEventListener("click",async()=>{try{const x=await e.archive($("eprNote").value||"");$("eprHeadline").textContent=`Archived ${x.id} · ${x.packet.decision}`;}catch(err){$("eprHeadline").textContent=err.message;}});
$("eprCopy")?.addEventListener("click",async()=>{try{const t=await e.text();await navigator.clipboard.writeText(t);$("eprHeadline").textContent="Executive review packet copied to clipboard.";}catch(err){$("eprHeadline").textContent=err.message;}});
["pilot-proof:configured","pilot-value:checkpoint","pilot-review:archived","auth:restored"].forEach(x=>eventBus?.on?.(x,load));load();return{engine:e,load};}window.createBlueCurrentExecutivePilotReviewCenterModule=createBlueCurrentExecutivePilotReviewCenterModule;})();