(function(){"use strict";
function createBlueCurrentHospitalityPerformanceCenterModule(eventBus,appState){const root=document.getElementById("hospitalityPerformanceCommand");if(!root||!window.BlueCurrentHospitalityPerformanceEngine)return null;const e=new window.BlueCurrentHospitalityPerformanceEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));let snapshot=null;
function categoryLabel(x){return ({reservations:"Reservations",labor:"Labor",kitchen:"Kitchen",guests:"Guest",inventory:"Inventory",revenue:"Revenue"})[x]||x;}
function money(n){return `$${Number(n||0).toLocaleString()}`;}
function render(s){snapshot=s;$("hpcOpen").textContent=s.summary?.openOpportunities||0;$("hpcImpact").textContent=money(s.summary?.totalEstimatedImpactDollars||0);$("hpcHigh").textContent=s.summary?.highPriority||0;$("hpcReadiness").textContent=s.summary?.readinessScore==null?"—":`${s.summary.readinessScore}%`;$("hpcTrend").textContent=`${Number(s.summary?.portfolioRevenueTrend||0)>=0?"+":""}${Number(s.summary?.portfolioRevenueTrend||0).toFixed(1)}%`;$("hpcHeadline").textContent=s.headline||"No material performance opportunities are active.";$("hpcUpdated").textContent=new Date(s.generatedAt).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"});
$("hpcQueue").innerHTML=(s.opportunities||[]).map(x=>`<article class="hpc-opportunity" data-opportunity="${esc(x.id)}"><div class="hpc-rank">#${x.rank}</div><div class="hpc-copy"><div><span>${esc(categoryLabel(x.category))}</span><b>${esc(x.severity)}</b><small>${x.confidence}% confidence</small></div><strong>${esc(x.title)}</strong><p>${esc(x.why)}</p><p><b>Next:</b> ${esc(x.nextAction)}</p><div class="hpc-meta"><span>${esc(x.owner)}</span><span>Score ${x.score}</span><span>${esc(x.impactLabel)}</span></div>${x.lastDecision?`<small>Last decision: ${esc(x.lastDecision.decision)} · ${esc(x.lastDecision.owner||x.lastDecision.actor)}</small>`:""}</div><div class="hpc-impact"><strong>${money(x.estimatedImpactDollars)}</strong><span>estimated impact</span><button type="button" data-hpc-decision="accepted">Own action</button><button type="button" data-hpc-decision="snoozed">Snooze</button><button type="button" data-hpc-decision="completed">Complete</button></div></article>`).join("")||"<article><strong>Operation is clear.</strong><span>No material opportunities are active right now.</span></article>";
$("hpcSources").textContent=Object.entries(s.sourceHealth||{}).filter(([,ok])=>ok).map(([name])=>name.replace(/([A-Z])/g," $1")).join(" · ");}
async function load(){try{$("hpcHeadline").textContent="Building the highest-value operating queue…";render(await e.snapshot());}catch(err){$("hpcHeadline").textContent=err.message;}}
root.addEventListener("click",async ev=>{const btn=ev.target.closest("[data-hpc-decision]"),card=ev.target.closest("[data-opportunity]");if(!btn||!card)return;try{btn.disabled=true;await e.decide(card.dataset.opportunity,btn.dataset.hpcDecision,$("hpcOwner").value||"Manager",$("hpcNote").value||"");await load();}catch(err){$("hpcHeadline").textContent=err.message;}finally{btn.disabled=false;}});
$("hpcRefresh")?.addEventListener("click",load);window.addEventListener?.("online",load);eventBus?.on?.("auth:restored",load);eventBus?.on?.("reservation:updated",load);eventBus?.on?.("inventory:action-recorded",load);eventBus?.on?.("workforce:action-recorded",load);load();return{engine:e,load};}
window.createBlueCurrentHospitalityPerformanceCenterModule=createBlueCurrentHospitalityPerformanceCenterModule;})();