(function(){"use strict";
class BlueCurrentNetworkRequestEngine{
 constructor({eventBus,appState}){this.eventBus=eventBus;this.appState=appState;this.pending=new Map();this.history=[];this.sequence=0;this.originalFetch=null;this.originalOpen=null;this.originalSend=null;this.install();this.timer=setInterval(()=>this.publish("sample"),4000);setTimeout(()=>this.publish("initial"),0);}
 install(){if(window.__blueCurrentNetworkBudgetInstalled)return;window.__blueCurrentNetworkBudgetInstalled=true;this.patchFetch();this.patchXhr();}
 recordStart(kind,url){const id=++this.sequence;this.pending.set(id,{id,kind,url:String(url||"unknown"),startedAt:performance.now(),startedIso:new Date().toISOString()});return id;}
 recordEnd(id,status,error=""){const item=this.pending.get(id);if(!item)return;this.pending.delete(id);const duration=Math.max(0,Math.round(performance.now()-item.startedAt));this.history.unshift({...item,status:Number(status||0),error:String(error||""),durationMs:duration,completedAt:new Date().toISOString()});this.history=this.history.slice(0,80);if(duration>2000||status>=400||error)this.publish("request-complete");}
 patchFetch(){if(typeof window.fetch!=="function")return;this.originalFetch=window.fetch.bind(window);const self=this;window.fetch=async function(input,init){const url=typeof input==="string"?input:input?.url;const id=self.recordStart("fetch",url);try{const response=await self.originalFetch(input,init);self.recordEnd(id,response.status);return response;}catch(error){self.recordEnd(id,0,error?.message||error);throw error;}};}
 patchXhr(){if(!window.XMLHttpRequest)return;const self=this,proto=XMLHttpRequest.prototype;this.originalOpen=proto.open;this.originalSend=proto.send;proto.open=function(method,url,...rest){this.__bcUrl=url;this.__bcMethod=method;return self.originalOpen.call(this,method,url,...rest);};proto.send=function(...args){const id=self.recordStart("xhr",this.__bcUrl);this.addEventListener("loadend",()=>self.recordEnd(id,this.status),{once:true});this.addEventListener("error",()=>self.recordEnd(id,this.status,"network error"),{once:true});return self.originalSend.apply(this,args);};}
 snapshot(reason="manual"){const now=performance.now(),pending=[...this.pending.values()].map(item=>({...item,ageMs:Math.round(now-item.startedAt)}));const recent=this.history.filter(item=>Date.now()-Date.parse(item.completedAt)<60000);const slow=recent.filter(item=>item.durationMs>2000),failed=recent.filter(item=>item.status>=400||item.error);const hanging=pending.filter(item=>item.ageMs>8000);const score=Math.max(0,100-Math.min(35,failed.length*12)-Math.min(30,slow.length*6)-Math.min(35,hanging.length*18));return{capturedAt:new Date().toISOString(),reason,score,status:score>=85?"healthy":score>=60?"watch":"critical",pending:pending.length,hanging:hanging.length,slow:slow.length,failed:failed.length,recent:recent.length,requests:[...hanging,...slow,...failed].slice(0,8)};}
 publish(reason="manual"){const value=this.snapshot(reason);this.appState.update({networkRequestBudget:value});this.eventBus.emit("network-budget:updated",structuredClone(value));return value;}
 destroy(){clearInterval(this.timer);}
}
window.BlueCurrentNetworkRequestEngine=BlueCurrentNetworkRequestEngine;})();