(function(global){"use strict";
class BlueCurrentOperatorConsolidationScorecardEngine{
  constructor({eventBus,appState,consolidationEngine,rationalizationEngine,flowEngine}={}){this.eventBus=eventBus;this.appState=appState;this.consolidationEngine=consolidationEngine||null;this.rationalizationEngine=rationalizationEngine||null;this.flowEngine=flowEngine||null;this.stageCenters=["reservationOperationsCenter","liveFloorOperationsCenter","kitchenThroughputCenter","laborDeploymentCenter","guestRecoveryCenter","shiftProfitPulseCenter"];}
  state(){try{return this.appState?.getState?.()||{};}catch{return {};}}
  navigationEntries(entries=null){if(Array.isArray(entries))return entries.map(x=>typeof x==="string"?{href:x,label:x,nav:"provided"}:{nav:"provided",...x});if(typeof document==="undefined")return [];return [...document.querySelectorAll(".desktop-nav a,.mobile-nav a")].map(a=>({href:a.getAttribute("href")||"",label:(a.textContent||"").trim(),nav:a.closest(".mobile-nav")?"mobile":"desktop"}));}
  duplicateNavigation(entries=null){const nav=this.navigationEntries(entries),buckets={};nav.forEach(x=>{const key=`${x.nav||"unknown"}::${x.href||""}`;(buckets[key] ||= []).push(x);});const groups=Object.values(buckets).filter(items=>items[0]?.href&&items.length>1).map(items=>({nav:items[0].nav||"unknown",href:items[0].href,count:items.length,labels:[...new Set(items.map(x=>x.label))],excess:items.length-1}));const uniqueHrefs=new Set(nav.map(x=>x.href).filter(Boolean));return {entries:nav.length,uniqueHrefs:uniqueHrefs.size,duplicateGroups:groups.length,duplicateEntries:groups.reduce((s,x)=>s+x.excess,0),groups};}
  workflowCoverage(role=null){const consolidation=this.consolidationEngine?.navigationModel?.(role)||{defaultSurfaces:[]},defaults=new Set(consolidation.defaultSurfaces||[]);const covered=this.stageCenters.filter(x=>defaults.has(x));return {required:this.stageCenters.length,covered:covered.length,percent:Math.round(100*covered.length/this.stageCenters.length),coveredCenters:covered,missingCenters:this.stageCenters.filter(x=>!defaults.has(x))};}
  handoffHealth(){const flow=this.flowEngine?.snapshot?.()||this.state().operatorServiceFlow||{handoffs:[]};const handoffs=flow.handoffs||[],attention=handoffs.filter(x=>x.status==="attention");return {total:handoffs.length,attention:attention.length,clear:handoffs.length-attention.length,percent:handoffs.length?Math.round(100*(handoffs.length-attention.length)/handoffs.length):100,attentionIds:attention.map(x=>x.id)};}
  usageByRole(){const evidence=this.consolidationEngine?.evidence?.()||this.state().operatorUseEvidence||[],roles={};for(const e of evidence){const role=e.role||"unknown";roles[role] ||= {role,events:0,surfaces:new Set(),actions:{}};roles[role].events++;roles[role].surfaces.add(e.surfaceId);roles[role].actions[e.action]=(roles[role].actions[e.action]||0)+1;}return Object.values(roles).map(x=>({role:x.role,events:x.events,uniqueSurfaces:x.surfaces.size,actions:x.actions})).sort((a,b)=>b.events-a.events);}
  clicksToAction(){const evidence=this.consolidationEngine?.evidence?.()||this.state().operatorUseEvidence||[];const actions=new Set(["action","execute","acknowledge","resolve","approve","create-action","open-action","task-completed"]);let opens=0,completed=0;for(const e of evidence){if(e.action==="open")opens++;if(actions.has(e.action))completed++;}const proxy=completed?Math.max(1,Math.round(opens/completed)):opens?opens:null;return {openEvents:opens,actionEvents:completed,clicksPerActionProxy:proxy,measurement:"instrumented-use-event-proxy"};}
  shortlist(ids=null){const rational=this.rationalizationEngine?.snapshot?.(ids)||{items:[]},usage=new Map((this.consolidationEngine?.evidenceSummary?.(rational.items.map(x=>x.id))||[]).map(x=>[x.surfaceId,x]));const coverage=this.workflowCoverage("manager");return rational.items.filter(x=>x.disposition==="deprecation-candidate").map(item=>{const u=usage.get(item.id)||{uses:0,roles:[],lastUsedAt:null};const eligible=u.uses===0&&coverage.percent===100;return {...item,usage:u,shortlistStatus:eligible?"eligible-for-deprecation-review":u.uses>0?"retain-observed-use":"blocked-until-primary-coverage",automaticDeletion:false};}).sort((a,b)=>a.usage.uses-b.usage.uses);}
  score(entries=null,ids=null){const nav=this.duplicateNavigation(entries),coverage=this.workflowCoverage("manager"),handoffs=this.handoffHealth(),clicks=this.clicksToAction(),usage=this.usageByRole(),shortlist=this.shortlist(ids);const navScore=Math.max(0,100-nav.duplicateEntries*8),coverageScore=coverage.percent,handoffScore=handoffs.percent,evidenceScore=Math.min(100,(this.consolidationEngine?.evidence?.()||[]).length*10),score=Math.round(navScore*.25+coverageScore*.35+handoffScore*.20+evidenceScore*.20);return {score,grade:score>=90?"A":score>=80?"B":score>=70?"C":score>=60?"D":"F",navigation:{...nav,score:navScore},workflowCoverage:coverage,handoffs,clicksToAction:clicks,usageByRole:usage,evidenceEvents:(this.consolidationEngine?.evidence?.()||[]).length,deprecationShortlist:shortlist,shortlistEligible:shortlist.filter(x=>x.shortlistStatus==="eligible-for-deprecation-review").length,policy:"evidence-backed-review-no-automatic-deletion",version:"46.25.0",capturedAt:new Date().toISOString()};}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentOperatorConsolidationScorecardEngine;
if(global)global.BlueCurrentOperatorConsolidationScorecardEngine=BlueCurrentOperatorConsolidationScorecardEngine;
})(typeof window!=="undefined"?window:globalThis);