(function(global){"use strict";
class BlueCurrentOperatorConsolidationEngine{
  constructor({eventBus,appState,rationalizationEngine}={}){this.eventBus=eventBus;this.appState=appState;this.rationalizationEngine=rationalizationEngine||null;this.roleDefaults={
    manager:["unifiedCommandCenter","guidedShiftCenter","operatorServiceFlowCenter","operatorCopilotCenter","commandActionInboxCenter","shiftProfitPulseCenter","operationsWorkspaceCenter","reservationOperationsCenter","liveFloorOperationsCenter","kitchenThroughputCenter","laborDeploymentCenter","guestRecoveryCenter"],
    executive:["unifiedCommandCenter","shiftProfitPulseCenter","executiveBriefingCenter","portfolioPerformanceCenter","marginIntelligenceCenter","enterpriseValuePlanCenter"],
    technical:["unifiedCommandCenter","operatorSurfaceRationalizationCenter","platformIntegrationAudit","runtimeReadinessCenter","aipRuntimeReadinessCenter","observabilityDashboard","releaseCertificationCenter"]
  };this.mergeMap=this.rationalizationEngine?.mergeTargets||{};}
  state(){try{return this.appState?.getState?.()||{};}catch{return {};}}
  role(){const s=this.state();return s.roleExperienceRole||s.unifiedCommandRole||"manager";}
  defaultSurfaces(role=this.role()){return [...(this.roleDefaults[role]||this.roleDefaults.manager)];}
  mergedSummary(target,state=this.state()){
    const sources=Object.entries(this.mergeMap).filter(([,t])=>t===target).map(([s])=>s);
    const sourceStates=sources.map(id=>({id,key:id.replace(/Center$/,""),value:state[id.replace(/Center$/,"")]||state[id]})).filter(x=>x.value!=null);
    const primaryKey=target.replace(/Center$/,""),primary=state[primaryKey]||state[target]||null;
    const headlines=[];if(primary?.headline)headlines.push(primary.headline);
    for(const x of sourceStates){if(x.value?.headline&&!headlines.includes(x.value.headline))headlines.push(x.value.headline);}
    return {target,sources,availableSources:sourceStates.map(x=>x.id),headline:headlines.slice(0,3).join(" · ")||null,primaryPresent:Boolean(primary),mergedSignalCount:(primary?1:0)+sourceStates.length};
  }
  consolidatedPrimary(){const state=this.state();const role=this.role();return this.defaultSurfaces(role).map(id=>({id,role,summary:this.mergedSummary(id,state)}));}
  evidence(){const s=this.state(),items=Array.isArray(s.operatorUseEvidence)?s.operatorUseEvidence:[];return items.slice(0,500);}
  recordUse(surfaceId,action="open",metadata={}){if(!surfaceId)return null;const s=this.state(),items=Array.isArray(s.operatorUseEvidence)?s.operatorUseEvidence:[],entry={id:`OUE-${Date.now().toString(36).toUpperCase()}`,surfaceId,action,role:this.role(),at:new Date().toISOString(),metadata};const next=[entry,...items].slice(0,500);this.appState?.update?.({operatorUseEvidence:next});this.eventBus?.emit?.("operator-use-evidence:recorded",structuredClone(entry));return entry;}
  resolvePrimarySurface(surfaceId){return this.mergeMap[surfaceId]||surfaceId;}
  recordTaskStart(surfaceId,taskId,metadata={}){const primary=this.resolvePrimarySurface(surfaceId);return this.recordUse(primary,"task-started",{taskId:String(taskId||"task"),sourceSurface:surfaceId,...metadata});}
  recordTaskCompletion(surfaceId,taskId,outcome="completed",metadata={}){const primary=this.resolvePrimarySurface(surfaceId),task=String(taskId||"task"),prior=this.evidence().find(x=>x.surfaceId===primary&&x.action==="task-started"&&x.metadata?.taskId===task),completedAt=new Date(),startedAt=metadata.startedAt||prior?.at||null,durationMs=startedAt?Math.max(0,completedAt.getTime()-new Date(startedAt).getTime()):null,entry=this.recordUse(primary,"task-completed",{taskId:task,outcome,sourceSurface:surfaceId,startedAt,durationMs,...metadata});this.eventBus?.emit?.("operator-task-completion:recorded",{surfaceId:primary,sourceSurface:surfaceId,taskId:task,outcome,durationMs});return entry;}
  taskMetrics(){const events=this.evidence(),roles={};for(const e of events.filter(x=>x.action==="task-completed")){const role=e.role||"unknown";roles[role] ||= {role,total:0,succeeded:0,failed:0,durations:[]};roles[role].total++;const outcome=String(e.metadata?.outcome||"completed").toLowerCase();if(["completed","success","resolved","approved"].includes(outcome))roles[role].succeeded++;else roles[role].failed++;if(Number.isFinite(Number(e.metadata?.durationMs)))roles[role].durations.push(Number(e.metadata.durationMs));}return Object.values(roles).map(x=>({...x,successRate:x.total?Math.round(100*x.succeeded/x.total):0,averageResolutionMs:x.durations.length?Math.round(x.durations.reduce((a,b)=>a+b,0)/x.durations.length):null}));}
  evidenceThresholds(){return {minimumObservedDays:3,minimumOpenEvents:3,minimumTaskCompletions:1,minimumDistinctRoles:1,minimumPrimaryWorkflowCoverage:100,minimumPreviewSnapshots:3,minimumTaskSuccessRate:95,maximumAverageResolutionMinutes:15,manifestValidityHours:72,automaticDeletion:false,version:"46.30.0"};}
  evidenceSummary(ids=null){const evidence=this.evidence(),scope=Array.isArray(ids)?ids:[...new Set(evidence.map(x=>x.surfaceId))];return scope.map(id=>{const hits=evidence.filter(x=>x.surfaceId===id),roles=[...new Set(hits.map(x=>x.role))];return {surfaceId:id,uses:hits.length,lastUsedAt:hits[0]?.at||null,roles,hasEvidence:hits.length>0};}).sort((a,b)=>b.uses-a.uses);}
  deprecationEvidence(ids=[]){const audit=this.rationalizationEngine?.snapshot?.(ids)||{items:ids.map(id=>({id,disposition:"supporting"}))};const usage=new Map(this.evidenceSummary(ids).map(x=>[x.surfaceId,x]));return audit.items.filter(x=>x.disposition==="deprecation-candidate").map(item=>{const u=usage.get(item.id)||{uses:0,lastUsedAt:null,roles:[]};return {...item,usage:u,recommendation:u.uses===0?"evidence-needed":u.uses<=1?"retain-until-more-evidence":"retain-active-use"};});}
  navigationModel(role=this.role()){const defaults=this.defaultSurfaces(role);return {role,defaultSurfaces:defaults,count:defaults.length,duplicateEntryPolicy:"merge-entry-points-into-primary-targets",fallback:"full-platform",version:"46.30.0"};}
  snapshot(){const rational=this.rationalizationEngine?.snapshot?.()||null,role=this.role(),defaults=this.defaultSurfaces(role),primary=this.consolidatedPrimary(),evidence=this.evidence(),deprecation=rational?this.deprecationEvidence(rational.items.map(x=>x.id)):[];return {capturedAt:new Date().toISOString(),role,navigation:this.navigationModel(role),primary,mergedPrimaryCount:primary.filter(x=>x.summary.sources.length>0).length,evidenceCount:evidence.length,evidenceSummary:this.evidenceSummary(),deprecationCandidates:deprecation,deprecationReady:deprecation.filter(x=>x.recommendation!=="evidence-needed").length,policy:"merge-before-delete-and-require-use-evidence",thresholds:this.evidenceThresholds(),version:"46.30.0"};}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentOperatorConsolidationEngine;
if(global)global.BlueCurrentOperatorConsolidationEngine=BlueCurrentOperatorConsolidationEngine;
})(typeof window!=="undefined"?window:globalThis);