(function(){"use strict";
class BlueCurrentOperationsWorkspaceEngine{
 constructor({eventBus,appState}){this.eventBus=eventBus;this.appState=appState;this.off=[];this.samples=[];this.startedAt=performance.now();this.stateEvents=0;this.lastSampleAt=performance.now();this.lastSnapshot=null;this.off.push(eventBus.on("state:updated",()=>{this.stateEvents+=1;}));this.timer=window.setInterval(()=>this.sample(),1000);this.sample();}
 sample(){const now=performance.now(),elapsed=Math.max(.25,(now-this.lastSampleAt)/1000),rate=this.stateEvents/elapsed;this.stateEvents=0;this.lastSampleAt=now;this.samples.push(rate);this.samples=this.samples.slice(-30);this.lastSnapshot=this.snapshot();this.eventBus.emit("operations-workspace:pulse",this.lastSnapshot);return this.lastSnapshot;}
 modules(){const names=["operationsWorkspace","shiftIntelligence","executiveDecisionFeed","operationsCopilot"];const constructors=["BlueCurrentOperationsWorkspaceEngine","BlueCurrentShiftIntelligenceEngine","BlueCurrentExecutiveDecisionFeedEngine","BlueCurrentOperationsCopilotEngine"];const centers=["operationsWorkspaceCenter","shiftIntelligenceCenter","executiveDecisionFeedCenter","operationsCopilotCenter"];return centers.map((id,i)=>({id,label:names[i].replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase()),script:typeof window[constructors[i]]==="function",center:Boolean(document.getElementById(id)),active:window.BlueCurrentActivatedCenters?.has(id)||id==="operationsWorkspaceCenter"}));}
 snapshot(){const modules=this.modules(),ready=modules.filter(m=>m.script&&m.center&&m.active).length;const boot=window.BlueCurrentBootReport||{};const avg=this.samples.length?this.samples.reduce((a,b)=>a+b,0)/this.samples.length:0;const latest=this.appState.get("shiftIntelligence")||{};return{capturedAt:new Date().toISOString(),modules,ready,total:modules.length,bootMs:Number(boot.durationMs)||Math.round(performance.now()-this.startedAt),stateRate:Number(avg.toFixed(1)),status:ready===modules.length?"ready":ready>=3?"degraded":"starting",topAction:latest.topAction||null,shiftScore:Number(latest.score)||0};}
 refresh(){return this.sample();}
 destroy(){this.off.forEach(fn=>fn?.());window.clearInterval(this.timer);}
}
window.BlueCurrentOperationsWorkspaceEngine=BlueCurrentOperationsWorkspaceEngine;})();
