(function(){"use strict";
function createBlueCurrentPilotValueScorecardCenterModule(eventBus,appState){const root=document.getElementById("pilotValueScorecard");if(!root||!window.BlueCurrentPilotValueScorecardEngine)return null;const e=new window.BlueCurrentPilotValueScorecardEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c])),money=n=>`$${Number(n||0).toLocaleString()}`;
function render(s){const c=s.current||{},ev=s.evidence||{},sc=s.scorecard||{};$("pvsStatus").textContent=s.status==="pilot-active"?"ACTIVE":"BASELINE";$("pvsOverall").textContent=sc.overall==null?"—":`${sc.overall}`;$("pvsVerified").textContent=money(ev.verifiedRealizedImpactDollars||0);$("pvsLeakage").textContent=ev.modeledLeakageReductionPercent==null?"—":`${ev.modeledLeakageReductionPercent}%`;$("pvsReadiness").textContent=ev.readinessDeltaPoints==null?"—":`${ev.readinessDeltaPoints>=0?"+":""}${ev.readinessDeltaPoints}`;$("pvsRhythm").textContent=ev.rhythmDeltaPoints==null?"—":`${ev.rhythmDeltaPoints>=0?"+":""}${ev.rhythmDeltaPoints}`;$("pvsHeadline").textContent=s.headline||"Capture the pilot baseline before claiming value.";
$("pvsScores").innerHTML=s.scorecard?`<article><small>Adoption</small><strong>${sc.adoption}</strong></article><article><small>Operating</small><strong>${sc.operating}</strong></article><article><small>Value evidence</small><strong>${sc.value}</strong></article><article><small>Targets met</small><strong>${sc.targetsMet}/${sc.targetsMeasured}</strong></article>`:"";
$("pvsEvidence").innerHTML=s.evidence?`<article><strong>Verified action value</strong><span>${money(ev.verifiedRealizedImpactDollars)} measured from completed Blue Current action outcomes.</span></article><article><strong>Observed leakage movement</strong><span>${money(ev.modeledLeakageReductionDollars)} reduction · ${ev.modeledLeakageReductionPercent}%.</span></article><article><strong>Observed contribution movement</strong><span>${money(ev.controllableContributionDeltaDollars)} delta from baseline.</span></article><article><strong>Attribution boundary</strong><span>${esc(ev.attribution.caveat)}</span></article>`:"<article><strong>No baseline yet.</strong><span>Start the pilot baseline before using this scorecard to discuss value.</span></article>";
$("pvsPortfolio").innerHTML=`<article><small>Locations</small><strong>${c.locations||0}</strong></article><article><small>Current readiness</small><strong>${c.averageReadiness||0}</strong></article><article><small>Current rhythm</small><strong>${c.averageRhythmScore||0}%</strong></article><article><small>Current contribution</small><strong>${money(c.controllableContributionDollars||0)}</strong></article><article><small>Current leakage</small><strong>${money(c.modeledLeakageDollars||0)}</strong></article>`;
$("pvsProgram").textContent=s.program?`${s.program.name} · Sponsor ${s.program.sponsor} · Day ${s.program.ageDays} of ${s.program.pilotDays} · ${s.program.checkpointCount} checkpoint(s)`:"No active pilot baseline.";}
async function load(){try{$("pvsHeadline").textContent="Building the pilot value scorecard…";render(await e.snapshot());}catch(err){$("pvsHeadline").textContent=err.message;}}
$("pvsRefresh")?.addEventListener("click",load);
$("pvsBaseline")?.addEventListener("click",async()=>{try{await e.baseline({name:$("pvsName").value||"Blue Current Pilot",sponsor:$("pvsSponsor").value||"Executive Sponsor",pilotDays:Number($("pvsDays").value||30)});await load();}catch(err){$("pvsHeadline").textContent=err.message;}});
$("pvsCheckpoint")?.addEventListener("click",async()=>{try{await e.checkpoint($("pvsNote").value||"");await load();}catch(err){$("pvsHeadline").textContent=err.message;}});
["hospitality-action:updated","hospitality-outcome:measured","manager-rhythm:closeout","multi-location-performance:updated","auth:restored"].forEach(evt=>eventBus?.on?.(evt,load));window.addEventListener?.("online",load);load();return{engine:e,load};}
window.createBlueCurrentPilotValueScorecardCenterModule=createBlueCurrentPilotValueScorecardCenterModule;})();