(function(){"use strict";
function createBlueCurrentRepositoryImpactCertificationCenterModule(eventBus,appState){const root=document.getElementById("repositoryImpactCertificationCenter");if(!root||!window.BlueCurrentRepositoryImpactCertificationEngine)return null;const e=new window.BlueCurrentRepositoryImpactCertificationEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));let impact=null,plan=null;
function candidates(){return (appState.getState?.().operatorRetirementCertifications||[]).filter(x=>x.status==="retirement-candidate-certified");}
function options(){const items=candidates(),cur=$("oricSurface").value;$("oricSurface").innerHTML=items.map(x=>`<option value="${esc(x.surfaceId)}">${esc(x.surfaceId)}</option>`).join("");if(items.some(x=>x.surfaceId===cur))$("oricSurface").value=cur;}
function render(){options();const snap=e.snapshot(),r=plan?e.readiness(plan):snap.readiness;$("oricPlans").textContent=snap.count;$("oricOwned").textContent=impact?.impact?.ownedFiles||0;$("oricInbound").textContent=impact?.impact?.inboundReferences||0;$("oricStartup").textContent=impact?.impact?.startupDependencies||0;$("oricApi").textContent=impact?.impact?.apiReferences||0;$("oricTests").textContent=impact?.impact?.testReferences||0;$("oricScore").textContent=`${r?.score||0}%`;$("oricStatus").textContent=r?.status||"—";$("oricHeadline").textContent=impact?`${impact.surfaceId} · ${impact.status} · ${(impact.blockers||[]).length} blocker(s) · deletion disabled`:"Select a certified retirement candidate and analyze repository impact.";$("oricImpact").innerHTML=impact?`<article><strong>Owned files</strong><span>${(impact.graph.ownedFiles||[]).map(esc).join(", ")||"none"}</span></article><article><strong>Inbound references</strong><span>${(impact.graph.inboundReferences||[]).map(x=>`${esc(x.file)} (${x.count})`).join(", ")||"none"}</span></article><article><strong>Rollback digest</strong><span>${esc(impact.rollback?.digest||"—")}</span></article>`:"";$("oricChecks").innerHTML=(r?.checks||[]).map(x=>`<article><strong>${x.pass?"PASS":"BLOCK"} · ${esc(x.id)}</strong><span>${esc(x.detail)}</span></article>`).join("");}
$("oricAnalyze")?.addEventListener("click",async()=>{try{impact=await e.analyze($("oricSurface").value);plan=null;render();}catch(err){$("oricHeadline").textContent=err.message;}});
$("oricPlan")?.addEventListener("click",()=>{try{plan=e.buildPlan(impact);render();}catch(err){$("oricHeadline").textContent=err.message;}});
$("oricAuthorize")?.addEventListener("click",()=>{try{if(!plan)throw new Error("Build a deletion plan first.");plan=e.authorize(plan.id,$("oricAuthorizer").value||"Operator",$("oricNote").value||"");render();}catch(err){$("oricHeadline").textContent=err.message;}});
$("oricRefresh")?.addEventListener("click",render);render();return{engine:e,render};}
window.createBlueCurrentRepositoryImpactCertificationCenterModule=createBlueCurrentRepositoryImpactCertificationCenterModule;})();