(function(){"use strict";
function createBlueCurrentRestaurantWorkflowIntegrationCenterModule(eventBus,appState){
 const root=document.getElementById("v5325RestaurantWorkflowIntegration");if(!root||!window.BlueCurrentRestaurantWorkflowIntegrationEngine)return null;
 const e=new window.BlueCurrentRestaurantWorkflowIntegrationEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
 function render(s){$("v5325Status").textContent=s.status||"—";$("v5325Ready").textContent=`${(s.locations||[]).filter(x=>x.workflowReady).length}/${(s.locations||[]).length}`;$("v5325Findings").textContent=(s.locations||[]).reduce((n,x)=>n+x.highCriticalFindings.length,0);$("v5325Headline").textContent=s.headline||"Restaurant workflow integration unavailable.";$("v5325Locations").innerHTML=(s.locations||[]).map(x=>`<article data-v5325-location="${esc(x.locationId)}"><strong>${esc(x.locationName)}</strong><span>${esc(x.state)} · ${x.passed}/${x.total} gates · high/critical ${x.highCriticalFindings.length}</span><div class="v432-list">${x.checks.map(c=>`<article><strong>${c.passed?"PASS":"OPEN"} · ${esc(c.id)}</strong><span>${esc(c.actual)}</span></article>`).join("")}</div><div class="v4316-actions"><button data-v5325-observe="true">Record end-to-end observation</button>${x.workflowReady&&!x.certification?'<button data-v5325-certify="true">Certify workflow</button>':""}</div></article>`).join("");}
 async function load(){try{render(await e.snapshot());}catch(err){$("v5325Headline").textContent=err.message;}}
 root.addEventListener("click",async ev=>{const card=ev.target.closest("[data-v5325-location]");if(!card)return;try{if(ev.target.closest("[data-v5325-observe]"))await e.observe(card.dataset.v5325Location,{handoffContinuity:$("v5325Handoff").value,shiftCompletion:$("v5325Completion").value,failureRecoveryEvidence:$("v5325Recovery").value,operatorEvidence:$("v5325Operator").value,note:$("v5325Note").value,findings:[]});else if(ev.target.closest("[data-v5325-certify]"))await e.certify(card.dataset.v5325Location,{evidence:$("v5325CertEvidence").value,note:$("v5325CertNote").value});await load();}catch(err){$("v5325Headline").textContent=err.message;}});
 $("v5325Refresh")?.addEventListener("click",load);load();return{engine:e,load};
}
window.createBlueCurrentRestaurantWorkflowIntegrationCenterModule=createBlueCurrentRestaurantWorkflowIntegrationCenterModule;})();