(function(global){"use strict";
class BlueCurrentRetirementCertificationEngine{
  constructor({eventBus,appState,consolidationEngine,manifestEngine,scorecardEngine}={}){this.eventBus=eventBus;this.appState=appState;this.consolidationEngine=consolidationEngine;this.manifestEngine=manifestEngine;this.scorecardEngine=scorecardEngine;}
  state(){try{return this.appState?.getState?.()||{};}catch{return {};}}
  thresholds(){return this.consolidationEngine?.evidenceThresholds?.()||{};}
  observations(){const s=this.state();return Array.isArray(s.operatorRetirementPreviewEvidence)?s.operatorRetirementPreviewEvidence:[];}
  recordObservation(surfaceId,{workflowCoverage=null,taskFailures=0,regressions=0,note="",at=null}={}){const manifest=this.manifestEngine?.manifest?.()||{},item=(manifest.items||[]).find(x=>x.surfaceId===surfaceId);if(!item||!item.featureFlag)throw new Error("Surface must be in an enabled hide preview before observation.");const coverage=workflowCoverage??this.scorecardEngine?.workflowCoverage?.("manager")?.percent??0,entry={id:`ORP-${Date.now().toString(36).toUpperCase()}`,surfaceId,at:at||new Date().toISOString(),workflowCoverage:Number(coverage),taskFailures:Number(taskFailures||0),regressions:Number(regressions||0),note:String(note||"").slice(0,500),previewHidden:true};const next=[entry,...this.observations()].slice(0,500);this.appState?.update?.({operatorRetirementPreviewEvidence:next});this.eventBus?.emit?.("operator-retirement-preview:observed",structuredClone(entry));return entry;}
  ownerSignoff(surfaceId,owner,decision="approve",note=""){const manifest=this.manifestEngine?.manifest?.()||{},items=(manifest.items||[]).map(x=>x.surfaceId===surfaceId?{...x,ownerSignoff:{owner:String(owner||"Owner"),decision:String(decision),note:String(note||"").slice(0,500),at:new Date().toISOString()}}:x);if(!items.some(x=>x.surfaceId===surfaceId))throw new Error("Surface is not in the manifest.");const next={...manifest,items};this.appState?.update?.({operatorDeprecationManifest:next});this.eventBus?.emit?.("operator-deprecation-manifest:updated",structuredClone(next));return next.items.find(x=>x.surfaceId===surfaceId).ownerSignoff;}
  taskQuality(){const metrics=this.consolidationEngine?.taskMetrics?.()||[];const total=metrics.reduce((s,x)=>s+x.total,0),succeeded=metrics.reduce((s,x)=>s+x.succeeded,0),failed=metrics.reduce((s,x)=>s+x.failed,0),durations=metrics.filter(x=>Number.isFinite(x.averageResolutionMs)&&x.total>0);const avg=durations.length?Math.round(durations.reduce((s,x)=>s+x.averageResolutionMs*x.total,0)/durations.reduce((s,x)=>s+x.total,0)):null;return {byRole:metrics,total,succeeded,failed,successRate:total?Math.round(100*succeeded/total):100,averageResolutionMs:avg,averageResolutionMinutes:avg==null?null:Math.round(avg/600)/100};}
  surfaceCertification(surfaceId){const t=this.thresholds(),manifest=this.manifestEngine?.manifest?.()||{},item=(manifest.items||[]).find(x=>x.surfaceId===surfaceId),obs=this.observations().filter(x=>x.surfaceId===surfaceId),days=[...new Set(obs.map(x=>String(x.at).slice(0,10)))],quality=this.taskQuality(),coverage=this.scorecardEngine?.workflowCoverage?.("manager")||{percent:0},signoff=item?.ownerSignoff||null,checks=[
    {id:"manifest-approved",pass:manifest.status==="approved"&&item?.approved===true,detail:manifest.status||"no manifest"},
    {id:"manifest-valid",pass:manifest.revalidationStatus==="valid"&&(!manifest.expiresAt||new Date(manifest.expiresAt).getTime()>Date.now()),detail:manifest.revalidationStatus||"not revalidated"},
    {id:"preview-enabled",pass:item?.featureFlag===true,detail:item?.featureFlag?"hidden preview active":"preview not active"},
    {id:"observation-days",pass:days.length>=Number(t.minimumObservedDays||3),detail:`${days.length}/${t.minimumObservedDays||3} observed day(s)`},
    {id:"preview-snapshots",pass:obs.length>=Number(t.minimumPreviewSnapshots||3),detail:`${obs.length}/${t.minimumPreviewSnapshots||3} preview observation(s)`},
    {id:"workflow-coverage",pass:coverage.percent>=Number(t.minimumPrimaryWorkflowCoverage||100)&&obs.every(x=>x.workflowCoverage>=Number(t.minimumPrimaryWorkflowCoverage||100)),detail:`${coverage.percent}% current coverage`},
    {id:"regressions",pass:obs.every(x=>x.regressions===0&&x.taskFailures===0),detail:`${obs.reduce((s,x)=>s+x.regressions+x.taskFailures,0)} preview failure/regression signal(s)`},
    {id:"task-success",pass:quality.successRate>=Number(t.minimumTaskSuccessRate||95),detail:`${quality.successRate}% task success`},
    {id:"time-to-resolution",pass:quality.averageResolutionMinutes==null||quality.averageResolutionMinutes<=Number(t.maximumAverageResolutionMinutes||15),detail:quality.averageResolutionMinutes==null?"No duration evidence yet":`${quality.averageResolutionMinutes} min avg resolution`},
    {id:"owner-signoff",pass:signoff?.decision==="approve",detail:signoff?`${signoff.owner} · ${signoff.decision}`:"Owner sign-off missing"}
  ];const eligible=checks.every(x=>x.pass);return {surfaceId,eligible,status:eligible?"retirement-candidate":"preview-incomplete",checks,observedDays:days.length,observations:obs.length,taskQuality:quality,ownerSignoff:signoff,automaticDeletion:false};}
  candidateSet(){const manifest=this.manifestEngine?.manifest?.()||{},items=(manifest.items||[]).map(x=>this.surfaceCertification(x.surfaceId));return {items,eligible:items.filter(x=>x.eligible),eligibleCount:items.filter(x=>x.eligible).length,policy:"certify-retirement-never-auto-delete",automaticDeletion:false,version:"46.30.0"};}
  certify(surfaceId,certifier){const result=this.surfaceCertification(surfaceId);if(!result.eligible)throw new Error("Surface has not satisfied retirement certification.");const s=this.state(),certs=Array.isArray(s.operatorRetirementCertifications)?s.operatorRetirementCertifications:[],record={id:`ORC-${Date.now().toString(36).toUpperCase()}`,surfaceId,status:"retirement-candidate-certified",certifiedBy:String(certifier||"Operator"),certifiedAt:new Date().toISOString(),checks:result.checks,automaticDeletion:false,codeDeletionAllowed:false};const next=[record,...certs.filter(x=>x.surfaceId!==surfaceId)].slice(0,200);this.appState?.update?.({operatorRetirementCertifications:next});this.eventBus?.emit?.("operator-retirement-candidate:certified",structuredClone(record));return record;}
  snapshot(){const set=this.candidateSet(),s=this.state(),certs=Array.isArray(s.operatorRetirementCertifications)?s.operatorRetirementCertifications:[];return {candidateSet:set,certifications:certs,certifiedCount:certs.filter(x=>x.status==="retirement-candidate-certified").length,taskQuality:this.taskQuality(),policy:"certify-retirement-never-auto-delete",automaticDeletion:false,codeDeletionAllowed:false,version:"46.30.0"};}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentRetirementCertificationEngine;
if(global)global.BlueCurrentRetirementCertificationEngine=BlueCurrentRetirementCertificationEngine;
})(typeof window!=="undefined"?window:globalThis);