(function(){"use strict";
function createBlueCurrentSelectedCandidatePreviewCenterModule(eventBus,appState){const root=document.getElementById("selectedCandidatePreviewCenter");if(!root||!window.BlueCurrentSelectedCandidatePreviewEngine)return null;const rational=new window.BlueCurrentOperatorSurfaceRationalizationEngine({eventBus,appState}),consolidation=new window.BlueCurrentOperatorConsolidationEngine({eventBus,appState,rationalizationEngine:rational}),flow=new window.BlueCurrentOperatorServiceFlowEngine({eventBus,appState}),score=new window.BlueCurrentOperatorConsolidationScorecardEngine({eventBus,appState,consolidationEngine:consolidation,rationalizationEngine:rational,flowEngine:flow}),e=new window.BlueCurrentSelectedCandidatePreviewEngine({eventBus,appState,consolidationEngine:consolidation,scorecardEngine:score}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
function render(){const s=e.snapshot(),p=s.preview,r=s.readiness;$("candidatePreviewCandidate").textContent=p?.surfaceId||s.selection?.surfaceId||"NONE";$("candidatePreviewStatus").textContent=p?.status||"NOT STARTED";$("candidatePreviewObservations").textContent=r?.observations||0;$("candidatePreviewDays").textContent=r?.observedDays||0;$("candidatePreviewCoverage").textContent=`${r?.currentWorkflow?.percent??0}%`;$("candidatePreviewTaskSuccess").textContent=`${r?.taskQuality?.successRate??100}%`;$("candidatePreviewReady").textContent=r?.eligibleForCertification?"READY":"BLOCKED";$("candidatePreviewHeadline").textContent=p?`${p.surfaceId} · ${r.status} · reversible preview ${p.active?"ACTIVE":"RESTORED"}.`:(s.selection?`${s.selection.surfaceId} selected. Preview has not started.`:"Select a top-three candidate in the previous gate first.");$("candidatePreviewChecks").innerHTML=(r?.checks||[]).map(c=>`<article><strong>${c.pass?"PASS":"BLOCK"} · ${esc(c.id)}</strong><span>${esc(c.detail)}</span></article>`).join("");$("candidatePreviewEvidence").innerHTML=(s.observations||[]).slice(0,12).map(x=>`<article><strong>${esc(x.at)} · coverage ${x.workflowCoverage}%</strong><span>failures ${x.taskFailures} · regressions ${x.regressions} · task success ${x.taskSuccessRate}% · use ${x.operatorUseEvents}</span></article>`).join("")||"<p>No preview observations yet.</p>";}
$("candidatePreviewStart")?.addEventListener("click",()=>{try{e.begin();render();}catch(err){$("candidatePreviewHeadline").textContent=err.message;}});
$("candidatePreviewRestore")?.addEventListener("click",()=>{try{e.stop("operator restore");render();}catch(err){$("candidatePreviewHeadline").textContent=err.message;}});
$("candidatePreviewObserve")?.addEventListener("click",()=>{try{e.recordObservation({note:$("candidatePreviewNote").value||""});render();}catch(err){$("candidatePreviewHeadline").textContent=err.message;}});
$("candidatePreviewSignoff")?.addEventListener("click",()=>{try{e.ownerSignoff($("candidatePreviewOwner").value||"Owner","approve",$("candidatePreviewNote").value||"");render();}catch(err){$("candidatePreviewHeadline").textContent=err.message;}});
$("candidatePreviewImpact")?.addEventListener("click",async()=>{try{await e.refreshImpact();render();}catch(err){$("candidatePreviewHeadline").textContent=err.message;}});
$("candidatePreviewRefresh")?.addEventListener("click",render);eventBus?.on?.("operator-retirement-candidate:selected",render);render();return{engine:e,render};}
window.createBlueCurrentSelectedCandidatePreviewCenterModule=createBlueCurrentSelectedCandidatePreviewCenterModule;})();