"use strict";
const crypto=require("crypto");
const HOLIDAYS=Object.freeze({Thanksgiving:"2026-11-26","Christmas Eve":"2026-12-24","Christmas Day":"2026-12-25","New Year's Eve":"2026-12-31","New Year's Day":"2027-01-01"});
const fail=(status,message)=>{const e=new Error(message);e.statusCode=status;throw e;};
const timeMinutes=value=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(String(value||"")))return NaN;const [h,m]=value.split(":").map(Number);return h*60+m;};
class HarborPointLiveService{
 constructor(database,operations,floorService,auditService,realtimeHub){Object.assign(this,{database,operations,floorService,auditService,realtimeHub});}
 async assess(org,allowed){const db=await this.database.read(),config=db.harborPointLiveConfigs?.[org]||null,blocking=[];if(!config)blocking.push("Manager configuration is required");
 const location=(db.locations||[]).find(l=>l.id===config?.locationId&&l.organizationId===org);
 if(!location||!(allowed.includes("*")||allowed.includes(location.id)))blocking.push("Dedicated location and access must be configured");
 if(config?.dataBoundary!=="DEDICATED_ORGANIZATION"||!(db.organizations||[]).some(o=>o.id===org&&o.dedicatedForHarborPoint===true)||(db.locations||[]).filter(l=>l.organizationId===org).length!==1)blocking.push("A separate Harbor Point organization with one venue must be provisioned");
 if(!config?.venueName||config.venueName!==location?.name)blocking.push("Official venue name must match the configured location");
 const events=config?.events||[];
 if(events.length!==Object.keys(HOLIDAYS).length||new Set(events.map(e=>e.name)).size!==events.length)blocking.push("Exactly the five approved holiday events are required");
 for(const [name,date] of Object.entries(HOLIDAYS)){const e=events.find(x=>x.name===name&&x.date===date);if(!e||!Number.isInteger(e.maxCoversPerSlot)||e.maxCoversPerSlot<1||![5,10,15,20,30,60].includes(e.incrementMinutes)||!(timeMinutes(e.firstSeating)<timeMinutes(e.lastSeating)))blocking.push(`${name} hours and slot limits require approval`);}
 const tables=(db.tables||[]).filter(t=>t.organizationId===org&&t.locationId===location?.id&&config?.tableIds?.includes(t.id));
 if(!config?.tableIds?.length||tables.length!==config.tableIds.length||tables.some(t=>!Number.isInteger(Number(t.seats))||Number(t.seats)<1))blocking.push("Approved table inventory and capacities are required");
 if(Number.isInteger(config?.maxPartySize)&&tables.length&&config.maxPartySize>Math.max(...tables.map(t=>Number(t.seats))))blocking.push("Maximum party size must fit an approved table");
 if(!Number.isInteger(config?.maxPartySize)||config.maxPartySize<1||!Number.isInteger(config?.graceMinutes)||config.graceMinutes<0)blocking.push("Party and late-arrival limits are required");
 for(const key of ["largePartyPolicy","cancellationPolicy","noShowPolicy","overbookingPolicy","accessibleTablePolicy","combineTablePolicy","seatingDurationPolicy","printerBackupProcedure","escalationContact","currentWaitlistProduct"]){if(!String(config?.[key]||"").trim())blocking.push(`${key} requires venue confirmation`);}
 const approvedHosts=config?.hostAccounts||[];const memberships=db.memberships||[],users=db.users||[];
 if(!Array.isArray(approvedHosts)||!approvedHosts.length||!String(config?.managerName||"").trim()||approvedHosts.some(email=>!users.some(u=>u.email?.toLowerCase()===String(email).toLowerCase()&&memberships.some(m=>m.userId===u.id&&m.organizationId===org&&["host","manager","owner","admin"].includes(m.role)&&(m.locationIds||[]).some(id=>id===location?.id||id==="*")))))blocking.push("Manager and location-scoped host accounts require approval");
 for(const key of ["mockDayPassed","ipadAccepted","backupRecoveryVerified"]){if(config?.checks?.[key]!==true)blocking.push(`${key} acceptance is required`);}
 if(!config?.activation?.approvedAt||!config?.activation?.approvedBy)blocking.push("Manager activation is required");
 return {readiness:blocking.length?"HOLD":"ACTIVE",blocking,config,location,tables,events};}
 async configure(org,input,actor){if(!input||typeof input!=="object"||Array.isArray(input))fail(400,"Configuration object required.");const allowedKeys=["locationId","venueName","dataBoundary","events","tableIds","maxPartySize","graceMinutes","largePartyPolicy","cancellationPolicy","noShowPolicy","overbookingPolicy","accessibleTablePolicy","combineTablePolicy","seatingDurationPolicy","printerBackupProcedure","escalationContact","currentWaitlistProduct","hostAccounts","managerName","checks"];
 const cfg=Object.fromEntries(allowedKeys.filter(k=>Object.hasOwn(input,k)).map(k=>[k,input[k]]));cfg.activation=null;cfg.updatedBy=actor;cfg.updatedAt=new Date().toISOString();
 await this.database.mutate(db=>{db.harborPointLiveConfigs||={};db.harborPointLiveConfigs[org]=cfg;return true;});return this.assess(org,["*"]);}
 async activate(org,allowed,actor,approval){if(approval?.confirmation!=="APPROVE HARBOR POINT LIVE BOOKINGS")fail(400,"Explicit manager confirmation is required.");const before=await this.assess(org,allowed);const pending=before.blocking.filter(x=>x!=="Manager activation is required");if(pending.length)fail(409,`Live activation blocked: ${pending.join("; ")}`);
 await this.database.mutate(db=>{const cfg=db.harborPointLiveConfigs?.[org];if(!cfg)fail(409,"Configuration missing.");cfg.activation={approvedAt:new Date().toISOString(),approvedBy:actor};return true;});return this.assess(org,allowed);}
 async snapshot(org,allowed){const status=await this.assess(org,allowed);if(status.readiness!=="ACTIVE")return {readiness:"HOLD",blocking:status.blocking};const db=await this.database.read(),locationId=status.location.id;
 const slotUsage={};for(const r of db.reservations||[]){if(r.organizationId!==org||r.locationId!==locationId||["cancelled","canceled"].includes(String(r.status||"").toLowerCase()))continue;const at=new Date(r.reservationTime);if(Number.isNaN(at.getTime()))continue;const local=new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(at);const part=k=>local.find(x=>x.type===k)?.value;const key=`${part("year")}-${part("month")}-${part("day")}T${part("hour")}:${part("minute")}`;slotUsage[key]=(slotUsage[key]||0)+Number(r.partySize||0);}
 return {readiness:"ACTIVE",location:{id:locationId,name:status.location.name},events:status.events,slotUsage,maxPartySize:status.config.maxPartySize,reservations:(db.reservations||[]).filter(r=>r.organizationId===org&&r.locationId===locationId&&r.source==="Harbor Point Phone"),tables:status.tables.map(t=>(db.tables||[]).find(x=>x.id===t.id&&x.organizationId===org))};}
 async requireActive(org,allowed){const status=await this.assess(org,allowed);if(status.readiness!=="ACTIVE")fail(423,"Harbor Point live bookings are on HOLD: "+status.blocking.join("; "));return status;}
 async create(org,allowed,input,actor){const gate=await this.requireActive(org,allowed);const name=String(input.guestName||"").trim(),phone=String(input.phone||"").replace(/\D/g,""),event=gate.events.find(e=>e.name===input.holidayEvent),time=String(input.time||""),size=Number(input.partySize);
 if(name.length<2||name.length>100||!/^[0-9]{10}$/.test(phone)||!Number.isInteger(size)||size<1||size>gate.config.maxPartySize||!event)fail(400,"Enter a guest name, ten-digit phone, valid party size, and configured holiday.");
 const start=timeMinutes(event.firstSeating),end=timeMinutes(event.lastSeating),chosen=timeMinutes(time);if(!Number.isFinite(chosen)||chosen<start||chosen>end||(chosen-start)%event.incrementMinutes!==0)fail(400,"Choose a configured reservation time.");
 const at=`${event.date}T${time}:00-05:00`;
 const result=await this.database.transaction(tx=>{const existing=tx.list("reservations").filter(r=>r.organizationId===org&&r.locationId===gate.location.id&&new Date(r.reservationTime).getTime()===new Date(at).getTime()&&!['cancelled','canceled'].includes(String(r.status||'').toLowerCase()));
 if(existing.some(r=>String(r.phone||'').replace(/\D/g,'')===phone))fail(409,"A booking already exists for this phone and time.");
 if(existing.reduce((sum,r)=>sum+Number(r.partySize||0),0)+size>event.maxCoversPerSlot)fail(409,"This time has reached its approved cover limit.");
 const now=new Date().toISOString(),row={id:`res_${crypto.randomUUID()}`,organizationId:org,locationId:gate.location.id,guestName:name,phone,partySize:size,reservationTime:at,holidayEvent:event.name,status:"confirmed",tableId:null,source:"Harbor Point Phone",seatingPreference:String(input.seatingPreference||"Flexible").slice(0,80),specialOccasion:String(input.specialOccasion||"").slice(0,120),accessibility:String(input.accessibility||"").slice(0,240),notes:String(input.notes||"").slice(0,500),createdAt:now,updatedAt:now,createdBy:actor};tx.create("reservations",row);return row;},{domain:"reservations",operation:"harbor-point-live-booking",organizationId:org});
 await this.auditService.record({organizationId:org,actor,action:`Harbor Point booking created for ${result.guestName}`,category:"reservation"});this.realtimeHub.publish("reservation:created",result);return result;}
 async edit(org,allowed,id,input,actor){const gate=await this.requireActive(org,allowed),name=String(input.guestName||"").trim(),phone=String(input.phone||"").replace(/\D/g,""),event=gate.events.find(e=>e.name===input.holidayEvent),time=String(input.time||""),size=Number(input.partySize);
 if(name.length<2||name.length>100||!/^[0-9]{10}$/.test(phone)||!Number.isInteger(size)||size<1||size>gate.config.maxPartySize||!event)fail(400,"Enter a guest name, ten-digit phone, valid party size, and configured holiday.");
 const first=timeMinutes(event.firstSeating),last=timeMinutes(event.lastSeating),selected=timeMinutes(time);if(!Number.isFinite(selected)||selected<first||selected>last||(selected-first)%event.incrementMinutes!==0)fail(400,"Choose a configured reservation time.");const at=`${event.date}T${time}:00-05:00`;
 const result=await this.database.transaction(tx=>{const row=tx.get("reservations",id);if(!row||row.organizationId!==org||row.locationId!==gate.location.id||row.source!=="Harbor Point Phone")fail(404,"Booking not found.");if(!["confirmed","arrived"].includes(row.status))fail(409,"This booking cannot be edited.");const sameSlot=tx.list("reservations").filter(r=>r.id!==id&&r.organizationId===org&&r.locationId===gate.location.id&&new Date(r.reservationTime).getTime()===new Date(at).getTime()&&!['cancelled','canceled'].includes(String(r.status||'').toLowerCase()));if(sameSlot.some(r=>String(r.phone||'').replace(/\D/g,'')===phone))fail(409,"A booking already exists for this phone and time.");if(sameSlot.reduce((sum,r)=>sum+Number(r.partySize||0),0)+size>event.maxCoversPerSlot)fail(409,"This time has reached its approved cover limit.");Object.assign(row,{guestName:name,phone,partySize:size,reservationTime:at,holidayEvent:event.name,seatingPreference:String(input.seatingPreference||"Flexible").slice(0,80),specialOccasion:String(input.specialOccasion||"").slice(0,120),accessibility:String(input.accessibility||"").slice(0,240),notes:String(input.notes||"").slice(0,500),updatedAt:new Date().toISOString(),updatedBy:actor});for(const w of tx.list("waitlist",w=>w.reservationId===id&&w.organizationId===org&&w.status==="waiting")){Object.assign(w,{guestName:name,phone,partySize:size,notes:row.notes,updatedAt:row.updatedAt});}return row;},{domain:"reservations",operation:"harbor-point-edit",organizationId:org});await this.auditService.record({organizationId:org,actor,action:`Harbor Point booking edited for ${result.guestName}`,category:"reservation"});this.realtimeHub.publish("reservation:updated",result);return result;}
 async action(org,allowed,input,actor){const gate=await this.requireActive(org,allowed),db=await this.database.read(),row=(db.reservations||[]).find(r=>r.id===input.reservationId&&r.organizationId===org&&r.locationId===gate.location.id&&r.source==="Harbor Point Phone");if(!row)fail(404,"Booking not found.");const action=String(input.action||"");
 if(["arrive","cancel","waitlist"].includes(action)){const result=await this.database.transaction(tx=>{const current=tx.get("reservations",row.id);if(!current||current.organizationId!==org||current.locationId!==gate.location.id)fail(404,"Booking not found.");
 if(action==="arrive"){if(current.status!=="confirmed")fail(409,"Only confirmed guests can arrive.");current.status="arrived";current.arrivedAt=new Date().toISOString();}
 if(action==="cancel"){if(!["confirmed","arrived"].includes(current.status))fail(409,"This booking cannot be cancelled.");current.status="cancelled";for(const w of tx.list("waitlist",w=>w.reservationId===current.id&&w.organizationId===org&&w.status==="waiting")){w.status="cancelled";w.updatedAt=new Date().toISOString();}}
 if(action==="waitlist"){if(current.status!=="arrived")fail(409,"Only an arrived guest can join the waitlist.");if(tx.list("waitlist",w=>w.reservationId===current.id&&w.organizationId===org&&w.status==="waiting").length)fail(409,"Guest is already on the waitlist.");tx.create("waitlist",{id:`wait_${crypto.randomUUID()}`,organizationId:org,locationId:current.locationId,reservationId:current.id,guestName:current.guestName,phone:current.phone,partySize:current.partySize,quotedMinutes:0,status:"waiting",source:"Harbor Point arrival",createdAt:new Date().toISOString()});}
 current.updatedAt=new Date().toISOString();return current;},{domain:"reservations",operation:`harbor-point-${action}`,organizationId:org});await this.auditService.record({organizationId:org,actor,action:`Harbor Point booking ${action}: ${result.guestName}`,category:"reservation"});this.realtimeHub.publish("reservation:updated",result);return result;}
 if(action==="seat"){if(row.status!=="arrived")fail(409,"Mark the guest arrived before seating.");if(!gate.tables.some(t=>t.id===input.tableId))fail(400,"Choose an approved table.");const result=await this.operations.seat(row.id,input.tableId,actor,org);if(!result)fail(409,"Table or booking changed. Refresh and try again.");return result;}
 if(action==="complete"){const result=await this.operations.complete(row.id,actor,org);if(!result)fail(409,"Only seated service can complete.");return result;}
 fail(400,"Unknown booking action.");}
 async ready(org,allowed,tableId,actor){const gate=await this.requireActive(org,allowed);if(!gate.tables.some(t=>t.id===tableId))fail(400,"Choose an approved table.");const result=await this.database.transaction(tx=>{const table=tx.get("tables",tableId);if(!table||table.organizationId!==org||table.locationId!==gate.location.id||table.status!=="cleaning")fail(409,"Only a cleaning table can become available.");table.status="available";table.guestName="";table.partySize=0;table.reservationId=null;table.updatedAt=new Date().toISOString();return table;},{domain:"floor",operation:"harbor-point-ready",organizationId:org});await this.auditService.record({organizationId:org,actor,action:`Harbor Point table ${result.name} available`,category:"floor"});this.realtimeHub.publish("floor:table-updated",result);return result;}
}
module.exports={HarborPointLiveService,HOLIDAYS};
