"use strict";
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const HOLIDAYS=Object.freeze({Thanksgiving:"2026-11-26","Christmas Eve":"2026-12-24","Christmas Day":"2026-12-25","New Year's Eve":"2026-12-31","New Year's Day":"2027-01-01"});
const ROOMS=Object.freeze([{name:"Inlet Room",prefix:"I",count:6},{name:"Sunset Ballroom",prefix:"S",count:12}]);
const clone=value=>JSON.parse(JSON.stringify(value));
const error=(status,message,code)=>Object.assign(new Error(message),{statusCode:status,code});
class HarborPointDemoService{
  constructor(filePath){if(!filePath)throw new Error("A separate demo store path is required.");this.filePath=path.resolve(filePath);this.queue=Promise.resolve();if(!fs.existsSync(this.filePath)){const main=process.env.BLUE_CURRENT_DB&&path.resolve(process.env.BLUE_CURRENT_DB);if(main===this.filePath)throw new Error("Demo store must not use the primary database.");}}
  initial(){return {schema:1,version:0,mode:"FICTIONAL_DEMO_ONLY",rooms:ROOMS,tables:ROOMS.flatMap(room=>Array.from({length:room.count},(_,i)=>({id:`${room.prefix}${String(i+1).padStart(2,"0")}`,room:room.name,seats:4,status:"available",reservationId:null}))),reservations:[]};}
  async read(){try{return JSON.parse(await fs.promises.readFile(this.filePath,"utf8"));}catch(e){if(e.code==="ENOENT")return this.initial();throw e;}}
  async snapshot(){return clone(await this.read());}
  async change(expectedVersion,fn){const run=async()=>{const state=await this.read();if(!Number.isInteger(expectedVersion)||expectedVersion!==state.version)throw error(412,"The demo changed on another device. Refresh and try again.","STALE_DEMO_VERSION");const result=fn(state);state.version++;const temp=`${this.filePath}.${process.pid}.${crypto.randomUUID()}.tmp`;await fs.promises.mkdir(path.dirname(this.filePath),{recursive:true});try{await fs.promises.writeFile(temp,JSON.stringify(state),{flag:"wx",mode:0o600});await fs.promises.rename(temp,this.filePath);}finally{await fs.promises.rm(temp,{force:true}).catch(()=>{});}return {result:clone(result),version:state.version};};const next=this.queue.then(run,run);this.queue=next.catch(()=>{});return next;}
  async create(input){return this.change(input.version,state=>{const name=String(input.guestName||"").trim(),phone=String(input.phone||"").replace(/\D/g,""),event=String(input.holidayEvent||""),date=HOLIDAYS[event],time=String(input.time||"");const size=Number(input.partySize);if(!/^Demo [A-Za-z][A-Za-z0-9 .'-]{1,45}$/.test(name))throw error(400,"Use a fictional name beginning with Demo, such as Demo Guest 1.","INVALID_DEMO_NAME");if(!/^73255501\d\d$/.test(phone))throw error(400,"Use a 10-digit sample phone number such as 732-555-0123.","INVALID_DEMO_PHONE");if(!date||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)||!Number.isInteger(size)||size<1||size>4)throw error(400,"Choose a listed holiday, valid time, and party of 1 to 4.","INVALID_DEMO_BOOKING");if(state.reservations.some(r=>r.status!=="cancelled"&&r.phone===phone&&r.date===date&&r.time===time))throw error(409,"A booking with this sample phone, date, and time already exists.","DUPLICATE_DEMO_BOOKING");const now=new Date().toISOString(),row={id:`demo_${crypto.randomUUID()}`,guestName:name,phone,partySize:size,holidayEvent:event,date,time,notes:String(input.notes||"").slice(0,240),status:"confirmed",tableId:null,createdAt:now,updatedAt:now};state.reservations.push(row);return row;});}
  async action(input){return this.change(input.version,state=>{const row=state.reservations.find(r=>r.id===input.reservationId);if(!row)throw error(404,"Demo reservation not found.","NOT_FOUND");const action=input.action,now=new Date().toISOString();if(action==="arrive"&&row.status==="confirmed")row.status="arrived";else if(action==="cancel"&&["confirmed","arrived"].includes(row.status))row.status="cancelled";else if(action==="seat"&&row.status==="arrived") {const table=state.tables.find(t=>t.id===input.tableId);if(!table||table.status!=="available"||table.seats<row.partySize)throw error(409,"Choose an available sample table that fits this party.","TABLE_UNAVAILABLE");row.status="seated";row.tableId=table.id;table.status="seated";table.reservationId=row.id;}else if(action==="complete"&&row.status==="seated"){const table=state.tables.find(t=>t.id===row.tableId);if(!table||table.reservationId!==row.id)throw error(409,"The table link needs manager review.","TABLE_LINK_MISSING");row.status="completed";table.status="cleaning";}else throw error(409,"This action is not available at the current step.","INVALID_TRANSITION");row.updatedAt=now;return row;});}
  async ready(input){return this.change(input.version,state=>{const table=state.tables.find(t=>t.id===input.tableId);if(!table||table.status!=="cleaning")throw error(409,"Only a cleaning table can become available.","INVALID_TABLE_STATE");table.status="available";table.reservationId=null;return table;});}
  async clearHistory(input){return this.change(input.version,state=>{const removed=new Set(state.reservations.filter(r=>["cancelled","completed"].includes(r.status)).map(r=>r.id));state.reservations=state.reservations.filter(r=>!removed.has(r.id));for(const table of state.tables)if(table.status==="cleaning"&&removed.has(table.reservationId))table.reservationId=null;return {removed:removed.size};});}
}
module.exports={HarborPointDemoService,HOLIDAYS};
