"use strict";
class RoleBasedServiceErgonomicsService{
 constructor(database,auditService,realtimeHub,managerInterventionDecisionSpeedService){Object.assign(this,{database,auditService,realtimeHub,managerInterventionDecisionSpeedService});this.roles=["HOST","SERVER","BARTENDER","KITCHEN","MANAGER","GENERAL_MANAGER"];}
 now(){return new Date().toISOString();}
 async observations(org){const db=await this.database.read();return (db.roleBasedServiceErgonomicsObservations||[]).filter(x=>x.organizationId===org).sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt));}
 async certifications(org){const db=await this.database.read();return (db.roleBasedServiceErgonomicsCertifications||[]).filter(x=>x.organizationId===org).sort((a,b)=>new Date(b.certifiedAt)-new Date(a.certifiedAt));}
 async snapshot(org,allowed){
  const [manager,obs,certs]=await Promise.all([this.managerInterventionDecisionSpeedService.snapshot(org,allowed),this.observations(org),this.certifications(org)]);
  const locations=(manager.locations||[]).map(loc=>{const latest=obs.find(x=>x.locationId===loc.locationId)||null,cert=certs.find(x=>x.locationId===loc.locationId)||null,roles=latest?.roles||[];
   const avgScan=roles.length?roles.reduce((n,x)=>n+Number(x.scanSeconds||0),0)/roles.length:0,avgActions=roles.length?roles.reduce((n,x)=>n+Number(x.primaryActionsVisible||0),0)/roles.length:0;
   const highCritical=(latest?.findings||[]).filter(x=>x.status!=="RESOLVED"&&["high","critical"].includes(String(x.severity||"").toLowerCase()));
   const checks=[
    {id:"MANAGER_DECISION_READY",passed:loc.decisionReady||loc.certification?.decision==="READY",actual:loc.state},
    {id:"ALL_SERVICE_ROLES_OBSERVED",passed:!!latest&&this.roles.every(id=>roles.some(x=>x.role===id)),actual:`${roles.length}/${this.roles.length}`},
    {id:"ROLE_RELEVANCE",passed:!!latest&&roles.every(x=>x.relevance==="PASS"),actual:latest?`${roles.filter(x=>x.relevance==="PASS").length}/${roles.length}`:"not observed"},
    {id:"INFORMATION_DENSITY",passed:latest?.informationDensity==="PASS",actual:latest?.informationDensity||"not assessed"},
    {id:"VISUAL_HIERARCHY",passed:latest?.visualHierarchy==="PASS",actual:latest?.visualHierarchy||"not assessed"},
    {id:"READABILITY",passed:latest?.readability==="PASS",actual:latest?.readability||"not assessed"},
    {id:"TOUCH_TARGETS",passed:latest?.touchTargets==="PASS",actual:latest?.touchTargets||"not assessed"},
    {id:"SHIFT_SCAN_SPEED",passed:!!latest&&avgScan<=Number(latest.thresholds.maxScanSeconds),actual:latest?`${avgScan.toFixed(1)}s avg / ${latest.thresholds.maxScanSeconds}s max`:"not observed"},
    {id:"PRIMARY_ACTION_DENSITY",passed:!!latest&&avgActions<=Number(latest.thresholds.maxPrimaryActions),actual:latest?`${avgActions.toFixed(1)} avg / ${latest.thresholds.maxPrimaryActions} max`:"not observed"},
    {id:"NO_HIGH_CRITICAL_ERGONOMIC_FRICTION",passed:highCritical.length===0,actual:`${highCritical.length} high/critical finding(s)`},
    {id:"HUMAN_ERGONOMIC_CERTIFICATION",passed:!!cert,actual:cert?.decision||"not certified"}];
   return {locationId:loc.locationId,locationName:loc.locationName,latestObservation:latest,certification:cert,checks,passed:checks.filter(x=>x.passed).length,total:checks.length,ergonomicReady:checks.slice(0,-1).every(x=>x.passed),metrics:{averageScanSeconds:Number(avgScan.toFixed(2)),averagePrimaryActions:Number(avgActions.toFixed(2))},state:cert?.decision==="READY"?"ROLE_ERGONOMICS_READY":cert?.decision==="REVISE"?"ROLE_ERGONOMICS_REVISE":cert?.decision==="HOLD"?"ROLE_ERGONOMICS_HOLD":latest?"ROLE_ERGONOMICS_OBSERVED":"ROLE_ERGONOMICS_OBSERVATION_REQUIRED"};});
  return {version:"54.75.0",generatedAt:this.now(),status:locations.some(x=>x.certification?.decision==="READY")?"role-ergonomics-ready":locations.some(x=>x.latestObservation)?"role-ergonomics-in-review":"role-ergonomics-observation-required",headline:`${locations.filter(x=>x.ergonomicReady).length}/${locations.length} location(s) satisfy role-based service ergonomics gates.`,roles:this.roles,locations,policy:{roleSpecificObservationRequired:true,informationDensityRequired:true,visualHierarchyRequired:true,readabilityRequired:true,touchTargetReviewRequired:true,scanSpeedRequired:true,humanReadyReviseHoldRequired:true,noAutomaticRolePermissionChange:true,noAutomaticLayoutMutation:true,noAutomaticRestaurantAction:true,autonomousProductionChanges:false}};
 }
 async observe(org,allowed,locationId,input,actor){
  const roles=(Array.isArray(input.roles)?input.roles:[]).map(x=>({role:String(x.role||"").toUpperCase(),scanSeconds:Math.max(0,Number(x.scanSeconds)||0),primaryActionsVisible:Math.max(0,Number(x.primaryActionsVisible)||0),relevance:String(x.relevance||"").toUpperCase(),note:String(x.note||"").trim().slice(0,1000)}));
  if(this.roles.some(id=>!roles.some(x=>x.role===id)))throw new Error("All six service roles require ergonomic observation.");if(roles.some(x=>x.relevance!=="PASS"&&x.relevance!=="FAIL"))throw new Error("Role relevance must be PASS or FAIL.");
  for(const k of ["informationDensity","visualHierarchy","readability","touchTargets"])if(!["PASS","FAIL"].includes(String(input[k]||"").toUpperCase()))throw new Error(`${k} must be PASS or FAIL.`);
  const evidence=String(input.evidence||"").trim();if(!evidence)throw new Error("Ergonomic evidence is required.");
  const record={id:`rbe_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,organizationId:org,locationId,observedAt:this.now(),observedBy:actor,roles,thresholds:{maxScanSeconds:Math.max(1,Number(input.maxScanSeconds)||8),maxPrimaryActions:Math.max(1,Number(input.maxPrimaryActions)||7)},informationDensity:String(input.informationDensity).toUpperCase(),visualHierarchy:String(input.visualHierarchy).toUpperCase(),readability:String(input.readability).toUpperCase(),touchTargets:String(input.touchTargets).toUpperCase(),evidence:evidence.slice(0,4000),findings:Array.isArray(input.findings)?input.findings:[],note:String(input.note||"").trim().slice(0,2200),rolePermissionsChanged:false,layoutMutatedAutomatically:false,restaurantActionExecuted:false};
  await this.database.mutate(db=>{db.roleBasedServiceErgonomicsObservations||=[];db.roleBasedServiceErgonomicsObservations.push(record);return record;});await this.auditService.record({organizationId:org,actor,action:`Role-based service ergonomics observation recorded for ${locationId}`,category:"service_ergonomics"});return record;
 }
 async certify(org,allowed,locationId,input,actor){const state=await this.snapshot(org,allowed),loc=state.locations.find(x=>x.locationId===locationId);if(!loc?.latestObservation)throw new Error("Ergonomic observation required.");const decision=String(input.decision||"").toUpperCase(),evidence=String(input.evidence||"").trim(),reason=String(input.reason||"").trim();if(!["READY","REVISE","HOLD"].includes(decision))throw new Error("Decision must be READY, REVISE, or HOLD.");if(!evidence)throw new Error("Certification evidence required.");if(decision==="READY"&&!loc.ergonomicReady&&!reason)throw new Error("READY with open gates requires override reason.");if(["REVISE","HOLD"].includes(decision)&&!reason)throw new Error(`${decision} requires reason.`);const record={id:`rbec_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,organizationId:org,locationId,decision,status:"ROLE_BASED_SERVICE_ERGONOMICS_CERTIFIED",certifiedAt:this.now(),certifiedBy:actor,evidence:evidence.slice(0,4000),reason:reason.slice(0,2200),gateSnapshot:loc.checks,rolePermissionsChangedByCertification:false,layoutMutatedByCertification:false,restaurantActionExecutedByCertification:false,autonomousProductionChanges:false};await this.database.mutate(db=>{db.roleBasedServiceErgonomicsCertifications||=[];db.roleBasedServiceErgonomicsCertifications.push(record);return record;});return record;}
}
module.exports=RoleBasedServiceErgonomicsService;
