"use strict";
class WorkforceIntelligenceService{
 constructor(database,auditService,realtimeHub,autonomousOperationsService){Object.assign(this,{database,auditService,realtimeHub,autonomousOperationsService});}
 async snapshot(organizationId,locationId){
  const db=await this.database.read();
  const location=(db.locations||[]).find(x=>x.id===locationId&&x.organizationId===organizationId);
  if(!location){const error=new Error("Location is not available to this organization.");error.statusCode=404;throw error;}
  const staff=(db.staff||[]).filter(x=>x.organizationId===organizationId&&x.locationId===locationId);
  const sections=(db.sections||[]).filter(x=>x.organizationId===organizationId&&x.locationId===locationId);
  const reservations=(db.reservations||[]).filter(x=>x.organizationId===organizationId&&x.locationId===locationId&&!['cancelled','completed'].includes(x.status));
  const waitlist=(db.waitlist||[]).filter(x=>x.organizationId===organizationId&&x.locationId===locationId&&!['cancelled','seated'].includes(x.status));
  const tickets=(db.kitchenTickets||[]).filter(x=>x.organizationId===organizationId&&x.locationId===locationId&&!['served','cancelled'].includes(x.status));
  const plan=(db.laborPlans||[]).find(x=>x.organizationId===organizationId&&x.locationId===locationId)||{};
  const roles=['server','bartender','host','cook','expo','manager'];
  const active=staff.filter(x=>x.status!=='off');
  const time=value=>{if(!value)return null;const match=String(value).match(/(?:T|^)(\d{2}:\d{2})/);return match?.[1]||null;};
  const hours=record=>{if(!/^\d{2}:\d{2}$/.test(record.start||'')||!/^\d{2}:\d{2}$/.test(record.end||''))return 0;const [sh,sm]=record.start.split(':').map(Number),[eh,em]=record.end.split(':').map(Number);return Math.max(0,(eh*60+em-sh*60-sm)/60);};
  const scheduled=active.map(person=>({id:person.id,name:person.name,role:person.role||'Unassigned',status:person.status||'active',start:time(person.shiftStart)||'—',end:time(person.shiftEnd)||'—',hourlyRate:Number(person.hourlyRate||0),skillScore:Number.isFinite(Number(person.skillScore))?Number(person.skillScore):'—',reliability:Number.isFinite(Number(person.reliability))?Number(person.reliability):'—',section:sections.find(x=>x.id===person.sectionId)?.name||'Unassigned'}));
  const projectedHours=Math.round(scheduled.reduce((s,x)=>s+hours(x),0)*10)/10;
  const projectedLabor=Math.round(scheduled.reduce((s,x)=>s+hours(x)*x.hourlyRate,0));
  const salesForecast=Number(plan.salesForecast||0); const laborPercent=salesForecast>0?Math.round(projectedLabor/salesForecast*1000)/10:0;
  const demand=Math.max(0,Math.round((reservations.length*2+waitlist.length*3+tickets.length*2)/5));
  const recommendations=[];
  const servers=scheduled.filter(x=>x.role==='server').length, cooks=scheduled.filter(x=>x.role==='cook').length;
  if(demand>servers*2)recommendations.push({id:'wf_add_server',severity:'high',title:'Add one service shift',action:'Offer a 5:00–9:00 PM server shift',reason:`Demand index ${demand} exceeds current server coverage.`,impact:'Reduce table wait 6–9 min',status:'active'});
  if(tickets.length>cooks*3)recommendations.push({id:'wf_add_cook',severity:'high',title:'Increase line coverage',action:'Extend one cook through close',reason:`${tickets.length} active tickets are loading ${cooks} scheduled cooks.`,impact:'Protect ticket target',status:'active'});
  if(laborPercent>Number(plan.targetLaborPercent||18)+1)recommendations.push({id:'wf_trim_labor',severity:'medium',title:'Trim late labor',action:'Release one low-demand closer at 9:30 PM',reason:`Projected labor is ${laborPercent}% against an ${plan.targetLaborPercent||18}% target.`,impact:`Save $${Math.round(projectedLabor*.06)}`,status:'active'});
  if(!recommendations.length)recommendations.push(scheduled.length?{id:'wf_hold_plan',severity:'low',title:'Maintain staffing plan',action:'Keep the current deployment',reason:'Recorded coverage and labor cost are within target thresholds.',impact:'Stable service',status:'active'}:{id:'wf_staffing_setup',severity:'medium',title:'Complete staffing setup',action:'Add the active restaurant team before service.',reason:'No active staff records are available for this restaurant.',impact:'Restore trustworthy coverage and labor guidance.',status:'active'});
  const roleCoverage=roles.map(role=>{const people=scheduled.filter(x=>String(x.role).toLowerCase()===role),skills=people.map(x=>x.skillScore).filter(Number.isFinite);return{role,scheduled:people.length,required:demand?Math.max(1,Math.round(demand/[3,5,6,4,7,12][roles.indexOf(role)])):0,averageSkill:skills.length?Math.round(skills.reduce((s,x)=>s+x,0)/skills.length):'—'};});
  return{generatedAt:new Date().toISOString(),locationId,summary:{scheduledPeople:scheduled.length,projectedHours,projectedLabor,salesForecast,laborPercent,targetLaborPercent:Number(plan.targetLaborPercent||18),demandIndex:demand,calloutRisk:scheduled.filter(x=>x.status==='callout-risk'||(Number.isFinite(x.reliability)&&x.reliability<85)).length,overtimeRisk:scheduled.filter(x=>hours(x)>8).length},scheduled,roleCoverage,recommendations,actions:(db.laborActions||[]).filter(x=>x.organizationId===organizationId&&x.locationId===locationId).slice(-20).reverse(),shiftOffers:(db.shiftOffers||[]).filter(x=>x.organizationId===organizationId&&x.locationId===locationId&&x.status==='open')};
 }
 async act(recommendationId,input,actor,organizationId){const locationId=String(input.locationId||'').trim(),location=locationId?await this.database.get('locations',locationId):null;if(!location||location.organizationId!==organizationId){const error=new Error('Location is not available to this organization.');error.statusCode=404;throw error;}const record={id:`labor_${Date.now()}`,recommendationId,organizationId,locationId,decision:input.decision||'approved',note:String(input.note||''),actor,createdAt:new Date().toISOString()};await this.database.mutate(db=>{db.laborActions||=[];db.shiftOffers||=[];db.laborActions.push(record);if(record.decision==='approved'&&recommendationId.includes('add_'))db.shiftOffers.push({id:`offer_${Date.now()}`,organizationId,locationId:record.locationId,recommendationId,role:recommendationId.includes('cook')?'cook':'server',shift:'5:00 PM–9:00 PM',status:'open',createdAt:record.createdAt});return record;});await this.auditService.record({organizationId,actor,action:`Labor recommendation ${record.decision}: ${recommendationId}`,category:'workforce'});this.realtimeHub.publish('workforce:action-recorded',record);return record;}
 async updatePlan(locationId,input,actor,organizationId){const location=locationId?await this.database.get('locations',locationId):null;if(!location||location.organizationId!==organizationId){const error=new Error('Location is not available to this organization.');error.statusCode=404;throw error;}let result;await this.database.mutate(db=>{db.laborPlans||=[];let plan=db.laborPlans.find(x=>x.organizationId===organizationId&&x.locationId===locationId);if(!plan){plan={id:`plan_${locationId}`,organizationId,locationId};db.laborPlans.push(plan);}Object.assign(plan,{salesForecast:Number(input.salesForecast||plan.salesForecast||0),targetLaborPercent:Number(input.targetLaborPercent||plan.targetLaborPercent||18),updatedAt:new Date().toISOString()});result=plan;return plan;});await this.auditService.record({organizationId,actor,action:'Labor plan updated',category:'workforce'});this.realtimeHub.publish('workforce:plan-updated',result);return result;}
}
module.exports=WorkforceIntelligenceService;
