(() => {
"use strict";
// V100.2.73 — Scheduling Truth Foundation.
// Primary schedule surface uses the Scheduling API's recorded shifts/publication state only.
// AI recommendations, reservation-demand assumptions, and synthetic staffing guidance stay out of this view.
const LOCATION_ID="loc_marina";
const byId=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let api=null,state=null,weekStart="",loading=false;
const iso=d=>d.toISOString().slice(0,10);
function monday(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return iso(x)}
function ensureStyles(){
 if(byId("bcScheduleTruthStylesV100273"))return;
 const s=document.createElement("style");s.id="bcScheduleTruthStylesV100273";s.textContent=`
 #scheduling.bc-schedule-truth-active-v273>.container{display:none!important}.bc-schedule-truth-v273{max-width:1180px;margin:0 auto;padding:32px 24px;color:#17343c}
 .bc-schedule-truth-v273 .bc-sch-head,.bc-schedule-truth-v273 .bc-sch-nav{display:flex;justify-content:space-between;gap:16px;align-items:center}.bc-schedule-truth-v273 small{color:#6b8086}.bc-schedule-truth-v273 h2{margin:5px 0 7px;font-size:32px}.bc-schedule-truth-v273 p{color:#5f757c;margin:0}
 .bc-schedule-truth-v273 button{border:0;border-radius:12px;padding:10px 13px;background:#0c6978;color:#fff;font-weight:900;cursor:pointer}.bc-schedule-truth-v273 .bc-sch-nav{margin:18px 0;padding:13px;background:#f5fafb;border:1px solid #d9e6e8;border-radius:16px}.bc-schedule-truth-v273 .bc-sch-nav div{display:flex;gap:8px}
 .bc-schedule-truth-v273 .bc-sch-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.bc-schedule-truth-v273 .bc-sch-kpis article{padding:14px;background:#fff;border:1px solid #dbe7e9;border-radius:16px}.bc-schedule-truth-v273 .bc-sch-kpis span{display:block;color:#6b8086;font-size:12px}.bc-schedule-truth-v273 .bc-sch-kpis strong{display:block;font-size:25px;margin-top:3px}
 .bc-schedule-truth-v273 .bc-sch-days{display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.bc-schedule-truth-v273 .bc-sch-day{min-width:0;border:1px solid #dbe7e9;border-radius:15px;background:#fff;overflow:hidden}.bc-schedule-truth-v273 .bc-sch-day header{padding:10px;background:#f3f8f9}.bc-schedule-truth-v273 .bc-sch-day header strong,.bc-schedule-truth-v273 .bc-sch-day header span{display:block}.bc-schedule-truth-v273 .bc-sch-shift{padding:10px;border-top:1px solid #e7eef0}.bc-schedule-truth-v273 .bc-sch-shift strong,.bc-schedule-truth-v273 .bc-sch-shift span,.bc-schedule-truth-v273 .bc-sch-shift small{display:block}.bc-schedule-truth-v273 .bc-sch-open{font-weight:900;color:#8a5328}.bc-schedule-truth-v273 .bc-sch-source{margin-top:14px;font-size:12px;color:#70858b}.bc-schedule-truth-v273 .bc-sch-empty{padding:18px;color:#647a81}
 @media(max-width:900px){.bc-schedule-truth-v273 .bc-sch-days{grid-template-columns:1fr 1fr}.bc-schedule-truth-v273 .bc-sch-kpis{grid-template-columns:1fr 1fr}}@media(max-width:600px){.bc-schedule-truth-v273{padding:20px 12px}.bc-schedule-truth-v273 .bc-sch-head,.bc-schedule-truth-v273 .bc-sch-nav{display:block}.bc-schedule-truth-v273 .bc-sch-nav div{margin-top:10px}.bc-schedule-truth-v273 .bc-sch-days{grid-template-columns:1fr}}
 `;document.head.appendChild(s);
}
function shell(){const root=byId("scheduling");if(!root)return null;root.classList.add("bc-schedule-truth-active-v273");let v=root.querySelector(":scope > .bc-schedule-truth-v273");if(!v){v=document.createElement("div");v.className="bc-schedule-truth-v273";root.appendChild(v)}return v}
function employeeName(shift){const e=(state?.employees||[]).find(x=>String(x.id)===String(shift.employeeId));return e?.name||null}
function render(payload){state=payload||{};weekStart=state.weekStart||weekStart||monday(new Date());const v=shell();if(!v)return;const shifts=Array.isArray(state.shifts)?state.shifts:[],summary=state.summary||{},start=new Date(`${weekStart}T12:00:00`),days=[];for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);days.push(iso(d))}const published=!!state.publication;
 v.innerHTML=`<div class="bc-sch-head"><div><small>Scheduling · recorded truth</small><h2>Who is scheduled to work?</h2><p>Published and draft shifts come directly from Blue Current Scheduling. Recommendations and demand assumptions are intentionally excluded from this primary view.</p></div><button data-bc-sch-refresh>Refresh</button></div>
 <div class="bc-sch-nav"><strong>${esc(state.weekStart||weekStart)} — ${esc(state.weekEnd||"")}</strong><div><button data-bc-sch-prev>← Previous</button><button data-bc-sch-today>This week</button><button data-bc-sch-next>Next →</button></div></div>
 <div class="bc-sch-kpis"><article><span>Schedule state</span><strong>${published?"Published":"Draft"}</strong></article><article><span>Shifts</span><strong>${Number(summary.totalShifts??shifts.length)}</strong></article><article><span>Open shifts</span><strong>${Number(summary.openShifts??shifts.filter(x=>!x.employeeId).length)}</strong></article><article><span>Conflicts</span><strong>${Number(summary.conflicts??0)}</strong></article></div>
 <div class="bc-sch-days">${days.map((date,i)=>{const items=shifts.filter(x=>x.date===date);return `<section class="bc-sch-day"><header><strong>${["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</strong><span>${esc(date.slice(5))}</span></header>${items.length?items.map(x=>`<article class="bc-sch-shift"><small>${esc(x.department||"Operations")}</small><strong>${esc(x.role||"Shift")}</strong><span>${esc(x.startTime||"")}–${esc(x.endTime||"")}</span><span class="${x.employeeId?"":"bc-sch-open"}">${esc(employeeName(x)||"Open shift")}</span></article>`).join(""):`<div class="bc-sch-empty">No shifts</div>`}</section>`}).join("")}</div>
 <div class="bc-sch-source">Source: Blue Current Scheduling API · ${published?`Published ${esc(new Date(state.publication.publishedAt).toLocaleString())}`:"Draft — not certified as expected staffing"} · AI staffing recommendations excluded</div>`;
 v.querySelector("[data-bc-sch-refresh]")?.addEventListener("click",load);v.querySelector("[data-bc-sch-prev]")?.addEventListener("click",()=>move(-7));v.querySelector("[data-bc-sch-next]")?.addEventListener("click",()=>move(7));v.querySelector("[data-bc-sch-today]")?.addEventListener("click",()=>{weekStart=monday(new Date());load()});
 window.dispatchEvent(new CustomEvent("bluecurrent:scheduling-truth-rendered",{detail:{version:"100.2.73",published,shifts:shifts.length}}));
}
function move(days){const d=new Date(`${weekStart||monday(new Date())}T12:00:00`);d.setDate(d.getDate()+days);weekStart=iso(d);load()}
async function load(){if(loading)return;loading=true;ensureStyles();shell();try{api ||= new window.BlueCurrentCloudApi("");if(!api?.token)throw new Error("Sign in to load the live schedule.");render(await api.scheduling(LOCATION_ID,weekStart))}catch(error){const v=shell();if(v)v.innerHTML=`<div class="bc-sch-head"><div><small>Scheduling · recorded truth</small><h2>Schedule unavailable</h2><p>Blue Current will not substitute AI recommendations or demo staffing when the Scheduling source is unavailable.</p></div><button data-bc-sch-refresh>Try again</button></div><div class="bc-sch-empty"><strong>Scheduling source unavailable.</strong><div>${esc(error?.message||"Unable to load schedule.")}</div></div>`;v?.querySelector("[data-bc-sch-refresh]")?.addEventListener("click",load)}finally{loading=false}}
function init(){if(!byId("scheduling"))return;weekStart=monday(new Date());ensureStyles();load();window.BlueCurrentSchedulingTruthV100_2_73={refresh:load,getState:()=>state?JSON.parse(JSON.stringify(state)):null}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})();