(() => {
"use strict";
// V100.2.76 — Time & Attendance Truth Foundation.
// Primary Time Clock surface is limited to recorded punch/break state from the Time Clock API.
// Labor-cost projections, overtime predictions, and synthetic attendance diagnoses stay out of this primary view.
const LOCATION_ID="loc_marina";
const byId=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmtTime=value=>{if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":d.toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})};
let api=null,state=null,loading=false,activated=false;
function ensureStyles(){
 if(byId("bcTimeClockTruthStylesV100276"))return;
 const s=document.createElement("style");s.id="bcTimeClockTruthStylesV100276";s.textContent=`
 #time-clock.bc-timeclock-truth-active-v276>.container{display:none!important}.bc-timeclock-truth-v276{max-width:1180px;margin:0 auto;padding:32px 24px;color:#17343c}
 .bc-timeclock-truth-v276 .bc-tc-head,.bc-timeclock-truth-v276 .bc-tc-panel-head{display:flex;justify-content:space-between;gap:16px;align-items:center}.bc-timeclock-truth-v276 small{color:#6b8086}.bc-timeclock-truth-v276 h2{margin:5px 0 7px;font-size:32px}.bc-timeclock-truth-v276 h3{margin:3px 0}.bc-timeclock-truth-v276 p{color:#5f757c;margin:0}
 .bc-timeclock-truth-v276 button{border:0;border-radius:12px;padding:10px 13px;background:#0c6978;color:#fff;font-weight:900;cursor:pointer}.bc-timeclock-truth-v276 button.bc-tc-secondary{background:#eef5f6;color:#31545d;border:1px solid #d6e4e7}.bc-timeclock-truth-v276 button:disabled{opacity:.5;cursor:not-allowed}
 .bc-timeclock-truth-v276 .bc-tc-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.bc-timeclock-truth-v276 .bc-tc-kpis article{padding:14px;background:#fff;border:1px solid #dbe7e9;border-radius:16px}.bc-timeclock-truth-v276 .bc-tc-kpis span{display:block;color:#6b8086;font-size:12px}.bc-timeclock-truth-v276 .bc-tc-kpis strong{display:block;font-size:25px;margin-top:3px}
 .bc-timeclock-truth-v276 .bc-tc-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.bc-timeclock-truth-v276 .bc-tc-panel{background:#fff;border:1px solid #dbe7e9;border-radius:16px;padding:16px;min-width:0}.bc-timeclock-truth-v276 label{display:block;color:#5f757c;font-size:13px;font-weight:800;margin-top:12px}.bc-timeclock-truth-v276 select,.bc-timeclock-truth-v276 input{box-sizing:border-box;width:100%;margin-top:6px;border:1px solid #cadbdd;border-radius:11px;padding:11px;background:#fff;color:#17343c}.bc-timeclock-truth-v276 .bc-tc-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}
 .bc-timeclock-truth-v276 .bc-tc-list{display:grid;gap:8px;margin-top:12px}.bc-timeclock-truth-v276 .bc-tc-row{border:1px solid #e0eaec;border-radius:12px;padding:11px;display:flex;justify-content:space-between;align-items:center;gap:12px}.bc-timeclock-truth-v276 .bc-tc-row>div:first-child{min-width:0}.bc-timeclock-truth-v276 .bc-tc-row strong,.bc-timeclock-truth-v276 .bc-tc-row span,.bc-timeclock-truth-v276 .bc-tc-row small{display:block}.bc-timeclock-truth-v276 .bc-tc-row span{color:#60767c;margin-top:2px}.bc-timeclock-truth-v276 .bc-tc-row .bc-tc-row-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.bc-timeclock-truth-v276 .bc-tc-row .bc-tc-row-actions button{padding:8px 9px;font-size:12px}.bc-timeclock-truth-v276 .bc-tc-empty{padding:15px;color:#647a81;background:#f7fafb;border-radius:12px;margin-top:12px}.bc-timeclock-truth-v276 .bc-tc-source{margin-top:14px;font-size:12px;color:#70858b}
 @media(max-width:850px){.bc-timeclock-truth-v276 .bc-tc-kpis{grid-template-columns:1fr 1fr}.bc-timeclock-truth-v276 .bc-tc-grid{grid-template-columns:1fr}}@media(max-width:560px){.bc-timeclock-truth-v276{padding:20px 12px}.bc-timeclock-truth-v276 .bc-tc-head{display:block}.bc-timeclock-truth-v276 .bc-tc-head button{margin-top:12px}.bc-timeclock-truth-v276 .bc-tc-row{display:block}.bc-timeclock-truth-v276 .bc-tc-row .bc-tc-row-actions{justify-content:flex-start;margin-top:9px}}
 `;document.head.appendChild(s);
}
function shell(){const root=byId("time-clock");if(!root)return null;root.classList.add("bc-timeclock-truth-active-v276");let v=root.querySelector(":scope > .bc-timeclock-truth-v276");if(!v){v=document.createElement("div");v.className="bc-timeclock-truth-v276";root.appendChild(v)}return v}
function employeeName(id){return (state?.employees||[]).find(x=>String(x.id)===String(id))?.name||id||"Unknown employee"}
function roleFor(id){return (state?.employees||[]).find(x=>String(x.id)===String(id))?.role||"Team member"}
function render(payload){
 state=payload||{};const v=shell();if(!v)return;const active=Array.isArray(state.active)?state.active:[],cards=Array.isArray(state.timecards)?state.timecards:[],corrections=Array.isArray(state.corrections)?state.corrections:[],employees=Array.isArray(state.employees)?state.employees:[];const needsReview=cards.filter(x=>String(x.status)==="needs_review").length;
 v.innerHTML=`<div class="bc-tc-head"><div><small>Time & Attendance · recorded truth</small><h2>Who is actually working right now?</h2><p>Blue Current shows recorded clock-ins, breaks, clock-outs, and manager corrections. Cost projections and attendance diagnoses are intentionally excluded from this primary view.</p></div><button data-bc-tc-refresh>Refresh</button></div>
 <div class="bc-tc-kpis"><article><span>Clocked in</span><strong>${active.length}</strong></article><article><span>On break</span><strong>${active.filter(x=>x.onBreak).length}</strong></article><article><span>Recorded punches today</span><strong>${cards.length}</strong></article><article><span>Needs review</span><strong>${needsReview}</strong></article></div>
 <div class="bc-tc-grid"><section class="bc-tc-panel"><div class="bc-tc-panel-head"><div><small>Employee kiosk</small><h3>Clock in / out</h3></div></div><label>Employee<select data-bc-tc-employee>${employees.map(e=>`<option value="${esc(e.id)}">${esc(e.name)} · ${esc(e.role||"Team member")}</option>`).join("")}</select></label><label>PIN<input data-bc-tc-pin type="password" inputmode="numeric" maxlength="6" placeholder="Enter PIN"></label><div class="bc-tc-actions"><button data-bc-tc-kiosk="clock-in">Clock in</button><button class="bc-tc-secondary" data-bc-tc-kiosk="clock-out">Clock out</button></div></section>
 <section class="bc-tc-panel"><div class="bc-tc-panel-head"><div><small>Current recorded state</small><h3>Working now</h3></div></div><div class="bc-tc-list">${active.length?active.map(item=>`<article class="bc-tc-row"><div><strong>${esc(item.employeeName||employeeName(item.employeeId))}</strong><span>${esc(item.role||roleFor(item.employeeId))} · clocked in ${esc(fmtTime(item.clockIn))}</span><small>${item.onBreak?"Recorded break active":"Recorded working state"}</small></div><div class="bc-tc-row-actions">${item.onBreak?`<button data-bc-tc-action="break-end" data-employee="${esc(item.employeeId)}">End break</button>`:`<button class="bc-tc-secondary" data-bc-tc-action="break-start" data-employee="${esc(item.employeeId)}">Start break</button>`}<button class="bc-tc-secondary" data-bc-tc-action="clock-out" data-employee="${esc(item.employeeId)}">Clock out</button></div></article>`).join(""):`<div class="bc-tc-empty">No active clock-ins are recorded.</div>`}</div></section></div>
 <div class="bc-tc-grid"><section class="bc-tc-panel"><div class="bc-tc-panel-head"><div><small>Recorded today</small><h3>Timecards</h3></div></div><div class="bc-tc-list">${cards.length?cards.map(item=>`<article class="bc-tc-row"><div><strong>${esc(employeeName(item.employeeId))}</strong><span>${esc(fmtTime(item.clockIn))} → ${item.clockOut?esc(fmtTime(item.clockOut)):"Active"}</span><small>Status: ${esc(item.status||"recorded")}</small></div><div class="bc-tc-row-actions"><button class="bc-tc-secondary" data-bc-tc-correct="${esc(item.id)}">Correct</button></div></article>`).join(""):`<div class="bc-tc-empty">No timecards are recorded for today.</div>`}</div></section>
 <section class="bc-tc-panel"><div class="bc-tc-panel-head"><div><small>Audit trail</small><h3>Manager corrections</h3></div></div><div class="bc-tc-list">${corrections.length?corrections.map(item=>`<article class="bc-tc-row"><div><strong>${esc(item.reason||"Manager correction")}</strong><span>${esc(employeeName(item.employeeId))}</span><small>${esc(item.actor||"Manager")} · ${esc(item.createdAt?new Date(item.createdAt).toLocaleString():"Time unavailable")}</small></div></article>`).join(""):`<div class="bc-tc-empty">No manager corrections are recorded.</div>`}</div></section></div>
 <div class="bc-tc-source">Source: Blue Current Time Clock API · location ${esc(state.locationId||LOCATION_ID)} · ${state.generatedAt?`updated ${esc(new Date(state.generatedAt).toLocaleTimeString())}`:"update time unavailable"} · no attendance cause inferred</div>`;
 bind();window.dispatchEvent(new CustomEvent("bluecurrent:timeclock-truth-rendered",{detail:{version:"100.2.76",active:active.length,onBreak:active.filter(x=>x.onBreak).length,timecards:cards.length,needsReview}}));
}
function message(error){return error?.message||"Time Clock action failed."}
async function action(fn){try{await fn();await load()}catch(error){alert(message(error))}}
function bind(){const v=shell();if(!v)return;v.querySelector("[data-bc-tc-refresh]")?.addEventListener("click",load);v.querySelectorAll("[data-bc-tc-kiosk]").forEach(button=>button.addEventListener("click",()=>{const employeeId=v.querySelector("[data-bc-tc-employee]")?.value,pin=v.querySelector("[data-bc-tc-pin]")?.value;if(!employeeId)return;action(async()=>{if(button.dataset.bcTcKiosk==="clock-in")await api.clockIn({employeeId,pin,locationId:LOCATION_ID,source:"kiosk"});else await api.clockOut({employeeId,locationId:LOCATION_ID});const input=v.querySelector("[data-bc-tc-pin]");if(input)input.value=""})}));v.querySelectorAll("[data-bc-tc-action]").forEach(button=>button.addEventListener("click",()=>action(async()=>{const employeeId=button.dataset.employee;if(button.dataset.bcTcAction==="clock-out")await api.clockOut({employeeId,locationId:LOCATION_ID});else if(button.dataset.bcTcAction==="break-start")await api.startBreak({employeeId,locationId:LOCATION_ID,paid:false});else if(button.dataset.bcTcAction==="break-end")await api.endBreak({employeeId,locationId:LOCATION_ID})})));v.querySelectorAll("[data-bc-tc-correct]").forEach(button=>button.addEventListener("click",()=>{const reason=prompt("Reason for correction","Manager correction");if(reason===null)return;action(()=>api.correctTimecard(button.dataset.bcTcCorrect,{reason}))}))}
async function load(){if(loading||!activated)return;loading=true;ensureStyles();shell();try{api ||= new window.BlueCurrentCloudApi("");if(!api?.token)throw new Error("Sign in to load recorded Time Clock state.");render(await api.timeClock(LOCATION_ID))}catch(error){const v=shell();if(v)v.innerHTML=`<div class="bc-tc-head"><div><small>Time & Attendance · recorded truth</small><h2>Time Clock unavailable</h2><p>Blue Current will not substitute schedule assumptions, labor projections, or demo attendance when the Time Clock source is unavailable.</p></div><button data-bc-tc-retry>Try again</button></div><div class="bc-tc-empty"><strong>Time Clock source unavailable.</strong><div>${esc(message(error))}</div></div>`;v?.querySelector("[data-bc-tc-retry]")?.addEventListener("click",load)}finally{loading=false}}
function activate(reason="workspace"){if(activated)return;activated=true;ensureStyles();shell();load();window.BlueCurrentTimeClockTruthV100_2_76={refresh:load,getState:()=>state?JSON.parse(JSON.stringify(state)):null,reason}}
function routeRequestsTimeClock(){return /time[- ]?clock|timeclock/i.test(`${location.hash} ${location.search}`)}
function init(){const root=byId("time-clock");if(!root)return;if(routeRequestsTimeClock())activate("route");window.addEventListener("hashchange",()=>{if(routeRequestsTimeClock())activate("hashchange")});document.addEventListener("click",event=>{const target=event.target.closest?.("a,button,[role='button']");if(!target)return;const signal=[target.getAttribute("href"),target.dataset?.workspace,target.dataset?.target,target.id,target.textContent].filter(Boolean).join(" ");if(/time[- ]?clock|timeclock/i.test(signal))activate("operator-navigation")},true);if("IntersectionObserver" in window){const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting||entry.intersectionRatio>0)){observer.disconnect();activate("workspace-visible")}}, {rootMargin:"400px 0px",threshold:0});observer.observe(root)}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})();
