(function(){"use strict";
class BlueCurrentAIPCommandConsoleEngine{
 constructor(eventBus){this.eventBus=eventBus;this.key="bluecurrent:v4033:command-sessions";this.sessions=this.read();}
 read(){try{const v=JSON.parse(sessionStorage.getItem(this.key)||"[]");return Array.isArray(v)?v:[];}catch{return[];}}
 save(){sessionStorage.setItem(this.key,JSON.stringify(this.sessions));}
 inferAgent(prompt){const p=String(prompt||"").toLowerCase();if(/labor|staff|overtime|schedule/.test(p))return"Labor Agent";if(/kitchen|ticket|expo|station|fire/.test(p))return"Kitchen Agent";if(/guest|reservation|vip|waitlist/.test(p))return"Concierge Agent";if(/portfolio|location|executive|margin|forecast/.test(p))return"Executive Agent";return"Operations Agent";}
 buildEvidence(prompt){const state=window.BlueCurrentAppState?.get?.()||window.BlueCurrentAppState?.state||{};const evidence=[];const add=(label,value)=>{if(value!==undefined&&value!==null&&value!=="")evidence.push({label,value});};add("Occupancy",state.occupancyPercent??state.occupancy);add("Kitchen pressure",state.kitchenLoad??state.kitchenPressure);add("Guest wait",state.guestWaitMinutes??state.guestWait);add("Labor",state.laborPercent??state.laborPercentage);add("Service quality",state.serviceQualityScore);if(!evidence.length)evidence.push({label:"Prompt context",value:String(prompt).slice(0,160)});return evidence.slice(0,5);}
 submit(prompt){const text=String(prompt||"").trim();if(!text)throw new Error("Enter an operating question or instruction.");const agent=this.inferAgent(text),evidence=this.buildEvidence(text),writeIntent=/\b(open|close|move|assign|notify|change|approve|schedule|send|execute|update)\b/i.test(text);const session={id:`AIP-CMD-${Date.now()}`,prompt:text,agent,createdAt:new Date().toISOString(),status:writeIntent?"approval-required":"advisory",approvalRequired:writeIntent,evidence,answer:writeIntent?`I can prepare a governed execution plan for this request. Human approval is required before any operational change.`:`${agent} recommends reviewing the strongest available evidence, selecting one owned action, and measuring the outcome before expanding the response.`};this.sessions.unshift(session);this.sessions=this.sessions.slice(0,60);this.save();this.eventBus?.emit?.("aip:command-submitted",session);return session;}
 clear(){this.sessions=[];this.save();this.eventBus?.emit?.("aip:command-console-cleared",{});}
}
window.BlueCurrentAIPCommandConsoleEngine=BlueCurrentAIPCommandConsoleEngine;})();
