(function(){"use strict";
class BlueCurrentAIPGovernanceEngine{
  constructor(eventBus){this.eventBus=eventBus;this.policyKey="bluecurrent:v403:aip-policies";this.auditKey="bluecurrent:v403:aip-policy-audit";this.defaults={operations:{role:"manager",allowedTools:["operations.snapshot","operations.priorities","operations.exceptions","workflow.draft"],maxRisk:"write",approvalFor:["workflow.draft"]},executive:{role:"executive",allowedTools:["operations.snapshot","operations.priorities"],maxRisk:"read",approvalFor:[]},kitchen:{role:"manager",allowedTools:["operations.snapshot","operations.exceptions"],maxRisk:"read",approvalFor:[]},concierge:{role:"manager",allowedTools:["operations.snapshot","operations.priorities"],maxRisk:"read",approvalFor:[]}};}
  policies(){try{return{...this.defaults,...JSON.parse(localStorage.getItem(this.policyKey)||"{}")};}catch{return{...this.defaults};}}
  save(policies){localStorage.setItem(this.policyKey,JSON.stringify(policies));this.eventBus?.emit?.("aip:policies-updated",{policies,at:new Date().toISOString()});return policies;}
  update(agentId,patch){const policies=this.policies();policies[agentId]={...(policies[agentId]||{}),...patch};return this.save(policies);}
  evaluate(agentId,tool){const policy=this.policies()[agentId]||{allowedTools:[],maxRisk:"read",approvalFor:[]};const allowed=policy.allowedTools.includes(tool.name);const riskRank={read:0,write:1,critical:2};const withinRisk=(riskRank[tool.risk||"read"]??0)<=(riskRank[policy.maxRisk||"read"]??0);const approvalRequired=Boolean(tool.approval||policy.approvalFor?.includes(tool.name));const decision={id:`POL-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,agentId,tool:tool.name,allowed:allowed&&withinRisk,approvalRequired,reason:!allowed?"Tool is not assigned to this agent.":!withinRisk?"Tool risk exceeds the agent policy.":approvalRequired?"Human approval is required before execution.":"Allowed by agent policy.",at:new Date().toISOString()};this.audit(decision);this.eventBus?.emit?.("aip:policy-evaluated",decision);return decision;}
  audit(entry){let rows=[];try{rows=JSON.parse(localStorage.getItem(this.auditKey)||"[]");}catch{}rows.unshift(entry);localStorage.setItem(this.auditKey,JSON.stringify(rows.slice(0,150)));}
  summary(){const policies=this.policies();const rows=Object.entries(policies);return{agents:rows.length,toolAssignments:rows.reduce((n,[,p])=>n+(p.allowedTools?.length||0),0),governedAgents:rows.filter(([,p])=>(p.approvalFor||[]).length).length,policies};}
}
window.BlueCurrentAIPGovernanceEngine=BlueCurrentAIPGovernanceEngine;})();