(function(global){"use strict";
class BlueCurrentDeprecationManifestEngine{
  constructor({eventBus,appState,consolidationEngine,rationalizationEngine,scorecardEngine}={}){this.eventBus=eventBus;this.appState=appState;this.consolidationEngine=consolidationEngine;this.rationalizationEngine=rationalizationEngine;this.scorecardEngine=scorecardEngine;}
  state(){try{return this.appState?.getState?.()||{};}catch{return {};}}
  thresholds(){return this.consolidationEngine?.evidenceThresholds?.()||{minimumObservedDays:3,minimumOpenEvents:3,minimumTaskCompletions:1,minimumDistinctRoles:1,minimumPrimaryWorkflowCoverage:100,automaticDeletion:false};}
  manifest(){const s=this.state();return s.operatorDeprecationManifest||{version:"46.30.0",status:"draft",approvedBy:null,approvedAt:null,featureFlagEnabled:false,items:[]};}
  evidenceFor(surfaceId){const events=(this.consolidationEngine?.evidence?.()||[]).filter(x=>x.surfaceId===surfaceId),days=[...new Set(events.map(x=>String(x.at||"").slice(0,10)).filter(Boolean))],roles=[...new Set(events.map(x=>x.role).filter(Boolean))];return {surfaceId,events:events.length,opens:events.filter(x=>x.action==="open").length,taskCompletions:events.filter(x=>x.action==="task-completed").length,days:days.length,roles:roles.length,lastUsedAt:events[0]?.at||null};}
  candidate(surfaceId){const rational=this.rationalizationEngine?.classify?.(surfaceId)||{disposition:"supporting"},t=this.thresholds(),ev=this.evidenceFor(surfaceId),coverage=this.scorecardEngine?.workflowCoverage?.("manager")||{percent:0};const zeroUse=ev.events===0,coveragePass=coverage.percent>=t.minimumPrimaryWorkflowCoverage;return {surfaceId,disposition:rational.disposition,evidence:ev,coverage:coverage.percent,eligibleForManifest:rational.disposition==="deprecation-candidate"&&zeroUse&&coveragePass,reason:rational.disposition!=="deprecation-candidate"?"Not a deprecation candidate":!zeroUse?"Observed use exists":!coveragePass?"Primary workflow coverage insufficient":"Zero observed use with full primary workflow coverage",automaticDeletion:false};}
  createDraft(surfaceIds=[]){const candidates=surfaceIds.map(id=>this.candidate(id)),items=candidates.filter(x=>x.eligibleForManifest).map(x=>({surfaceId:x.surfaceId,status:"proposed-hide",reason:x.reason,featureFlag:false,approved:false,ownerSignoff:null,automaticDeletion:false})),now=Date.now(),validHours=this.thresholds().manifestValidityHours||72;const manifest={version:"46.30.0",status:"draft",createdAt:new Date(now).toISOString(),expiresAt:new Date(now+validHours*3600000).toISOString(),approvedBy:null,approvedAt:null,lastRevalidatedAt:null,revalidationStatus:"pending",featureFlagEnabled:false,items,candidates,policy:"human-approved-reversible-hide-before-delete",automaticDeletion:false};this.appState?.update?.({operatorDeprecationManifest:manifest});this.eventBus?.emit?.("operator-deprecation-manifest:updated",structuredClone(manifest));return manifest;}
  approve(approver){const current=this.manifest();if(!current.items?.length)throw new Error("Manifest has no eligible items.");if(current.expiresAt&&new Date(current.expiresAt).getTime()<=Date.now())throw new Error("Manifest expired; rebuild before approval.");const next={...current,status:"approved",approvedBy:String(approver||"Operator"),approvedAt:new Date().toISOString(),items:current.items.map(x=>({...x,approved:true}))};this.appState?.update?.({operatorDeprecationManifest:next});this.eventBus?.emit?.("operator-deprecation-manifest:updated",structuredClone(next));return next;}
  revalidate(){const current=this.manifest(),expired=Boolean(current.expiresAt)&&new Date(current.expiresAt).getTime()<=Date.now(),coverage=this.scorecardEngine?.workflowCoverage?.("manager")||{percent:0},items=(current.items||[]).map(item=>{const c=this.candidate(item.surfaceId);return {...item,revalidationEligible:c.eligibleForManifest,revalidationReason:c.reason};}),valid=!expired&&coverage.percent>=this.thresholds().minimumPrimaryWorkflowCoverage&&items.every(x=>x.revalidationEligible);const next={...current,lastRevalidatedAt:new Date().toISOString(),revalidationStatus:valid?"valid":"invalid",status:valid&&current.status==="approved"?"approved":current.status,items};this.appState?.update?.({operatorDeprecationManifest:next});this.eventBus?.emit?.("operator-deprecation-manifest:updated",structuredClone(next));return {manifest:next,valid,expired,coverage:coverage.percent};}
  setFeatureFlag(enabled){const current=this.manifest();if(enabled&&current.status!=="approved")throw new Error("Human approval is required before enabling deprecation hiding.");if(enabled&&current.revalidationStatus!=="valid")throw new Error("Manifest must pass revalidation before enabling deprecation hiding.");const next={...current,featureFlagEnabled:Boolean(enabled),previewStartedAt:enabled&&!current.previewStartedAt?new Date().toISOString():current.previewStartedAt||null,items:(current.items||[]).map(x=>({...x,featureFlag:Boolean(enabled)&&x.approved===true}))};this.appState?.update?.({operatorDeprecationManifest:next});if(typeof document!=="undefined"){for(const item of next.items){const el=document.getElementById(item.surfaceId);if(!el)continue;const hide=next.featureFlagEnabled&&item.featureFlag;if(hide){el.hidden=true;el.setAttribute("aria-hidden","true");el.setAttribute("inert","");}else{el.hidden=false;el.removeAttribute("aria-hidden");el.removeAttribute("inert");}}document.documentElement.dataset.deprecationPreview=next.featureFlagEnabled?"true":"false";}this.eventBus?.emit?.("operator-deprecation-manifest:flag-changed",{enabled:next.featureFlagEnabled});return next;}
  snapshot(){const manifest=this.manifest(),t=this.thresholds(),expired=Boolean(manifest.expiresAt)&&new Date(manifest.expiresAt).getTime()<=Date.now();return {manifest,thresholds:t,expired,approvedItems:(manifest.items||[]).filter(x=>x.approved).length,hiddenPreviewItems:(manifest.items||[]).filter(x=>x.featureFlag).length,policy:"human-approved-reversible-hide-before-delete",automaticDeletion:false,version:"46.30.0"};}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentDeprecationManifestEngine;
if(global)global.BlueCurrentDeprecationManifestEngine=BlueCurrentDeprecationManifestEngine;
})(typeof window!=="undefined"?window:globalThis);