(function(){"use strict";
function createBlueCurrentFinalRetirementAuthorizationCenterModule(eventBus,appState){const root=document.getElementById("finalRetirementAuthorizationCenter");if(!root||!window.BlueCurrentFinalRetirementAuthorizationEngine)return null;const e=new window.BlueCurrentFinalRetirementAuthorizationEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));let packet=null;
function surfaces(){const rehearsals=appState.getState?.().operatorRetirementRehearsals||[];return rehearsals.filter(x=>x.readiness?.status==="final-change-set-ready-for-human-review").map(x=>x.surfaceId);}
function options(){const ids=surfaces(),cur=$("fraSurface").value;$("fraSurface").innerHTML=ids.map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join("");if(ids.includes(cur))$("fraSurface").value=cur;}
async function render(){const snap=e.snapshot();packet=packet||snap.latest;options();let ready=null;try{ready=packet?await e.readiness(packet):null;}catch{}$("fraPackets").textContent=snap.count;$("fraExpiry").textContent=packet?new Date(packet.expiresAt).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}):"—";$("fraSecond").textContent=packet?.secondAuthorization?.authorizedBy||"—";$("fraCheckpoint").textContent=packet?.checkpoint?.checkpointVerified?"VERIFIED":"PENDING";$("fraScore").textContent=`${ready?.score||0}%`;$("fraStatus").textContent=ready?.status||"—";$("fraHeadline").textContent=packet?`${packet.surfaceId} · ${packet.status} · deletion still disabled`:"Create the final retirement authorization packet from a human-authorized plan and successful rehearsal.";$("fraBinding").innerHTML=packet?`<article><strong>Plan binding</strong><span>${esc(packet.binding.planId)} · ${esc(packet.bindingDigest)}</span></article><article><strong>Rollback digest</strong><span>${esc(packet.binding.rollbackDigest)}</span></article><article><strong>Change-set digest</strong><span>${esc(packet.binding.changeSetDigest)}</span></article><article><strong>Source digest</strong><span>${esc(packet.binding.authoritativeSourceDigest||"—")}</span></article>`:"";$("fraCommands").textContent=packet?(packet.checkpoint?.commands||[]).join("\n"):"";$("fraChecks").innerHTML=(ready?.checks||[]).map(c=>`<article><strong>${c.pass?"PASS":"BLOCK"} · ${esc(c.id)}</strong><span>${esc(c.detail)}</span></article>`).join("");}
$("fraCreate")?.addEventListener("click",async()=>{try{packet=await e.create($("fraSurface").value,"Operator");await render();}catch(err){$("fraHeadline").textContent=err.message;}});
$("fraAuthorize")?.addEventListener("click",async()=>{try{if(!packet)throw new Error("Create a packet first.");packet=await e.authorize(packet.id,$("fraApprover").value,$("fraNote").value||"");await render();}catch(err){$("fraHeadline").textContent=err.message;}});
$("fraCheckpointBtn")?.addEventListener("click",async()=>{try{if(!packet)throw new Error("Create a packet first.");packet=await e.markCheckpoint(packet.id,$("fraApprover").value||"Operator");await render();}catch(err){$("fraHeadline").textContent=err.message;}});
$("fraRefresh")?.addEventListener("click",async()=>{packet=null;await render();});render();return{engine:e,render};}
window.createBlueCurrentFinalRetirementAuthorizationCenterModule=createBlueCurrentFinalRetirementAuthorizationCenterModule;})();