(function(){"use strict";
function createBlueCurrentManagerOperatingRhythmCenterModule(eventBus,appState){const root=document.getElementById("managerOperatingRhythm");if(!root||!window.BlueCurrentManagerOperatingRhythmEngine)return null;const e=new window.BlueCurrentManagerOperatingRhythmEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c])),money=n=>`$${Number(n||0).toLocaleString()}`;let snap=null;
function render(s){snap=s;const m=s.summary||{};$("morScore").textContent=`${m.rhythmScore||0}%`;$("morReadiness").textContent=m.readinessScore||0;$("morPriorities").textContent=m.priorityCount||0;$("morActions").textContent=m.activeActions||0;$("morProfit").textContent=money(m.modeledControllableContributionDollars||0);$("morRealized").textContent=money(m.realizedImpactDollars||0);$("morHeadline").textContent=s.headline||"Build the shift plan before service.";
$("morStages").innerHTML=(s.stages||[]).map(x=>`<article><strong>${x.complete?"PASS":"OPEN"} · ${esc(x.label)}</strong><span>${esc(x.detail)}</span></article>`).join("");
$("morPriorityList").innerHTML=(s.priorities||[]).map(x=>`<article><strong>#${x.rank} · ${esc(x.title)}</strong><span>${esc(x.category)} · ${esc(x.owner)} · ${money(x.estimatedImpactDollars)} modeled impact</span><p>${esc(x.nextAction)}</p></article>`).join("")||"<article><span>No operating priorities available.</span></article>";
$("morTimeline").innerHTML=(s.narrative||[]).map(x=>`<article><span>${esc(x)}</span></article>`).join("");
const h=s.latestHandoff,c=s.latestCloseout;$("morHandoff").textContent=h?`${h.shift} · ${h.authorName}`:"NONE";$("morCloseout").textContent=c?c.resultStatus:"NONE";}
async function load(){try{$("morHeadline").textContent="Building the shift operating rhythm…";render(await e.snapshot());}catch(err){$("morHeadline").textContent=err.message;}}
$("morRefresh")?.addEventListener("click",load);
$("morPlan")?.addEventListener("click",async()=>{try{await e.plan({shift:$("morShift").value||"dinner",manager:$("morManager").value||"Manager",operatingIntent:$("morNote").value||""});await load();}catch(err){$("morHeadline").textContent=err.message;}});
$("morHandoffBtn")?.addEventListener("click",async()=>{try{await e.handoff({shift:$("morShift").value||"closing",manager:$("morManager").value||"Manager",summary:$("morNote").value||""});await load();}catch(err){$("morHeadline").textContent=err.message;}});
$("morCloseoutBtn")?.addEventListener("click",async()=>{try{await e.closeout({shift:$("morShift").value||"dinner",manager:$("morManager").value||"Manager",note:$("morNote").value||""});await load();}catch(err){$("morHeadline").textContent=err.message;}});
["hospitality-action:updated","predictive-shift:decision","service-profitability:snapshot","auth:restored"].forEach(evt=>eventBus?.on?.(evt,load));window.addEventListener?.("online",load);load();return{engine:e,load};}
window.createBlueCurrentManagerOperatingRhythmCenterModule=createBlueCurrentManagerOperatingRhythmCenterModule;})();