(function(global){"use strict";
class BlueCurrentOperatorServiceFlowEngine{
  constructor({eventBus,appState}){this.eventBus=eventBus;this.appState=appState;this.primaryCenters=new Set(["unifiedCommandCenter","guidedShiftCenter","operatorCopilotCenter","commandActionInboxCenter","shiftProfitPulseCenter","operatorServiceFlowCenter","operationsWorkspaceCenter","reservationOperationsCenter","liveFloorOperationsCenter","kitchenThroughputCenter","laborDeploymentCenter","guestRecoveryCenter"]);this.previousVisibility=new Map();this.off=[];["state:updated","guided-shift:updated","kitchen-throughput:updated","guest-recovery:updated","labor-deployment:updated","reservation-yield:updated","shift-profit-pulse:updated"].forEach(n=>this.off.push(eventBus?.on?.(n,()=>this.refresh(n))));}
  stages(){return [
    {id:"reservations",label:"Reservations",center:"reservationOperationsCenter",stateKeys:["reservationOperations","reservationYield","reservations"],question:"Are arrivals paced to capacity?"},
    {id:"floor",label:"Floor",center:"liveFloorOperationsCenter",stateKeys:["liveFloorOperations","operationalDigitalTwin","occupancyPercent"],question:"Where is seating pressure building?"},
    {id:"kitchen",label:"Kitchen",center:"kitchenThroughputCenter",stateKeys:["kitchenThroughput","kitchenOperations"],question:"What is constraining ticket flow?"},
    {id:"staffing",label:"Staffing",center:"laborDeploymentCenter",stateKeys:["laborDeployment","staffOperations","activeStaff"],question:"Is labor aligned to demand?"},
    {id:"guest",label:"Guest Recovery",center:"guestRecoveryCenter",stateKeys:["guestRecovery","guestRecoveryCases"],question:"Which guest moments need ownership?"},
    {id:"profit",label:"Profit",center:"shiftProfitPulseCenter",stateKeys:["shiftProfitPulse","costVariance","marginIntelligence"],question:"Is the shift converting demand into profit?"}
  ];}
  state(){try{return this.appState?.getState?.()||{};}catch{return {};}}
  signal(state,keys){for(const key of keys){const value=state[key];if(value!==undefined&&value!==null&&(!(Array.isArray(value))||value.length))return {key,value};}return null;}
  stageSnapshot(stage,state){const signal=this.signal(state,stage.stateKeys),center=typeof document!=="undefined"?document.getElementById(stage.center):null;let status=signal?"live":center?"ready":"unavailable",summary="Awaiting operating signal.";
    if(stage.id==="reservations"){const x=state.reservationYield||state.reservationOperations||{};summary=x.headline||`${Number(x.waitlist||x.waitlistCount||0)} waiting · ${Number(x.covers||x.bookedCovers||0)} covers`;}
    if(stage.id==="floor"){const x=state.operationalDigitalTwin||state.liveFloorOperations||{};summary=`${Number(state.occupancyPercent??x.occupancy??0)}% occupied · ${Number(x.guestWait||0)} min guest wait`;}
    if(stage.id==="kitchen"){const x=state.kitchenThroughput||{};summary=x.headline||`${Number(x.throughput||0)} throughput score · ${Number(x.wait||0)} min wait`; if(Number(x.throughput||100)<55)status="attention";}
    if(stage.id==="staffing"){const x=state.laborDeployment||{};summary=x.headline||`${Number(state.activeStaff??x.activeStaff??0)} active staff · ${Number(x.laborPercent||0)}% labor`;}
    if(stage.id==="guest"){const x=state.guestRecovery||{};summary=x.headline||`${Number(x.open||0)} open recovery moments`; if(Number(x.open||0)>0)status="attention";}
    if(stage.id==="profit"){const x=state.shiftProfitPulse||state.costVariance||{};summary=x.headline||`${Number(x.margin||x.marginPercent||0)}% margin · $${Math.round(Number(x.profitAtRisk||0))} at risk`; if(Number(x.profitAtRisk||0)>0)status="attention";}
    return {...stage,status,signalKey:signal?.key||null,centerPresent:Boolean(center),summary};}
  surfaceAudit(){if(typeof document==="undefined")return {total:0,primary:0,supporting:0,hidden:0,items:[]};const centers=[...document.querySelectorAll('section[id$="Center"],section[id$="center"]')].filter(x=>x.id);const items=centers.map(el=>({id:el.id,primary:this.primaryCenters.has(el.id),hidden:Boolean(el.hidden),technical:/readiness|certification|registry|reconciliation|telemetry|governance|sandbox|runtime|observability|integration|contract|lineage|replay|audit|benchmark/i.test(el.id)}));return {total:items.length,primary:items.filter(x=>x.primary).length,supporting:items.filter(x=>!x.primary).length,hidden:items.filter(x=>x.hidden).length,technical:items.filter(x=>x.technical).length,items};}
  handoffs(stages){return stages.slice(0,-1).map((stage,index)=>{const next=stages[index+1],needsAttention=stage.status==="attention"||next.status==="attention";return {id:`${stage.id}-to-${next.id}`,from:stage.id,to:next.id,fromLabel:stage.label,toLabel:next.label,status:needsAttention?"attention":"clear",reason:needsAttention?`${stage.label} → ${next.label} requires operator review.`:`${stage.label} → ${next.label} handoff is clear.`,targetCenter:next.center};});}
  snapshot(){const state=this.state(),stages=this.stages().map(x=>this.stageSnapshot(x,state)),live=stages.filter(x=>x.status==="live"||x.status==="attention").length,attention=stages.filter(x=>x.status==="attention").length,audit=this.surfaceAudit(),handoffs=this.handoffs(stages);const guided=state.guidedShift||{},inbox=state.commandActionInbox||{},profit=state.shiftProfitPulse||{};return {capturedAt:new Date().toISOString(),stages,handoffs,attentionHandoffs:handoffs.filter(x=>x.status==="attention").length,liveStages:live,attentionStages:attention,flowScore:Math.round(stages.reduce((s,x)=>s+(x.status==="live"?100:x.status==="attention"?75:x.status==="ready"?50:0),0)/stages.length),surfaceAudit:audit,operator:{phase:guided.phase?.label||"Shift",openActions:Number(inbox.open||inbox.pending||guided.unacknowledged||0),focusScore:Number(guided.focusScore||0),profitSignal:profit.headline||null},operatorMode:typeof document!=="undefined"?document.documentElement.dataset.operatorMode==="true":false};}
  setOperatorMode(enabled){if(typeof document==="undefined")return this.snapshot();const on=Boolean(enabled),centers=[...document.querySelectorAll('section[id$="Center"],section[id$="center"]')].filter(x=>x.id);if(on){this.previousVisibility.clear();centers.forEach(el=>{this.previousVisibility.set(el.id,{hidden:el.hidden,aria:el.getAttribute("aria-hidden"),inert:el.hasAttribute("inert")});if(!this.primaryCenters.has(el.id)){el.hidden=true;el.setAttribute("aria-hidden","true");el.setAttribute("inert","");}});document.documentElement.dataset.operatorMode="true";}else{centers.forEach(el=>{const prev=this.previousVisibility.get(el.id);if(!prev)return;el.hidden=prev.hidden;if(prev.aria==null)el.removeAttribute("aria-hidden");else el.setAttribute("aria-hidden",prev.aria);if(prev.inert)el.setAttribute("inert","");else el.removeAttribute("inert");});document.documentElement.dataset.operatorMode="false";this.previousVisibility.clear();}const snap=this.snapshot();this.eventBus?.emit?.("operator-service-flow:mode-changed",{enabled:on,snapshot:snap});return snap;}
  refresh(reason="manual"){const snap=this.snapshot();snap.reason=reason;this.appState?.update?.({operatorServiceFlow:snap});this.eventBus?.emit?.("operator-service-flow:updated",structuredClone(snap));return snap;}
  destroy(){this.off.forEach(fn=>fn?.());}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentOperatorServiceFlowEngine;
if(global)global.BlueCurrentOperatorServiceFlowEngine=BlueCurrentOperatorServiceFlowEngine;
})(typeof window!=="undefined"?window:globalThis);