(function(global){"use strict";
class BlueCurrentOperatorSurfaceRationalizationEngine{
  constructor({eventBus,appState,flowEngine}={}){this.eventBus=eventBus;this.appState=appState;this.flowEngine=flowEngine||null;this.primary=new Set(["unifiedCommandCenter","guidedShiftCenter","operatorServiceFlowCenter","operatorCopilotCenter","commandActionInboxCenter","shiftProfitPulseCenter","operationsWorkspaceCenter","reservationOperationsCenter","liveFloorOperationsCenter","kitchenThroughputCenter","laborDeploymentCenter","guestRecoveryCenter"]);this.mergeTargets=this.buildMergeTargets();}
  buildMergeTargets(){return {reservationYieldCenter:"reservationOperationsCenter",operationalDigitalTwinCenter:"liveFloorOperationsCenter",kitchenOperationsCenter:"kitchenThroughputCenter",predictiveServiceCenter:"kitchenThroughputCenter",staffOperationsCenter:"laborDeploymentCenter",workforceIntelligenceCenter:"laborDeploymentCenter",serviceRecoveryCenter:"guestRecoveryCenter",serviceRecoveryPlaybooksCenter:"guestRecoveryCenter",marginIntelligenceCenter:"shiftProfitPulseCenter",costVarianceCenter:"shiftProfitPulseCenter",priorityFocusCenter:"guidedShiftCenter",actionOwnershipCenter:"commandActionInboxCenter",shiftHandoffSnapshotCenter:"guidedShiftCenter",decisionExecutionLedgerCenter:"commandActionInboxCenter",outcomeCaptureCenter:"shiftProfitPulseCenter",shiftCloseBriefCenter:"guidedShiftCenter",openingReadinessCenter:"guidedShiftCenter",shiftCheckpointCenter:"guidedShiftCenter",dailyValueReportCenter:"shiftProfitPulseCenter",serviceExceptionQueueCenter:"commandActionInboxCenter"};}
  centerIds(){if(typeof document==="undefined")return [];return [...document.querySelectorAll('section[id$="Center"],section[id$="center"]')].map(x=>x.id).filter(Boolean);}
  classify(id){if(this.primary.has(id))return {disposition:"keep-primary",target:id,score:100,reason:"Directly supports the primary manager shift path."};if(this.mergeTargets[id])return {disposition:"merge",target:this.mergeTargets[id],score:80,reason:`Useful operator capability overlaps ${this.mergeTargets[id]}.`};if(/readiness|certification|registry|reconciliation|telemetry|governance|sandbox|runtime|observability|integration|contract|lineage|replay|audit|benchmark|deployment|release|rollback|environment|acceptance|connector|ingestion|source|provider|sync|migration|diagnostic|health|performance|budget|policy|aip|v4[0-9]|v3[0-9]/i.test(id))return {disposition:"diagnostics-admin",target:null,score:35,reason:"Technical, governance, integration, release, or certification surface."};if(/innovation|experiment|learning|scenario|strategy|tradeoff|portfolio|executive|enterprise|district|briefing|expansion|market|forecast|planning/i.test(id))return {disposition:"deprecation-candidate",target:null,score:20,reason:"Outside the core shift workflow; requires operator evidence before retention."};return {disposition:"supporting",target:null,score:50,reason:"Supporting workflow; requires operator evidence before merge or removal."};}
  snapshot(ids=null){const centerIds=Array.isArray(ids)?ids:this.centerIds(),items=centerIds.map(id=>({id,...this.classify(id)}));const counts={};items.forEach(x=>counts[x.disposition]=(counts[x.disposition]||0)+1);const duplicateGroups={};items.filter(x=>x.disposition==="merge").forEach(x=>{(duplicateGroups[x.target] ||= []).push(x.id);});const flow=this.flowEngine?.snapshot?.()||this.appState?.get?.("operatorServiceFlow")||null;const handoffs=flow?.handoffs||[];return {capturedAt:new Date().toISOString(),total:items.length,counts,items,duplicateGroups,handoffs,attentionHandoffs:handoffs.filter(x=>x.status==="attention").length,recommendations:["Keep the 12 primary operator surfaces as the default manager path.","Merge overlapping operator capabilities into mapped primary surfaces before deleting code.","Keep diagnostics/admin surfaces outside Operator Mode for implementation/support roles.","Require real operator evidence before permanently removing deprecation candidates."],deletionPolicy:"no-permanent-deletion-without-operator-evidence",version:"46.10.0"};}
  applyDispositionView(disposition){if(typeof document==="undefined")return this.snapshot();const snap=this.snapshot();for(const item of snap.items){const el=document.getElementById(item.id);if(!el)continue;const show=disposition==="all"||item.disposition===disposition||this.primary.has(item.id);el.hidden=!show;if(show){el.removeAttribute("aria-hidden");el.removeAttribute("inert");}else{el.setAttribute("aria-hidden","true");el.setAttribute("inert","");}}document.documentElement.dataset.surfaceDisposition=disposition;this.eventBus?.emit?.("operator-surface-rationalization:view-changed",{disposition});return this.snapshot();}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentOperatorSurfaceRationalizationEngine;
if(global)global.BlueCurrentOperatorSurfaceRationalizationEngine=BlueCurrentOperatorSurfaceRationalizationEngine;
})(typeof window!=="undefined"?window:globalThis);