(function(){"use strict";
function createBlueCurrentPilotProofProgramCenterModule(eventBus,appState){const root=document.getElementById("pilotProofProgram");if(!root||!window.BlueCurrentPilotProofProgramEngine)return null;const e=new window.BlueCurrentPilotProofProgramEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c])),money=n=>`$${Number(n||0).toLocaleString()}`;
function render(s){$("pppDecision").textContent=s.recommendation?.decision||"CONFIGURE";$("pppOverall").textContent=s.scorecard?.overall??"—";$("pppValue").textContent=money(s.valueLedger?.verifiedRealizedImpactDollars||0);$("pppExceptions").textContent=(s.exceptions||[]).length;$("pppHeadline").textContent=s.headline||"Pilot proof program loading…";$("pppProgram").textContent=s.program?`${s.program.name} · ${s.program.sponsor} · Day ${s.program.ageDays}/${s.program.pilotDays}`:"Pilot baseline required.";
$("pppGates").innerHTML=s.recommendation?.gates?Object.entries(s.recommendation.gates).map(([k,v])=>`<article><small>${esc(k)}</small><strong>${v?"PASS":"OPEN"}</strong></article>`).join(""):"";
$("pppLocations").innerHTML=(s.locationObjectives||[]).map(x=>`<article><strong>${esc(x.locationName)} · ${esc(x.owner||"Unassigned")}</strong><p>${esc(x.objective)}</p><div class="hpc-meta"><span>Readiness ${x.readiness.current}${x.readiness.target!=null?` / ${x.readiness.target}`:""}</span><span>Rhythm ${x.rhythm.current}%${x.rhythm.target!=null?` / ${x.rhythm.target}%`:""}</span><span>Leakage ${money(x.leakage.current)}</span><span>Reduction ${x.leakage.reductionPercent}%</span><span>Targets ${x.targetsMet}/${x.targetsMeasured}</span></div></article>`).join("")||"<article><span>No location objectives available.</span></article>";
$("pppTrend").innerHTML=(s.trend||[]).map(x=>`<article><strong>${esc(x.label)}</strong><span>Readiness ${x.readiness} · Rhythm ${x.rhythm}% · Leakage ${money(x.leakage)} · Verified ${money(x.verifiedValue)}${x.overall==null?"":` · Score ${x.overall}`}</span></article>`).join("");
$("pppExceptionList").innerHTML=(s.exceptions||[]).map(x=>`<article><strong>${esc(x.locationName)} · ${esc(x.type)}</strong><span>${esc(x.reason)} · Owner ${esc(x.owner||"Unassigned")}</span></article>`).join("")||"<article><strong>No current proof-program exceptions.</strong></article>";}
async function load(){try{render(await e.snapshot());}catch(err){$("pppHeadline").textContent=err.message;}}
$("pppRefresh")?.addEventListener("click",load);$("pppConfigure")?.addEventListener("click",async()=>{try{await e.configure({defaultOwner:$("pppOwner").value||"Executive Sponsor",minimumOverallScore:Number($("pppMinOverall").value||65),minimumAdoptionScore:65,minimumOperatingScore:65,minimumValueScore:50,maximumHighAttentionLocations:0});await load();}catch(err){$("pppHeadline").textContent=err.message;}});
["pilot-value:started","pilot-value:checkpoint","pilot-value:updated","multi-location-performance:updated","auth:restored"].forEach(evt=>eventBus?.on?.(evt,load));load();return{engine:e,load};}
window.createBlueCurrentPilotProofProgramCenterModule=createBlueCurrentPilotProofProgramCenterModule;})();