(function(){"use strict";
function createBlueCurrentPredictiveShiftControlCenterModule(eventBus,appState){const root=document.getElementById("predictiveShiftControl");if(!root||!window.BlueCurrentPredictiveShiftControlEngine)return null;const e=new window.BlueCurrentPredictiveShiftControlEngine({eventBus,appState}),$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
function tone(n){return n>=88?"CRITICAL":n>=75?"ACTION":n>=60?"WATCH":"STABLE";}
function render(s){const m=s.summary||{};$("pshiftEta").textContent=m.timeToConstraintMinutes==null?"CLEAR":`${m.timeToConstraintMinutes}m`;$("pshiftConstraint").textContent=m.firstConstraint?String(m.firstConstraint).toUpperCase():"NONE";$("pshiftPeak").textContent=`${m.peakOverallPressure||0}`;$("pshiftConfidence").textContent=`${m.confidence||0}%`;$("pshiftActions").textContent=m.interventionCount||0;$("pshiftHeadline").textContent=s.headline||"No modeled service dimension crosses the intervention threshold.";
$("pshiftForecast").innerHTML=(s.forecast||[]).map(x=>`<article><small>${x.minutes===0?"Now":`+${x.minutes}m`}</small><strong>${x.overall}</strong><span>${tone(x.overall)}</span><p>Host ${x.host} · Kitchen ${x.kitchen} · Labor ${x.labor} · Revenue ${x.revenue}</p></article>`).join("");
$("pshiftInterventions").innerHTML=(s.interventions||[]).map(x=>`<article data-pshift-id="${esc(x.id)}"><div><strong>#${x.rank} · ${esc(x.type)}</strong><span>${x.etaMinutes}m · pressure ${x.pressure} · ${esc(x.severity)}</span></div><p>${esc(x.detail)}</p><p><b>Preemptive action:</b> ${esc(x.action)}</p><small>${esc(x.owner)} · ${esc(x.expectedImpact)}</small>${x.lastDecision?`<small>Last decision: ${esc(x.lastDecision.decision)} · ${esc(x.lastDecision.owner)}</small>`:""}<div class="v4316-actions"><button type="button" data-pshift-decision="accepted">Own intervention</button><button type="button" data-pshift-decision="snoozed">Snooze</button><button type="button" data-pshift-decision="dismissed">Dismiss</button></div></article>`).join("")||"<article><strong>No intervention threshold crossed.</strong><span>Continue monitoring the next 90 minutes.</span></article>";
const sig=s.signals||{};$("pshiftSignals").innerHTML=`<article><small>Demand</small><strong>${sig.demand?.demandInventoryCovers||0} covers</strong><span>${sig.demand?.unassignedCovers||0} unassigned · ${sig.demand?.waitCovers||0} waitlist</span></article><article><small>Tables</small><strong>${sig.tables?.availableSeats||0} open seats</strong><span>${sig.tables?.unavailableSeats||0} unavailable</span></article><article><small>Kitchen</small><strong>${sig.kitchen?.activeTickets||0} tickets</strong><span>${sig.kitchen?.delayedTickets||0} delayed</span></article><article><small>Labor</small><strong>${sig.labor?.staffingGap||0} gap</strong><span>${sig.labor?.staffScheduled||0}/${sig.labor?.staffRequired||0} scheduled/required</span></article>`;$("pshiftMethod").textContent=s.methodology?.caveat||"";}
async function load(){try{$("pshiftHeadline").textContent="Forecasting the next 90 minutes…";render(await e.snapshot());}catch(err){$("pshiftHeadline").textContent=err.message;}}
root.addEventListener("click",async ev=>{const btn=ev.target.closest("[data-pshift-decision]"),card=ev.target.closest("[data-pshift-id]");if(!btn||!card)return;try{btn.disabled=true;await e.decide(card.dataset.pshiftId,btn.dataset.pshiftDecision,$("pshiftOwner").value||"Manager",$("pshiftNote").value||"");await load();}catch(err){$("pshiftHeadline").textContent=err.message;}finally{btn.disabled=false;}});
$("pshiftRefresh")?.addEventListener("click",load);eventBus?.on?.("hospitality-action:updated",load);eventBus?.on?.("reservation:updated",load);eventBus?.on?.("inventory:action-recorded",load);eventBus?.on?.("workforce:action-recorded",load);eventBus?.on?.("auth:restored",load);window.addEventListener?.("online",load);load();return{engine:e,load};}
window.createBlueCurrentPredictiveShiftControlCenterModule=createBlueCurrentPredictiveShiftControlCenterModule;})();