(function(global){"use strict";
class BlueCurrentRetirementCandidateSelectionEngine{
  constructor({eventBus,appState,rationalizationEngine,consolidationEngine,assuranceEngine}={}){this.eventBus=eventBus;this.appState=appState;this.rationalizationEngine=rationalizationEngine;this.consolidationEngine=consolidationEngine;this.assuranceEngine=assuranceEngine;}
  state(){try{return this.appState?.getState?.()||{};}catch{return {};}}
  token(){return localStorage.getItem("blueCurrentV3230Token")||"";}
  protectedSurfaces(){const roles=["manager","executive","technical"],map={};for(const role of roles)for(const id of this.consolidationEngine?.defaultSurfaces?.(role)||[]){map[id] ||= [];map[id].push(role);}return map;}
  retiredSurfaces(assurance){return new Set((assurance?.items||[]).map(x=>x.surfaceId).filter(Boolean));}
  candidatePool(assurance){const rational=this.rationalizationEngine?.snapshot?.()||{items:[]},protectedMap=this.protectedSurfaces(),retired=this.retiredSurfaces(assurance);return rational.items.filter(x=>x.disposition==="deprecation-candidate"&&!retired.has(x.id)).map(x=>({...x,protectedRoles:protectedMap[x.id]||[]}));}
  async impact(surfaceIds){const r=await fetch("/api/operator-fine-comb/candidate-impact",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${this.token()}`},body:JSON.stringify({surfaceIds})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Candidate impact failed (${r.status})`);return d;}
  clusterSignal(id,pool){const prefix=(String(id).match(/^(executive|enterprise|portfolio|district|innovation|scenario|strategy|planning|forecast|learning|expansion)/i)||[])[1]?.toLowerCase()||"other",siblings=pool.filter(x=>x.id!==id&&x.id.toLowerCase().startsWith(prefix)).length;return {prefix,siblings,score:Math.min(100,20+siblings*8)};}
  scoreCandidate(candidate,impact,pool,evidenceMap){const ev=evidenceMap.get(candidate.id)||{uses:0,roles:[],hasEvidence:false},uses=Number(ev.uses||0),useIndependence=uses===0?100:uses===1?70:uses===2?45:Math.max(0,35-(uses-3)*5),protectedRoles=candidate.protectedRoles||[],workflowIndependence=protectedRoles.length===0?100:Math.max(0,100-protectedRoles.length*45),i=impact?.impact||{},removalCost=Math.min(100,(i.ownedFiles||0)*10+(i.startupDependencies||0)*12+(i.apiReferences||0)*15+(i.operationalInboundReferences||0)*10),repositoryEase=Math.max(0,100-removalCost),cluster=this.clusterSignal(candidate.id,pool),score=Math.round(useIndependence*.35+workflowIndependence*.30+repositoryEase*.25+cluster.score*.10);const blockers=[];if(protectedRoles.length)blockers.push(`Protected by ${protectedRoles.join(", ")} default navigation.`);if(uses>0)blockers.push(`${uses} observed operator-use event(s).`);if((i.apiReferences||0)>0)blockers.push(`${i.apiReferences} API reference(s) require review.`);return {surfaceId:candidate.id,score,rank:null,operatorUseEvents:uses,operatorUseRoles:ev.roles||[],protectedRoles,workflowIndependence,useIndependence,repositoryEase,clusterRedundancy:cluster.score,cluster:cluster.prefix,clusterSiblings:cluster.siblings,impact:i,blockers,eligibleForSelection:protectedRoles.length===0,automaticSelection:false,automaticDeletion:false};}
  async rank(){const assurance=await this.assuranceEngine?.snapshot?.();if(!assurance?.nextCandidateGate?.eligible)throw new Error(assurance?.nextCandidateGate?.reason||"Post-retirement assurance gate is closed.");const pool=this.candidatePool(assurance),impactResult=await this.impact(pool.map(x=>x.id));if(!impactResult.gateOpen)throw new Error(impactResult.reason||"Candidate impact gate is closed.");const impactMap=new Map((impactResult.items||[]).map(x=>[x.surfaceId,x])),evidence=new Map((this.consolidationEngine?.evidenceSummary?.(pool.map(x=>x.id))||[]).map(x=>[x.surfaceId,x]));const ranked=pool.map(x=>this.scoreCandidate(x,impactMap.get(x.id),pool,evidence)).sort((a,b)=>b.score-a.score||a.surfaceId.localeCompare(b.surfaceId));ranked.forEach((x,i)=>x.rank=i+1);const selectable=ranked.filter(x=>x.eligibleForSelection),result={version:"46.60.0",capturedAt:new Date().toISOString(),assuranceDigest:assurance.digest,poolSize:pool.length,protectedCount:ranked.filter(x=>x.protectedRoles.length).length,ranked,top3:selectable.slice(0,3),selected:this.state().operatorNextRetirementSelection||null,policy:"rank-top-three-then-require-explicit-selection",automaticSelection:false,automaticDeletion:false};this.appState?.update?.({operatorRetirementCandidateRanking:result});this.eventBus?.emit?.("operator-retirement-candidates:ranked",structuredClone(result));return result;}
  select(candidate,rationale=""){if(!candidate?.surfaceId)throw new Error("A ranked candidate is required.");if(candidate.eligibleForSelection!==true)throw new Error("Protected workflow surfaces cannot be selected.");const ranking=this.state().operatorRetirementCandidateRanking;if(!ranking?.top3?.some(x=>x.surfaceId===candidate.surfaceId))throw new Error("Selection is limited to the current top-three shortlist.");const record={id:`NRCS-${Date.now().toString(36).toUpperCase()}`,surfaceId:candidate.surfaceId,rank:candidate.rank,score:candidate.score,rationale:String(rationale||"").slice(0,500),selectedAt:new Date().toISOString(),assuranceDigest:ranking.assuranceDigest,status:"selected-for-preview-pipeline-only",previewStarted:false,codeDeletionAllowed:false,deletionExecuted:false};this.appState?.update?.({operatorNextRetirementSelection:record});this.eventBus?.emit?.("operator-retirement-candidate:selected",structuredClone(record));return record;}
  clearSelection(){this.appState?.update?.({operatorNextRetirementSelection:null});return null;}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentRetirementCandidateSelectionEngine;
if(global)global.BlueCurrentRetirementCandidateSelectionEngine=BlueCurrentRetirementCandidateSelectionEngine;
})(typeof window!=="undefined"?window:globalThis);