(function(global){"use strict";
class BlueCurrentSelectedCandidatePreviewEngine{
  constructor({eventBus,appState,consolidationEngine,scorecardEngine}={}){this.eventBus=eventBus;this.appState=appState;this.consolidationEngine=consolidationEngine;this.scorecardEngine=scorecardEngine;}
  state(){try{return this.appState?.getState?.()||{};}catch{return {};}}
  token(){return localStorage.getItem("blueCurrentV3230Token")||"";}
  selection(){return this.state().operatorNextRetirementSelection||null;}
  preview(){return this.state().operatorSelectedCandidatePreview||null;}
  observations(){return Array.isArray(this.state().operatorSelectedCandidatePreviewEvidence)?this.state().operatorSelectedCandidatePreviewEvidence:[];}
  taskQuality(){const metrics=this.consolidationEngine?.taskMetrics?.()||[],total=metrics.reduce((s,x)=>s+x.total,0),succeeded=metrics.reduce((s,x)=>s+x.succeeded,0),failed=metrics.reduce((s,x)=>s+x.failed,0),durations=metrics.filter(x=>Number.isFinite(x.averageResolutionMs)&&x.total>0),avg=durations.length?Math.round(durations.reduce((s,x)=>s+x.averageResolutionMs*x.total,0)/durations.reduce((s,x)=>s+x.total,0)):null;return {byRole:metrics,total,succeeded,failed,successRate:total?Math.round(100*succeeded/total):100,averageResolutionMs:avg,averageResolutionMinutes:avg==null?null:Math.round(avg/600)/100};}
  workflowCoverage(){return this.scorecardEngine?.workflowCoverage?.("manager")||{required:6,covered:0,percent:0,coveredCenters:[],missingCenters:[]};}
  evidenceFor(surfaceId){return this.consolidationEngine?.evidenceSummary?.([surfaceId])?.[0]||{surfaceId,uses:0,lastUsedAt:null,roles:[],hasEvidence:false};}
  applyVisibility(surfaceId,hidden){if(typeof document==="undefined")return;const el=document.getElementById(surfaceId);if(!el)return;if(hidden){el.hidden=true;el.setAttribute("aria-hidden","true");el.setAttribute("inert","");}else{el.hidden=false;el.removeAttribute("aria-hidden");el.removeAttribute("inert");}document.documentElement.dataset.selectedCandidatePreview=hidden?surfaceId:"none";}
  begin(){const selected=this.selection();if(!selected?.surfaceId)throw new Error("Explicit candidate selection is required before preview.");if(selected.status!=="selected-for-preview-pipeline-only")throw new Error("Selected candidate is not eligible for preview.");const existing=this.preview();if(existing?.active&&existing.surfaceId!==selected.surfaceId)throw new Error("Another candidate preview is already active.");const baseline={workflow:this.workflowCoverage(),operatorUse:this.evidenceFor(selected.surfaceId),taskQuality:this.taskQuality(),capturedAt:new Date().toISOString()};const preview={id:`SCPV-${Date.now().toString(36).toUpperCase()}`,surfaceId:selected.surfaceId,selectionId:selected.id,selectionRank:selected.rank,selectionScore:selected.score,status:"reversible-preview-active",startedAt:new Date().toISOString(),baseline,ownerSignoff:null,impact:null,active:true,reversible:true,codeDeletionAllowed:false,deletionExecuted:false};this.appState?.update?.({operatorSelectedCandidatePreview:preview,operatorNextRetirementSelection:{...selected,previewStarted:true}});this.applyVisibility(preview.surfaceId,true);this.eventBus?.emit?.("operator-selected-candidate-preview:started",structuredClone(preview));return preview;}
  stop(reason="manual restore"){const p=this.preview();if(!p)return null;this.applyVisibility(p.surfaceId,false);const next={...p,status:"preview-restored",active:false,restoredAt:new Date().toISOString(),restoreReason:String(reason||"manual restore").slice(0,300),codeDeletionAllowed:false,deletionExecuted:false};this.appState?.update?.({operatorSelectedCandidatePreview:next});this.eventBus?.emit?.("operator-selected-candidate-preview:restored",structuredClone(next));return next;}
  recordObservation({workflowCoverage=null,taskFailures=0,regressions=0,note="",at=null}={}){const p=this.preview();if(!p?.active)throw new Error("An active reversible preview is required.");const coverage=workflowCoverage??this.workflowCoverage().percent,quality=this.taskQuality(),usage=this.evidenceFor(p.surfaceId),entry={id:`SCPVE-${Date.now().toString(36).toUpperCase()}`,previewId:p.id,surfaceId:p.surfaceId,at:at||new Date().toISOString(),workflowCoverage:Number(coverage),taskFailures:Number(taskFailures||0),regressions:Number(regressions||0),taskSuccessRate:quality.successRate,averageResolutionMinutes:quality.averageResolutionMinutes,operatorUseEvents:usage.uses,note:String(note||"").slice(0,500)};const next=[entry,...this.observations()].slice(0,300);this.appState?.update?.({operatorSelectedCandidatePreviewEvidence:next});this.eventBus?.emit?.("operator-selected-candidate-preview:observed",structuredClone(entry));return entry;}
  ownerSignoff(owner,decision="approve",note=""){const p=this.preview();if(!p)throw new Error("Candidate preview is required.");const signoff={owner:String(owner||"Owner"),decision:String(decision),note:String(note||"").slice(0,500),at:new Date().toISOString()};const next={...p,ownerSignoff:signoff};this.appState?.update?.({operatorSelectedCandidatePreview:next});return signoff;}
  async refreshImpact(){const p=this.preview();if(!p?.surfaceId)throw new Error("Candidate preview is required.");const r=await fetch("/api/operator-fine-comb/candidate-impact",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${this.token()}`},body:JSON.stringify({surfaceIds:[p.surfaceId]})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Candidate impact failed (${r.status})`);const impact=d.items?.[0]||null,next={...p,impact,impactRefreshedAt:new Date().toISOString()};this.appState?.update?.({operatorSelectedCandidatePreview:next});return impact;}
  readiness(){const p=this.preview(),selected=this.selection();if(!p)return {score:0,status:"preview-not-started",checks:[],eligibleForCertification:false};const obs=this.observations().filter(x=>x.previewId===p.id),days=[...new Set(obs.map(x=>String(x.at).slice(0,10)))],currentWorkflow=this.workflowCoverage(),quality=this.taskQuality(),usage=this.evidenceFor(p.surfaceId),checks=[
    {id:"selection-binding",pass:Boolean(selected)&&selected.id===p.selectionId&&selected.surfaceId===p.surfaceId,detail:selected?.id||"selection missing"},
    {id:"reversible-preview",pass:p.reversible===true,detail:p.active?"active":"restored"},
    {id:"observation-count",pass:obs.length>=3,detail:`${obs.length}/3 observation(s)`},
    {id:"observation-days",pass:days.length>=3,detail:`${days.length}/3 distinct day(s)`},
    {id:"workflow-coverage",pass:currentWorkflow.percent===100&&obs.every(x=>x.workflowCoverage===100),detail:`${currentWorkflow.percent}% current`},
    {id:"preview-regressions",pass:obs.every(x=>x.regressions===0&&x.taskFailures===0),detail:`${obs.reduce((s,x)=>s+x.regressions+x.taskFailures,0)} regression/failure signal(s)`},
    {id:"task-success",pass:quality.successRate>=95,detail:`${quality.successRate}% task success`},
    {id:"operator-use-delta",pass:usage.uses<=Number(p.baseline?.operatorUse?.uses||0),detail:`baseline ${p.baseline?.operatorUse?.uses||0} · current ${usage.uses}`},
    {id:"owner-signoff",pass:p.ownerSignoff?.decision==="approve",detail:p.ownerSignoff?`${p.ownerSignoff.owner} · ${p.ownerSignoff.decision}`:"missing"},
    {id:"impact-refresh",pass:Boolean(p.impact),detail:p.impact?`${p.impact.impact?.operationalInboundReferences||0} operational inbound · ${p.impact.impact?.apiReferences||0} API`:"not refreshed"},
    {id:"no-delete-capability",pass:p.codeDeletionAllowed===false&&p.deletionExecuted===false,detail:"Preview/evidence only"}
  ];const score=Math.round(checks.reduce((s,x)=>s+(x.pass?100:0),0)/checks.length),eligible=checks.every(x=>x.pass);return {score,status:eligible?"preview-evidence-complete":"preview-evidence-incomplete",checks,eligibleForCertification:eligible,observations:obs.length,observedDays:days.length,currentWorkflow,taskQuality:quality,currentOperatorUse:usage,version:"46.65.0",codeDeletionAllowed:false,deletionExecuted:false};}
  snapshot(){const p=this.preview();return {version:"46.65.0",selection:this.selection(),preview:p,readiness:p?this.readiness():null,observations:p?this.observations().filter(x=>x.previewId===p.id):[],policy:"selected-candidate-reversible-preview-before-certification",automaticCertification:false,automaticDeletion:false};}
}
if(typeof module!=="undefined"&&module.exports)module.exports=BlueCurrentSelectedCandidatePreviewEngine;
if(global)global.BlueCurrentSelectedCandidatePreviewEngine=BlueCurrentSelectedCandidatePreviewEngine;
})(typeof window!=="undefined"?window:globalThis);