(function(){
"use strict";
const CONNECTORS=[
 {id:"toast",name:"Toast POS",category:"POS",status:"healthy",events:1284,latency:86,uptime:99.98},
 {id:"opentable",name:"OpenTable",category:"Reservations",status:"healthy",events:642,latency:112,uptime:99.94},
 {id:"twilio",name:"Twilio",category:"Voice & SMS",status:"warning",events:388,latency:248,uptime:98.72},
 {id:"stripe",name:"Stripe",category:"Payments",status:"healthy",events:214,latency:97,uptime:99.99},
 {id:"google",name:"Google Calendar",category:"Calendar",status:"healthy",events:96,latency:131,uptime:99.91},
 {id:"doordash",name:"DoorDash",category:"Delivery",status:"healthy",events:174,latency:156,uptime:99.84},
 {id:"ubereats",name:"Uber Eats",category:"Delivery",status:"offline",events:0,latency:0,uptime:0},
 {id:"outlook",name:"Microsoft Outlook",category:"Calendar",status:"healthy",events:72,latency:144,uptime:99.76}
];
class ConnectorSDK{
 constructor(bus,state){this.bus=bus;this.state=state;this.registry=new Map();}
 register(connector){if(!connector?.id)throw new Error("Connector requires an id");this.registry.set(connector.id,{...connector,connected:connector.status!=="offline",lastSync:new Date()});this.bus.emit("connector:registered",{connector:this.registry.get(connector.id)});return this.registry.get(connector.id);}
 connect(id){const c=this.registry.get(id);if(!c)return false;c.connected=true;c.status="healthy";c.lastSync=new Date();this.bus.emit("connector:connected",{connector:c});return true;}
 disconnect(id){const c=this.registry.get(id);if(!c)return false;c.connected=false;c.status="offline";this.bus.emit("connector:disconnected",{connector:c});return true;}
 publish(id,event,payload={}){const c=this.registry.get(id);if(!c||!c.connected)return false;c.events=(c.events||0)+1;c.lastSync=new Date();this.bus.emit("connector:event",{source:id,event,payload,timestamp:c.lastSync.toISOString()});this.bus.emit(event,{...payload,source:id});return true;}
 health(){return [...this.registry.values()].map(c=>({...c,healthScore:c.status==="healthy"?98:c.status==="warning"?78:0}));}
}
window.createConnectorPlatformModule=function(eventBus,appState){
 const root=document.getElementById("connect-platform");if(!root)return null;
 const $=id=>document.getElementById(id);const sdk=new ConnectorSDK(eventBus,appState);CONNECTORS.forEach(c=>sdk.register(c));window.blueCurrentConnectors=sdk;
 const nodes={grid:$("connectorGrid"),events:$("connectorInspectorFeed"),filter:$("connectorEventFilter"),summary:$("integrationSummary"),playMethod:$("apiMethod"),playEndpoint:$("apiEndpoint"),playPayload:$("apiPayload"),send:$("apiSend"),response:$("apiResponse"),market:$("connectorMarketplace"),security:$("securityAudit"),pulse:$("connectorHealthPulse"),stats:$("connectorStats")};
 let inspected=[];
 const escape=s=>String(s??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
 function renderConnectors(){const list=sdk.health();nodes.grid.innerHTML=list.map(c=>`<article class="connect-card ${c.status}" data-id="${c.id}"><div class="connect-card-head"><span class="connect-icon">${c.name.slice(0,2).toUpperCase()}</span><div><strong>${escape(c.name)}</strong><small>${escape(c.category)}</small></div><i title="${c.status}"></i></div><div class="connect-metrics"><span><b>${Number(c.events).toLocaleString()}</b> events</span><span><b>${c.latency||"—"}</b> ms</span><span><b>${c.uptime?c.uptime.toFixed(2):"0.00"}%</b> uptime</span></div><div class="connect-actions"><button data-connect-action="${c.connected?'test':'connect'}" data-id="${c.id}">${c.connected?'Test':'Connect'}</button><button data-connect-action="logs" data-id="${c.id}">Logs</button></div></article>`).join("");
 const healthy=list.filter(c=>c.status==="healthy").length, totalEvents=list.reduce((a,c)=>a+(c.events||0),0), avg=Math.round(list.filter(c=>c.latency).reduce((a,c)=>a+c.latency,0)/list.filter(c=>c.latency).length);nodes.stats.innerHTML=`<div><strong>${healthy}/${list.length}</strong><span>Healthy</span></div><div><strong>${totalEvents.toLocaleString()}</strong><span>Events processed</span></div><div><strong>${avg} ms</strong><span>Average latency</span></div><div><strong>99.62%</strong><span>Platform uptime</span></div>`;}
 function addInspection(name,payload={}){inspected.unshift({time:new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit",second:"2-digit"}),name,source:payload.source||payload.connector?.name||"Blue Current",payload});inspected=inspected.slice(0,80);renderEvents();}
 function renderEvents(){const q=(nodes.filter.value||"").toLowerCase();const list=inspected.filter(e=>(e.name+e.source+JSON.stringify(e.payload)).toLowerCase().includes(q));nodes.events.innerHTML=list.length?list.map(e=>`<button class="inspector-event"><time>${e.time}</time><span><strong>${escape(e.name)}</strong><small>${escape(e.source)}</small></span><code>${escape(JSON.stringify(e.payload).slice(0,120))}</code></button>`).join(""):`<p class="connect-empty">No matching integration events.</p>`;}
 function integrationBrief(){const health=sdk.health(),warning=health.find(c=>c.status==="warning"),offline=health.filter(c=>!c.connected);nodes.summary.innerHTML=`<span>AI integration monitor</span><h3>${offline.length?"One connection needs attention":"Integration fabric is stable"}</h3><p>${warning?`${warning.name} is responding more slowly than normal. Retry its webhook handshake during the next low-volume window.`:"All active connectors are publishing normalized events into shared App State."}</p><div><b>Recommendation</b><small>${offline.length?`Configure ${offline.map(c=>c.name).join(", ")}.`:"No immediate action required."}</small></div>`;}
 function runApi(){let payload={};try{payload=JSON.parse(nodes.playPayload.value||"{}");}catch(e){nodes.response.textContent="Invalid JSON: "+e.message;return;}const endpoint=nodes.playEndpoint.value;let event="api:request";if(endpoint.includes("reservation"))event="reservation:confirmed";else if(endpoint.includes("call"))event="concierge:call-started";else if(endpoint.includes("payment"))event="payment:captured";else if(endpoint.includes("walkin"))event="guest:arrived";sdk.publish("api-playground",event,{...payload,source:"API Playground"});if(event==="reservation:confirmed"&&payload.reservation){appState.appendReservation?.(payload.reservation);appState.update?.({occupancyPercent:Math.min(100,(appState.get("occupancyPercent")||78)+3),lastOperationalEvent:{event,source:"API Playground"}});}nodes.response.textContent=JSON.stringify({status:202,accepted:true,event,requestId:"bc_"+Date.now().toString(36)},null,2);}
 root.addEventListener("click",e=>{const btn=e.target.closest("[data-connect-action]");if(btn){const id=btn.dataset.id,action=btn.dataset.connectAction;if(action==="connect")sdk.connect(id);if(action==="test")sdk.publish(id,"connector:test-succeeded",{connector:id,latency:Math.floor(70+Math.random()*120)});if(action==="logs"){nodes.filter.value=id;renderEvents();nodes.events.scrollIntoView({behavior:"smooth",block:"center"});}renderConnectors();integrationBrief();}
 const install=e.target.closest("[data-market-install]");if(install){const id=install.dataset.marketInstall;install.textContent="Installed";install.disabled=true;eventBus.emit("connector:marketplace-installed",{source:"Marketplace",connector:id});}});
 nodes.filter.addEventListener("input",renderEvents);nodes.send.addEventListener("click",runApi);nodes.pulse.addEventListener("click",()=>{nodes.pulse.disabled=true;nodes.pulse.textContent="Running health pulse…";[...sdk.registry.keys()].forEach((id,i)=>setTimeout(()=>sdk.publish(id,"connector:heartbeat",{connector:id,status:"healthy"}),i*180));setTimeout(()=>{nodes.pulse.disabled=false;nodes.pulse.textContent="Run connector health pulse";renderConnectors();integrationBrief();},1800);});
 const originalEmit=eventBus.emit.bind(eventBus);if(!eventBus.__connectorInspectorWrapped){eventBus.emit=function(name,payload){const result=originalEmit(name,payload);try{if(name.startsWith("connector:")||name.startsWith("api:")||payload?.source)addInspection(name,payload||{});}catch{}return result;};eventBus.__connectorInspectorWrapped=true;}
 nodes.market.innerHTML=["Square","Resy","SevenRooms","Clover","Lightspeed","Oracle Simphony"].map((n,i)=>`<article><span>${i<2?"Official":"Coming soon"}</span><strong>${n}</strong><p>Normalized events, health monitoring, logs and App State synchronization.</p><button data-market-install="${n.toLowerCase().replaceAll(" ","-")}" ${i>1?"disabled":""}>${i>1?"Waitlist":"Install"}</button></article>`).join("");
 nodes.security.innerHTML=`<li><span>Webhook signatures</span><b>Verified</b></li><li><span>OAuth token health</span><b>7 active</b></li><li><span>Credentials exposed to browser</span><b>None</b></li><li><span>Last audit event</span><b>Just now</b></li>`;
 renderConnectors();integrationBrief();addInspection("connector:platform-ready",{source:"Blue Current Connect",connectors:CONNECTORS.length});return{sdk,render:renderConnectors};
};window.BlueCurrentConnectorSDK=ConnectorSDK;
})();