(function(){"use strict";
function createServiceCoordinationModule(eventBus,appState,cloudFoundationModule){
 const api=cloudFoundationModule?.api||new window.BlueCurrentCloudApi(""); const $=id=>document.getElementById(id); let state={flows:[],alerts:[],events:[],metrics:{},staff:[]}; let filter="all";
 const mins=v=>Math.max(0,Math.floor((Date.now()-new Date(v))/60000));
 function render(){const m=state.metrics||{};$("svcActive").textContent=m.activeTables||0;$("svcReady").textContent=m.readyForRunner||0;$("svcRisk").textContent=m.highRisk||0;$("svcHealth").textContent=`${m.operationalHealth||0}%`;
  const flows=filter==="all"?state.flows:state.flows.filter(x=>x.risk===filter||x.expoStatus===filter);
  $("svcFlowBody").innerHTML=flows.map(x=>`<tr><td><strong>${x.tableName}</strong><small>${x.guestName}</small></td><td>${x.serverName}</td><td><select data-flow-course="${x.id}">${["seated","drinks","appetizer","entree","food-delivered","dessert","check","closed"].map(v=>`<option ${v===x.course?"selected":""}>${v}</option>`).join("")}</select></td><td><span class="svc-pill ${x.kitchenStatus}">${x.kitchenStatus}</span></td><td><span class="svc-pill ${x.expoStatus}">${x.expoStatus}</span></td><td>${mins(x.seatedAt)}m</td><td><span class="svc-risk ${x.risk}">${x.risk}</span></td><td>${x.expoStatus==="ready"?`<button class="button button-gold svc-deliver" data-deliver="${x.id}">Deliver</button>`:"—"}</td></tr>`).join("")||`<tr><td colspan="8">No active service flows.</td></tr>`;
  $("svcExpoQueue").innerHTML=state.flows.filter(x=>x.expoStatus==="ready"||x.expoStatus==="assigned").map(x=>`<article><div><small>${x.tableName}</small><strong>${x.guestName}</strong><span>${x.serverName}</span></div><div><b>${x.readyAt?mins(x.readyAt):0}m</b><button class="button button-gold" data-deliver="${x.id}">Run food</button></div></article>`).join("")||`<p class="svc-empty">Expo is clear.</p>`;
  $("svcAlerts").innerHTML=state.alerts.map(a=>`<article class="${a.severity}"><i></i><div><strong>${a.title}</strong><p>${a.detail}</p></div></article>`).join("")||`<p class="svc-empty">No active operational alerts.</p>`;
  const loads={};state.flows.filter(x=>x.course!=="closed").forEach(x=>loads[x.serverName]=(loads[x.serverName]||0)+x.partySize);$("svcServerLoad").innerHTML=state.staff.filter(x=>x.role==="Server").map(x=>{const n=loads[x.name]||0,p=Math.min(100,Math.round(n/(x.maxCovers||24)*100));return `<article><div><strong>${x.name}</strong><span>${n}/${x.maxCovers||24} covers</span></div><i><b style="width:${p}%"></b></i></article>`}).join("");
  appState.update({serviceHealth:m.operationalHealth,serviceAlerts:state.alerts.length,expoReady:m.readyForRunner});
 }
 async function load(){if(!api.token)return;state=await api.serviceCoordination("loc_marina");render();eventBus.emit("service:coordination-loaded",state.metrics);}
 $("svcFilters")?.addEventListener("click",e=>{const b=e.target.closest("[data-svc-filter]");if(!b)return;filter=b.dataset.svcFilter;document.querySelectorAll("[data-svc-filter]").forEach(x=>x.classList.toggle("active",x===b));render();});
 $("serviceCoordination")?.addEventListener("change",async e=>{const s=e.target.closest("[data-flow-course]");if(!s)return;await api.updateServiceFlow(s.dataset.flowCourse,{course:s.value});await load();});
 $("serviceCoordination")?.addEventListener("click",async e=>{const b=e.target.closest("[data-deliver]");if(!b)return;await api.deliverServiceFlow(b.dataset.deliver);await load();});
 ["auth:signed-in","auth:restored","service:guest-seated","service:flow-updated","kitchen:ticket-updated","kitchen:item-updated"].forEach(t=>eventBus.on?.(t,load));setInterval(load,60000);load();return{reload:load,getState:()=>state};
} window.createBlueCurrentServiceCoordinationModule=createServiceCoordinationModule;})();