"use strict";
const crypto=require("crypto");
const DAY=86400000;
function mondayOf(value=new Date()){const d=new Date(value);d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)}
class EmployeePortalService{
 constructor(database,auditService,realtimeHub){this.database=database;this.auditService=auditService;this.realtimeHub=realtimeHub;}
 async login(employeeId,pin){const db=await this.database.read();const employee=(db.employees||[]).find(x=>x.id===employeeId&&String(x.pin)===String(pin)&&x.status==="active");if(!employee)return null;const token=crypto.randomBytes(24).toString("hex"),session={id:`eps_${Date.now()}`,tokenHash:crypto.createHash("sha256").update(token).digest("hex"),employeeId:employee.id,organizationId:employee.organizationId,locationId:employee.locationId,expiresAt:new Date(Date.now()+12*60*60*1000).toISOString()};await this.database.create("employeePortalSessions",session);await this.auditService.record({organizationId:employee.organizationId,actor:employee.name,action:"Signed in to Employee Portal",category:"employee_portal"});return{token,employee:this.publicEmployee(employee),expiresAt:session.expiresAt};}
 async authenticate(token){if(!token)return null;const hash=crypto.createHash("sha256").update(token).digest("hex"),db=await this.database.read();const session=(db.employeePortalSessions||[]).find(x=>x.tokenHash===hash&&new Date(x.expiresAt)>new Date());if(!session)return null;const employee=(db.employees||[]).find(x=>x.id===session.employeeId&&x.status==="active");return employee?{session,employee}:null;}
 publicEmployee(e){return{id:e.id,name:e.name,role:e.role,department:e.department,locationId:e.locationId,weeklyHours:e.weeklyHours||0};}
 async snapshot(employeeId){const db=await this.database.read(),employee=(db.employees||[]).find(x=>x.id===employeeId);if(!employee)return null;const today=new Date().toISOString().slice(0,10),weekStart=mondayOf(today),weekEnd=new Date(new Date(`${weekStart}T12:00:00`).getTime()+6*DAY).toISOString().slice(0,10);const shifts=(db.scheduleShifts||[]).filter(x=>x.organizationId===employee.organizationId&&x.locationId===employee.locationId&&x.date>=weekStart&&x.date<=weekEnd);const mine=shifts.filter(x=>x.employeeId===employee.id).sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime));const open=shifts.filter(x=>!x.employeeId).sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime));const pto=(db.ptoRequests||[]).filter(x=>x.employeeId===employee.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const swaps=(db.shiftSwapRequests||[]).filter(x=>x.requesterEmployeeId===employee.id||x.targetEmployeeId===employee.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const notifications=(db.employeeNotifications||[]).filter(x=>x.employeeId===employee.id).slice(-20).reverse();return{employee:this.publicEmployee(employee),today,weekStart,weekEnd,todaysShift:mine.find(x=>x.date===today)||null,nextShift:mine.find(x=>x.date>=today)||null,myShifts:mine,openShifts:open,ptoRequests:pto,swapRequests:swaps,notifications,summary:{scheduledHours:mine.reduce((s,x)=>{const [sh,sm]=x.startTime.split(":").map(Number),[eh,em]=x.endTime.split(":").map(Number);return s+Math.max(0,(eh*60+em-sh*60-sm)/60)},0),openShiftCount:open.length,pendingPto:pto.filter(x=>x.status==="pending").length,unreadNotifications:notifications.filter(x=>!x.readAt).length}};}
 async requestPto(employee,input){
  const startDate=String(input.startDate||"").trim(),endDate=String(input.endDate||"").trim();
  const requestType=String(input.requestType||"vacation").trim().toLowerCase();
  const allowedTypes=new Set(["vacation","sick","personal","unpaid"]);
  if(!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||!/^\d{4}-\d{2}-\d{2}$/.test(endDate))throw new Error("Valid start and end dates are required.");
  if(endDate<startDate)throw new Error("The last day cannot be before the first day.");
  if(!allowedTypes.has(requestType))throw new Error("Select a valid time-off request type.");
  const reason=String(input.reason||"").trim();
  if(reason.length>300)throw new Error("The manager note must be 300 characters or fewer.");
  const db=await this.database.read();
  const duplicate=(db.ptoRequests||[]).some(x=>x.employeeId===employee.id&&x.status==="pending"&&x.startDate===startDate&&x.endDate===endDate);
  if(duplicate)throw new Error("You already have a pending request for those dates.");
  const row={id:`pto_${Date.now()}`,organizationId:employee.organizationId,employeeId:employee.id,startDate,endDate,requestType,reason,status:"pending",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
  await this.database.create("ptoRequests",row);
  await this.auditService.record({organizationId:employee.organizationId,actor:employee.name,action:`Requested ${requestType} time off ${row.startDate} to ${row.endDate}`,category:"employee_portal"});
  this.realtimeHub.publish("employee-portal:pto-created",row);
  return row;
 }
 async claimShift(employee,shiftId){return this.database.mutate(async db=>{const shift=(db.scheduleShifts||[]).find(x=>x.id===shiftId&&x.organizationId===employee.organizationId&&x.locationId===employee.locationId);if(!shift)throw new Error("Open shift not found.");if(shift.employeeId)throw new Error("This shift has already been assigned.");shift.employeeId=employee.id;shift.status="draft";shift.updatedAt=new Date().toISOString();db.employeeNotifications||=[];db.employeeNotifications.push({id:`note_${Date.now()}`,employeeId:employee.id,title:"Open shift claimed",message:`${shift.role} on ${shift.date}, ${shift.startTime}–${shift.endTime}`,createdAt:new Date().toISOString(),readAt:null});return shift;}).then(async shift=>{await this.auditService.record({organizationId:employee.organizationId,actor:employee.name,action:`Claimed open ${shift.role} shift on ${shift.date}`,category:"employee_portal"});this.realtimeHub.publish("employee-portal:shift-claimed",shift);return shift;});}
 async requestSwap(employee,input){const db=await this.database.read(),shift=(db.scheduleShifts||[]).find(x=>x.id===input.shiftId&&x.employeeId===employee.id);if(!shift)throw new Error("Assigned shift not found.");const row={id:`swap_${Date.now()}`,organizationId:employee.organizationId,locationId:employee.locationId,shiftId:shift.id,requesterEmployeeId:employee.id,targetEmployeeId:input.targetEmployeeId||null,reason:String(input.reason||""),status:"pending",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await this.database.create("shiftSwapRequests",row);await this.auditService.record({organizationId:employee.organizationId,actor:employee.name,action:`Requested shift swap for ${shift.date}`,category:"employee_portal"});this.realtimeHub.publish("employee-portal:swap-created",row);return row;}
 async markRead(employee,id){const row=await this.database.get("employeeNotifications",id);if(!row||row.employeeId!==employee.id)return null;return this.database.update("employeeNotifications",id,{readAt:new Date().toISOString()});}
}
module.exports=EmployeePortalService;
